- 08.Server-integration/03.Client-certificates/docs.md
changelog: none
Signed-off-by: Marcin Chalczynski <m.chalczynski@gmail.com>
Thank you!
> 08.Server-integration/03.Client-certificates: fix CA cert mount point

- 05.System-updates-Yocto-Project/05.Customize-Mender/01.Delta-update-support/docs.md
> MEN-3953: update instuctions to download `mender-binary-delta`

- 08.Server-integration/03.Client-certificates/docs.md
> mtls: Specify proper mtls key.

- 202.Release-information/01.Release-notes-changelog/docs.md
> [2.5.x] Changelog and statistics for meta-mender maintenance releases

- .gitlab-ci.yml
- .passive-blacklist
- 02.Overview/05.Device-integration/docs.md
- 02.Overview/06.Delta-update/docs.md
- 02.Overview/14.Compatibility/docs.md
- scripts/passive.sh
- scripts/run-passive.sh
* Some minor cleanups of the `passive-voice.sh` script
* A new script to select the files to be checked using a blacklist
* A new job in Gitlab-CI to enforce this on master
> MEN-4020: Enable the passive-voice checker in CI

- .passive-blacklist
- 03.Client-installation/01.Overview/docs.md
- 03.Client-installation/02.Install-with-Debian-package/docs.md
- 03.Client-installation/06.Configuration-file/01.Polling-intervals/docs.md
- 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
- 03.Client-installation/06.Configuration-file/docs.md
> MEN-4021: Remove passive voice from the Client-installation section.

- 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/01.Customization/docs.md
Signed-off-by: Alin Alexandru <alin.alexandru@innobyte.com>
Documentation for https://github.com/mendersoftware/mender-convert/pull/238
> Update docs for overlay hook feature

- 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> MEN-3924 Allow to load private key from the Security conf section

- 07.Server-installation/07.Upgrading/docs.md
same as https://github.com/mendersoftware/mender-docs/pull/1208 but for 2.5.x branch
> Server-installation/Upgrading: add information about upgrading MongoDB

- .passive-blacklist
- 08.Server-integration/02.Preauthorizing-devices/docs.md
- 08.Server-integration/03.Client-certificates/docs.md
https://tracker.mender.io/browse/MEN-4026
Thank you!
> passive checker: unblacklist 08.Server-integration

- .passive-blacklist
- 04.System-updates-Debian-family/01.Overview/docs.md
- 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/01.Customization/docs.md
- 04.System-updates-Debian-family/04.Provision-a-new-device/docs.md
https://tracker.mender.io/browse/MEN-4022
Thank you!
> passive checker: 04.System-updates-Debian-family

- .gitlab-ci.yml
> CI: Typo in MENDER_CLIENT_VERSION pipe

- 02.Overview/08.Inventory/docs.md
> Brief mention on reserved inventory status attribute in the identity scope

- 07.Server-installation/02.Demo-installation/docs.md
- 07.Server-installation/03.Production-installation/docs.md
> Mention Docker Hub limits recently introduced.

- 02.Overview/11.Security/docs.md
> MEN-4038 Hardware security subsection in Overview/Security.

- 01.Get-started/01.Preparation/docs.md
> Adjust Preparation text to mention non-RPI device types (MEN-3999)

- 01.Get-started/chapter.md
> Remove outdated text about arrow navigation

- 202.Release-information/01.Release-notes-changelog/docs.md
That is:
* Mender-client 2.4.1
* Mender-client 2.3.1
* Mender-convert 2.2.1
> Changelog and change-statistics for the new releases

- 01.Get-started/04.Deploy-a-container-update/docs.md
- 03.Client-installation/02.Install-with-Debian-package/docs.md
- 03.Client-installation/03.Identity/docs.md
- 03.Client-installation/04.Inventory/docs.md
- 05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
- 06.Artifact-creation/01.Create-an-Artifact/docs.md
- 06.Artifact-creation/07.Sign-and-verify/docs.md
- 06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
- 08.Server-integration/02.Preauthorizing-devices/docs.md
- 09.Downloads/docs.md
- 201.Troubleshoot/01.Yocto-project-build/docs.md
- autoversion.py
```
./autoversion.py --update --mender-client-version 2.4.1 --meta-mender-version dunfell --poky-version dunfell
```
> Upd hosted

- 201.Troubleshoot/03.Mender-Client/docs.md
> Command to follow Mender client and what it is doing, MEN-3757.

- 01.Get-started/02.Deploy-an-application-update/docs.md
> Add missing step when creating app deployment.

- 02.Overview/02.Artifact/docs.md
> fixed passive voice usage in artifact description to allow build to pass

- 202.Release-information/01.Release-notes-changelog/docs.md
> Monthly Meta-Mender release for November

- 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> Small typo fix.

- 202.Release-information/01.Release-notes-changelog/docs.md
> Update changelog and statistics for dunfell-v2020.12 tag.

- 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
I put it together based on advice I gathered from client team members and existing docs. please take a good look as I'm far from an expert.
depends on https://github.com/mendersoftware/mender-docs/pull/1242 (for a link to mender-shell config options).
https://tracker.mender.io/browse/MEN-4098
---
Thank you!
> 05.System-updates-Yocto-Project/05.Customize-Mender/: mender-shell

- 02.Overview/01.Introduction/docs.md
- 03.Add-ons/01.Remote-Terminal/10.Overview/docs.md
- 03.Add-ons/01.Remote-Terminal/30.Mender-shell-configuration-file/50.Mender-shell-configuration-options/docs.md
- 03.Add-ons/01.Remote-Terminal/40.Security/docs.md
- 09.Downloads/docs.md
> The term Remote Terminal to be used everywhere, typos and fixes.

- 202.Release-information/01.Release-notes-changelog/docs.md
> [2.5.x] Release notes for meta-mender zeus-v2020.12 and warrior-v2020.12

- 09.Add-ons/01.Remote-Terminal/30.Mender-shell-configuration-file/50.Mender-shell-configuration-options/docs.md
> MEN-4229 Remote Terminal addon: reconnect interval option.

- autoversion.py
> hosted: [autoversion] Fetch docker versions from release_tool

- 01.Get-started/03.Deploy-a-system-update/docs.md
- 07.Server-installation/05.Bandwidth/docs.md
> Contributed grammar fixes

- 202.Release-information/01.Release-notes-changelog/docs.md
> Add changelogs for mender-binary-delta 1.1.1 and 1.2.0.

- 202.Release-information/01.Release-notes-changelog/docs.md
(cherry picked from commit bdfedb73bcb4d811c9b1995cdc1f0d37c8197e4e)
> 2.5.x: Add changelogs for mender-binary-delta 1.1.1 and 1.2.0.

- 202.Release-information/01.Release-notes-changelog/docs.md
(cherry picked from commit bdfedb73bcb4d811c9b1995cdc1f0d37c8197e4e)
> 2.4.x: Add changelogs for mender-binary-delta 1.1.1 and 1.2.0.

- 09.Add-ons/01.Remote-Terminal/20.Installation/docs.md
> direct links to install Remote Terminal

- 07.Server-installation/03.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
- 07.Server-installation/03.Production-installation/docs.md
Following recent changes in `demo` and production `run` scripts.
> tests: update number of expected containers

- 07.Server-installation/03.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
- 07.Server-installation/03.Production-installation/docs.md
> 2.6.x: tests: update number of expected containers

- 07.Server-installation/03.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
- 07.Server-installation/03.Production-installation/docs.md
> 2.6.x: tests: Update (again) the expected containers for Enterprise setup

- 202.Release-information/02.Open-source-licenses/docs.md
> Update licenses for Mender 2.4.2.

- 202.Release-information/02.Open-source-licenses/docs.md
> Update licenses for Mender 2.5.1.

- 02.Overview/14.Compatibility/docs.md
- 202.Release-information/01.Release-notes-changelog/docs.md
- 202.Release-information/02.Open-source-licenses/docs.md
Cherry-picking relevant parts of #1313
> master: release Mender 2.6.0 + mender-convert 2.3.0

- 07.Server-installation/03.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
- 07.Server-installation/03.Production-installation/docs.md
follow-up task for fixing the docs - https://tracker.mender.io/browse/MEN-4400
> fix production installation script

- 202.Release-information/01.Release-notes-changelog/docs.md
> Add changelogs and statistics for meta-mender/dunfell-v2021.01.

- 202.Release-information/01.Release-notes-changelog/docs.md
> Add changelogs and statistics for mender-convert 2.2.2.

- 03.Client-installation/04.Inventory/docs.md
> Make shell script POSIX compatible

- 202.Release-information/01.Release-notes-changelog/docs.md
> 2.6.x: Add changelogs and statistics for zeus-v2021.02 and warrior-v2021.02

- 202.Release-information/01.Release-notes-changelog/docs.md
> 2.5.x: Add changelogs and statistics for zeus-v2021.02 and warrior-v2021.02

- 202.Release-information/01.Release-notes-changelog/docs.md
> 2.4.x: Add changelogs and statistics for zeus-v2021.02 and warrior-v2021.02

- 02.Overview/14.Compatibility/docs.md
- 201.Troubleshoot/02.Yocto-Project-runtime/docs.md
Signed-off-by: Jake Withecombe <jake@ruggednetworks.co.uk>
Thank you!
> Add more detail about updating old mender versions

- 09.Add-ons/02.Configure/01.Device-integration/docs.md
> MEN-4440: Document how to make an apply-device-config script

- 202.Release-information/01.Release-notes-changelog/docs.md
> Changelogs and statistics for meta-mender/dunfell-v2021.03.

- 201.Troubleshoot/01.Yocto-project-build/docs.md
- 201.Troubleshoot/02.Yocto-Project-runtime/docs.md
Signed-off-by: Drew Moseley <drew@moseleynet.net>
Fix a few instances where the mender-> mender-client renaming didn't happen.
Thank you!
> migrate-configuration: Rename mender to mender-client.

- 04.System-updates-Debian-family/99.Variables/docs.md
And correct style of existing Mender Connect ones.
> [Debian family/Variables] Add Mender Configure add-on variables

- 09.Add-ons/01.Remote-Terminal/20.Installation/docs.md
- 09.Add-ons/01.Remote-Terminal/docs.md
- 09.Downloads/docs.md
Re-purposing existing Remote Terminal section as general "add-ons"
section.
> [Downloads] Add mender-configure section

- 01.Get-started/03.Deploy-a-system-update/docs.md
- 01.Get-started/04.Deploy-a-container-update/docs.md
- 02.Overview/02.Device-Support/docs.md
- 02.Overview/03.Artifact/docs.md
- 03.Client-installation/02.Install-with-Debian-package/docs.md
- 03.Client-installation/03.Identity/docs.md
- 03.Client-installation/04.Inventory/docs.md
- 05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
- 05.System-updates-Yocto-Project/04.Image-customization/03.State-scripts/docs.md
- 06.Artifact-creation/01.Create-an-Artifact/docs.md
- 06.Artifact-creation/07.Sign-and-verify/docs.md
- 06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
- 07.Server-installation/02.Demo-installation/docs.md
- 07.Server-installation/03.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
- 07.Server-installation/03.Production-installation/docs.md
- 07.Server-installation/07.Upgrading/docs.md
- 08.Server-integration/01.Using-the-apis/docs.md
- 08.Server-integration/02.Preauthorizing-devices/docs.md
- 08.Server-integration/03.Mutual-TLS-authentication/docs.md
- 09.Downloads/docs.md
- 200.API/chapter.md
- 201.Troubleshoot/01.Yocto-project-build/docs.md
- 201.Troubleshoot/04.Mender-Server/docs.md
- home/chapter.md
> Switch all version references to 2.7.0-build1 and dunfell.

- 01.Get-started/04.Deploy-a-container-update/docs.md
new containers, both from Mender Hub description and the code.
Thank you!
> The Docker Update Module seems to both stop existing and start

- 09.Add-ons/01.Remote-Terminal/40.Security/docs.md
- 09.Add-ons/01.Remote-Terminal/docs.md
changelog: title
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>
> MEN-4514: Include session logging in remote terminal documentation

- 07.Server-installation/03.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
- 07.Server-installation/03.Production-installation/docs.md
* sleep 3 --> sleep 4
* n<10 --> n<11
ChangeLog:none
> Increased sleeps and iterations for docs testing containers up waits.

- 202.Release-information/02.Open-source-licenses/docs.md
> Update license information for 2.7.0.

- 07.Server-installation/03.Production-installation/docs.md
> Enterprise containers count up to 16

- 202.Release-information/02.Open-source-licenses/docs.md
> Update the licenses for Mender 2.4.3

- 01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
- 09.Downloads/docs.md
> MEN-4395: Bump version to 2021-01-11

- 02.Overview/14.Compatibility/docs.md
- 202.Release-information/01.Release-notes-changelog/docs.md
> master: Mender 2.7.0 and mender-convert 2.4.0 releases

- 01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
- 02.Overview/14.Compatibility/docs.md
- 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/01.Customization/docs.md
- 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
- 09.Downloads/docs.md
- 202.Release-information/01.Release-notes-changelog/docs.md
Bring #1367 and update versions for `mender-convert`
> hosted: updates for mender-convert 2.4.0

- 01.Getting-started/01.Quickstart-with-raspberry-pi/docs.md
- 08.Downloads/docs.md
> Bump the RaspiOS version

- 09.Add-ons/00.Overview/docs.md
- 09.Add-ons/02.Configure/01.Device-integration/docs.md
- 09.Add-ons/02.Configure/docs.md
- 09.Add-ons/03.File-Transfer/docs.md
> Adjust headings for consistency

- 202.Release-information/01.Release-notes-changelog/docs.md
> Add changelog for mender-binary-delta 1.2.1.

- 202.Release-information/01.Release-notes-changelog/docs.md
> Add changelog and statistiscs for meta-mender/dunfell-v2021.04.

- 202.Release-information/01.Release-notes-changelog/docs.md
* 2.6.1 release logs and stats
* mender-binary-delta 1.1.2 logs
> 2.6.1 release changelogs n stats

- 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> MEN-4557: Documentation for Update Control configuration options

- 09.Add-ons/02.Configure/01.Device-integration/docs.md
> Fix: link to the mender-configure-update-module article

- 202.Release-information/01.Release-notes-changelog/docs.md
> 2.7.x: Add changelogs and statistics for zeus-v2021.04 and warrior-v2021.04

- 202.Release-information/01.Release-notes-changelog/docs.md
> 2.6.x: Add changelogs and statistics for zeus-v2021.04 and warrior-v2021.04

- 202.Release-information/01.Release-notes-changelog/docs.md
> 2.5.x: Add changelogs and statistics for zeus-v2021.04 and warrior-v2021.04

- 202.Release-information/01.Release-notes-changelog/docs.md
> 2.4.x: Add changelogs and statistics for zeus-v2021.04 and warrior-v2021.04

- 07.Server-installation/03.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
- 07.Server-installation/03.Production-installation/docs.md
> Docs exec testing: pass as soon as containers run.

- 07.Server-installation/06.Storage/docs.md
> MEN-3966: extend documentation on artifacts storage

- 07.Server-installation/03.Production-installation/docs.md
Signed-off-by: Drew Moseley <drew@moseleynet.net>
Thank you!
> Fix broken STORAGE_PROXY_DOMAIN_NAME

- 09.Add-ons/90.Reference/docs.md
> MEN-4505: Add the `ShellArguments` mender-connect config docs

- 07.Server-installation/03.Production-installation/docs.md
> 2.7.x: Fix broken STORAGE_PROXY_DOMAIN_NAME

- 09.Downloads/docs.md
> 2.7.x: MEN-4591: Downloads: Note that APT repository installs latest package

- 09.Downloads/docs.md
> 2.6.x: MEN-4591: Downloads: Note that APT repository installs latest package

- 02.Overview/14.Compatibility/docs.md
> MEN-4785: Update Device API compatibility table for v2.

- 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
> 2.7.x: Yocto Customize Mender: fixes in yocto snippets

- 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
> 2.6.x: Yocto Customize Mender: fixes in yocto snippets

- .gitlab-ci.yml
- 08.Server-integration/03.Mutual-TLS-authentication/docs.md
Small changes to the snippets that are used in the Mutual TLS
authentication.
Signed-off-by: Nils Olav Kvelvane Johansen <nils.olav@northern.tech>
Main work done by Nils. GitLab CI inclusion and minor fixes by Lluis.
> QA-251: Added AUTOMATION tests to Mutual TLS authentication snippets.

- .gitlab-ci.yml
- 08.Server-integration/03.Mutual-TLS-authentication/docs.md
> 2.7.x: QA-251: Added AUTOMATION tests to Mutual TLS authentication snippets.

- .gitlab-ci.yml
- 02.Overview/06.Delta-update/docs.md
- 02.Overview/12.Role.Based.Access.Control/docs.md
- 08.Server-integration/03.Mutual-TLS-authentication/docs.md
- 09.Add-ons/01.Remote-Terminal/40.Security/docs.md
- 09.Add-ons/01.Remote-Terminal/docs.md
> 2.6.x: QA-251: Added AUTOMATION tests to Mutual TLS authentication snippets.

- 09.Add-ons/03.File-Transfer/40.Security/docs.md
- 09.Add-ons/03.File-Transfer/docs.md
- 09.Add-ons/90.Reference/docs.md
> MEN-4881 File Transfer limits docs update

- 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> Helm chart installation: remove resources settings, use defaults

- 07.Server-installation/chapter.md
> Update "latest" references to 3.0 documentation.

- 200.Server-side-API/chapter.md
Mistake introduced doing conflict resolution at 2950b7f.
> hosted: Fix Server-side API chapter redirect

- 07.Server-installation/03.Installation-with-docker-compose/02.Upgrading-from-OS-to-Enterprise/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/docs.md
- this is needed after the introduction of redis to the enterprise stack
> aligned container count

- 02.Overview/01.Introduction/docs.md
- 09.Add-ons/00.Overview/docs.md
- 09.Add-ons/50.Monitoring/30.Configuration/docs.md
- 09.Add-ons/50.Monitoring/docs.md
- 09.Add-ons/chapter.md
> MEN-4818 Monitoring add-on: initial docs

- 07.Server-installation/03.Installation-with-docker-compose/02.Upgrading-from-OS-to-Enterprise/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/docs.md
This reverts commit 213671ff3af059ce46a1272460ff1b55b391debf.
> Revert "tests: Bump container count for devicemonitor"

- 02.Overview/14.Compatibility/docs.md
- 05.System-updates-Yocto-Project/01.Overview/docs.md
Small improvement suggestions which make the compatibility page more unambiguous.
> Clarify compatibility explanations

- 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> Add `global.auditlogs` to Helm chart installation instructions

- 09.Add-ons/50.Monitoring/docs.md
MEN-4840 Log Monitoring: update on regular expression logic.
ChangeLog:title
> MEN-4840 Log Monitoring: update on regular expression logic.

- 01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
> Make it clear Raspberry Pi OS image no longer contains Mender.

- 07.Server-installation/04.Production-installation-with-kubernetes/docs.md
> Add S3-compatible projects to the list of supported storage layers

- 302.Release-information/02.Open-source-licenses/docs.md
> MEN-4987: Add U-Boot and Grub licenses to license page

- 03.Client-installation/07.Configuration-file/50.Configuration-options/docs.md
> Document new boot utilities options in the client.

- 03.Client-installation/07.Configuration-file/50.Configuration-options/docs.md
> Fix a version mis-reference.

- 05.System-updates-Yocto-Project/06.Build-for-production/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/docs.md
- 07.Server-installation/05.Certificates-and-keys/docs.md
- 301.Troubleshoot/04.Mender-Server/docs.md
See mendersoftware/integration#1253
> [MEN-4986] Update certificate docs to reference unified certificate

- 05.System-updates-Yocto-Project/05.Customize-Mender/01.Delta-update-support/docs.md
- 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
- 09.Downloads/docs.md
> Replace download.mender.io with downloads.customer.mender.io

- 09.Add-ons/20.Monitor/30.Advanced-configuration/docs.md
> Document the DEFAULT_ALERT_STORE_RESEND_INTERVAL_S variable

- 07.Server-installation/03.Installation-with-docker-compose/02.Upgrading-from-OS-to-Enterprise/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/docs.md
https://tracker.mender.io/browse/MEN-5093
Thank you!
> MEN-5093: add auditlogs to default enterprise setups

- 09.Downloads/docs.md
> Make sure mender-monitor installs dependencies too.

- 09.Downloads/docs.md
(cherry picked from commit 745fb28ccc7ae80aa5cbdcbd48aaf1f010b6b43d)
> 3.1.x: Make sure mender-monitor installs dependencies too.

- .checklinks-whitelist
- 02.Overview/14.Compatibility/docs.md
- 302.Release-information/01.Release-notes-changelog/docs.md
- 302.Release-information/02.Open-source-licenses/docs.md
Bring the relevant parts from #1555
> master: Release Mender 3.1.0

- 202.Release-information/02.Open-source-licenses/docs.md
> 2.6.3 Open source licenses

- 01.Get-started/03.Deploy-a-system-update/docs.md
- 01.Get-started/04.Deploy-a-container-update/docs.md
- 02.Overview/02.Device-Support/docs.md
- 02.Overview/03.Artifact/docs.md
- 03.Client-installation/02.Install-with-Debian-package/docs.md
- 03.Client-installation/03.Identity/docs.md
- 03.Client-installation/04.Inventory/docs.md
- 05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
- 06.Artifact-creation/01.Create-an-Artifact/docs.md
- 06.Artifact-creation/07.Sign-and-verify/docs.md
- 06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
- 07.Server-installation/02.Demo-installation/docs.md
- 07.Server-installation/03.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
- 07.Server-installation/03.Production-installation/docs.md
- 07.Server-installation/07.Upgrading/docs.md
- 08.Server-integration/02.Preauthorizing-devices/docs.md
- 08.Server-integration/03.Mutual-TLS-authentication/docs.md
- 09.Downloads/docs.md
- 201.Troubleshoot/01.Yocto-project-build/docs.md
- 201.Troubleshoot/04.Mender-Server/docs.md
> 2.6.3 Mender release version bumps

- 01.Get-started/03.Deploy-a-system-update/docs.md
- 01.Get-started/04.Deploy-a-container-update/docs.md
- 02.Overview/02.Device-Support/docs.md
- 02.Overview/03.Artifact/docs.md
- 03.Client-installation/02.Install-with-Debian-package/docs.md
- 03.Client-installation/03.Identity/docs.md
- 03.Client-installation/04.Inventory/docs.md
- 05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
- 06.Artifact-creation/01.Create-an-Artifact/docs.md
- 06.Artifact-creation/07.Sign-and-verify/docs.md
- 06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
- 07.Server-installation/02.Demo-installation/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/01.Upgrading/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/02.Upgrading-from-OS-to-Enterprise/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
- 08.Server-integration/02.Preauthorizing-devices/docs.md
- 08.Server-integration/03.Mutual-TLS-authentication/docs.md
- 09.Downloads/docs.md
- 301.Troubleshoot/01.Yocto-project-build/docs.md
> 3.0.1 Mender release version updates

- 202.Release-information/01.Release-notes-changelog/docs.md
> 2.6.3 release changelogs and statistics

- 09.Add-ons/10.Configure/docs.md
> Document that Configure and signed Artifacts don't work together.

- 07.Server-installation/03.Installation-with-docker-compose/02.Upgrading-from-OS-to-Enterprise/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/docs.md
> MEN-5149 Production installation tests: updating containers count.

- 07.Server-installation/03.Installation-with-docker-compose/02.Upgrading-from-OS-to-Enterprise/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/docs.md
This test failed in master but not in the pull request, which makes me question the stability of these "AUTOMATION" tests.
> FIX: Update container count function in install w/compose docs

- 01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
FuP to https://github.com/mendersoftware/mender-docs/pull/1571
> Add Mac OS path for SD card

- 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
- 09.Add-ons/90.Mender-Connect/docs.md
> Mender Connect configuration: remove deprecated fields

- 06.Artifact-creation/06.Standalone-deployment/docs.md
I believe we also need to disable the mender client, so it doesn't auto restart on the next boot? Or maybe I'm missing something, in such case maybe we should improve the documentation.
> Also mask/disable mender client

- 06.Artifact-creation/06.Standalone-deployment/docs.md
Porting https://github.com/mendersoftware/mender-docs/pull/1577 to master.
> master: Also mask/disable mender client

- 03.Client-installation/01.Overview/docs.md
> Client installation / overview: Missing space

- 05.System-updates-Yocto-Project/04.Image-customization/01.Features/docs.md
> Fix: mender-install → mender-client-install

- 05.System-updates-Yocto-Project/04.Image-customization/01.Features/docs.md
> master: Fix: mender-install → mender-client-install

- 09.Downloads/docs.md
Be explicit on updates without rollback.
Signed-off-by: Alan Martinovic <alan.martinovic@northern.tech>
> Add section about apt-get update

- 05.System-updates-Yocto-Project/06.Build-for-production/docs.md
Improve the wording of this notice for both grammar and clarity.
Signed-off-by: Trevor Woerner <twoerner@gmail.com>
Thank you!
> improve wording

- 05.System-updates-Yocto-Project/04.Image-customization/01.Features/docs.md
- 05.System-updates-Yocto-Project/04.Image-customization/docs.md
- 05.System-updates-Yocto-Project/06.Build-for-production/docs.md
- 06.Artifact-creation/02.Create-an-Artifact-with-system-snapshot/docs.md
Porting @twoerner contributions to master, namely: #1597, #1596, #1599, #1600 and #1601.
I am following-up with #1598 independently :+1:
> master: Misc fixes 

- 06.Artifact-creation/07.Sign-and-verify/docs.md
> Add a small section about Google Cloud Key Management and signing.

- 05.System-updates-Yocto-Project/20.Provisioning-a-new-device/docs.md
Based on a commit by: Simon A. Eugster <simon.eu@gmail.com>
(https://github.com/mendersoftware/mender-docs/pull/1605)
> Improve information about image types and flashing.

- 09.Add-ons/20.Monitor/30.Advanced-configuration/docs.md
Signed-off-by: Bas Metman <bas@hiber.global>
> Fix MONITOR_D_DIRECTORY typo

- 09.Add-ons/20.Monitor/30.Advanced-configuration/docs.md
> master: Fix MONITOR_D_DIRECTORY typo

- 01.Get-started/03.Deploy-a-system-update/docs.md
- 01.Get-started/04.Deploy-a-container-update/docs.md
- 02.Overview/02.Device-Support/docs.md
- 02.Overview/03.Artifact/docs.md
- 03.Client-installation/02.Install-with-Debian-package/docs.md
- 03.Client-installation/03.Identity/docs.md
- 03.Client-installation/04.Inventory/docs.md
- 05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
- 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
- 06.Artifact-creation/01.Create-an-Artifact/docs.md
- 06.Artifact-creation/07.Sign-and-verify/docs.md
- 06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
- 07.Server-installation/02.Demo-installation/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/01.Upgrading/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/02.Upgrading-from-OS-to-Enterprise/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
- 08.Server-integration/02.Preauthorizing-devices/docs.md
- 08.Server-integration/03.Mutual-TLS-authentication/docs.md
- 09.Downloads/docs.md
- 301.Troubleshoot/01.Yocto-project-build/docs.md
> 3.2.0-build5 bumps

- 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
- 05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
- 06.Artifact-creation/01.Create-an-Artifact/docs.md
- 08.Server-integration/03.Mutual-TLS-authentication/docs.md
- README-autoversion.markdown
- README.markdown
- autoversion.py
Reverts #1615 and fixes the problem in a simpler way.
> autoversion.py: Switch to git versions

- 01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
- 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/01.Customization/docs.md
- 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
- 09.Downloads/docs.md
Note: These images do not actually exist yet.
> bump mender-convert and raspios image

- 09.Add-ons/20.Monitor/20.Monitoring-subsystems/docs.md
> Monitor add-on: fixing the stderr log checks description

- 09.Add-ons/20.Monitor/20.Monitoring-subsystems/docs.md
> Fix: small typo in 20.Monitoring-subsystems/docs.md

- 01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
> fix the raspios link

- 01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
- 01.Get-started/03.Deploy-a-system-update/docs.md
- 01.Get-started/04.Deploy-a-container-update/docs.md
- 02.Overview/02.Device-Support/docs.md
- 02.Overview/03.Artifact/docs.md
- 03.Client-installation/02.Install-with-Debian-package/docs.md
- 03.Client-installation/03.Identity/docs.md
- 03.Client-installation/04.Inventory/docs.md
- 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/01.Customization/docs.md
- 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
- 05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
- 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
- 06.Artifact-creation/01.Create-an-Artifact/docs.md
- 06.Artifact-creation/07.Sign-and-verify/docs.md
- 06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
- 08.Server-integration/02.Preauthorizing-devices/docs.md
- 08.Server-integration/03.Mutual-TLS-authentication/docs.md
- 09.Downloads/docs.md
- 301.Troubleshoot/01.Yocto-project-build/docs.md
- autoversion.py
Also a small update to autoversion
> release 3.2.0: version update on the hosted branch

- 01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
> update the raspbian images

- 07.Server-installation/01.Overview/docs.md
- 07.Server-installation/02.Demo-installation/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/01.Upgrading/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/02.Upgrading-from-OS-to-Enterprise/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/03.Backup-and-restore/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/01.Kubernetes/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/02.MongoDB/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/03.NATS/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/04.Minio/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/docs.md
- 07.Server-installation/05.Certificates-and-keys/docs.md
- 07.Server-installation/06.Storage-of-the-artifacts/docs.md
- 07.Server-installation/chapter.md
- 301.Troubleshoot/04.Mender-Server/docs.md
> release 3.2.0: Update the docs latest version

- 08.Server-integration/03.Mutual-TLS-authentication/docs.md
> Add the ignore tag as a workaround for the mtls-ambassador version

- 01.Get-started/05.Monitor/docs.md
> add a note that the pi user on pi requires sudo for mender-monitor

- 301.Troubleshoot/03.Mender-Client/docs.md
> Add a note on the installation problems for the client debian package

- 02.Overview/14.Compatibility/docs.md
> [3.2.1 release]: Add 3.2.1 compatibility to the tables

- 09.Downloads/docs.md
Following packages names updates from MEN-5410.
> Downloads: mender-client: Update URLs for direct downloads

- 06.Artifact-creation/01.Create-an-Artifact/docs.md
- 09.Downloads/docs.md
- 301.Troubleshoot/03.Mender-Client/docs.md
Merging master in to bring #1651
> hosted: downloads client package links

- 09.Downloads/docs.md
Merging master in to bring https://github.com/mendersoftware/mender-docs/pull/1654
> hosted: Downloads: Fix autoversion expressions for Mender client packages

- 09.Downloads/docs.md
Cherry-picking https://github.com/mendersoftware/mender-docs/pull/1654
> 3.2.x: Downloads: Fix autoversion expressions for Mender client packages

- 301.Troubleshoot/03.Mender-Client/docs.md
> Update the Debian package installation warning

- 03.Client-installation/07.Configuration-file/50.Configuration-options/docs.md
goes with:
* https://github.com/mendersoftware/mender/pull/879
* https://github.com/mendersoftware/integration/pull/1921
> DisableKeepAlive and IdleConnTimeoutSeconds configuration options

- 03.Client-installation/02.Install-with-Debian-package/docs.md
- 09.Downloads/docs.md
> 3.1.x: Correct the deb packages filenames in the install commands

- 03.Client-installation/02.Install-with-Debian-package/docs.md
> 2.6.x: Correct the deb packages filenames in the install commands

- 03.Client-installation/02.Install-with-Debian-package/docs.md
- 09.Downloads/docs.md
Namely #1669, #1676, #1677, #1683 and #1685.
> hosted: Misc cherry-picks

- 03.Client-installation/02.Install-with-Debian-package/docs.md
- 09.Downloads/docs.md
Cherry-pick of #1676, #1677, #1683 and #1685.
> 3.2.x: Correct the deb packages filenames in the install commands

- 09.Downloads/docs.md
> 3.1.x: Switch from curl to wget for commercial packages download

- 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> Fix an incorrect url

- 06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
> Clarify command vs. file contents

- 09.Downloads/docs.md
> 3.2.x: Downloads: fix typo in Enterprise downloads shell snippets

- 09.Downloads/docs.md
> 3.1.x: Downloads: fix typo in Enterprise downloads shell snippets

- 03.Client-installation/07.Configuration-file/50.Configuration-options/docs.md
> RetryPollCount description

- 08.Server-integration/05.Azure-IoT-Hub/docs.md
Issue: https://tracker.mender.io/browse/MEN-5392
> azure-iot: update info about permissions to the Device Twin

- 01.Get-started/03.Deploy-a-system-update/docs.md
- 01.Get-started/04.Deploy-a-container-update/docs.md
(cherry picked from commit 4bdf7945b6363310e447c4c3388ed1e62d1d1a55)
> chore: onboarding fixes from latest onboarding test run

- 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/01.Customization/docs.md
- 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
This is a companion PR to https://github.com/mendersoftware/mender-convert/pull/433
> Update dockumentation to make docker container independent from mender-convert repository

- 09.Downloads/docs.md
- 301.Troubleshoot/03.Mender-Client/docs.md
> MEN-5461 Notes on removing the stable APT repository.

- 06.Artifact-creation/05.Create-a-Delta-update-Artifact/docs.md
- 301.Troubleshoot/03.Mender-Client/docs.md
Revamp of the delta docs:
* reduce verbosity
* expand with parameter passing to xdelta
* define limits of support for those cases
* add a troubleshoot section which explains the checksum mechanics
Signed-off-by: Alan Martinovic <alan.martinovic@northern.tech>
Thank you!
> Revamp of the delta docs

- 08.Server-integration/03.Mutual-TLS-authentication/docs.md
- 09.Downloads/docs.md
> Docs tests: fix typo in AUTOMATION checks

- 01.Get-started/03.Deploy-a-system-update/docs.md
- 06.Artifact-creation/02.Create-an-Artifact-with-system-snapshot/docs.md
> MEN-5219: Update warnings about `apt upgrade`.

- 02.Overview/11.Security/docs.md
> feat: add section about rate limits in overview/security

- 301.Troubleshoot/03.Mender-Client/docs.md
> Troubleshooting: extra information on repo name change.

- 01.Get-started/06.Mender-Gateway/docs.md
- 08.Server-integration/04.Mender-Gateway/99.Configuration-file/docs.md
- 08.Server-integration/04.Mender-Gateway/docs.md
> feat: document the artifacts cache configuration settings

- 01.Get-started/03.Deploy-a-system-update/docs.md
- 01.Get-started/04.Deploy-a-container-update/docs.md
- 02.Overview/03.Artifact/docs.md
- 05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
- 07.Server-installation/02.Demo-installation/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/01.Upgrading/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/02.Upgrading-from-OS-to-Enterprise/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
- 08.Server-integration/03.Mutual-TLS-authentication/docs.md
- 09.Downloads/docs.md
> Update version references for Mender 3.2.2.

- 01.Get-started/03.Deploy-a-system-update/docs.md
- 01.Get-started/04.Deploy-a-container-update/docs.md
- 02.Overview/03.Artifact/docs.md
- 05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
- 09.Downloads/docs.md
> Update version references for staging.

- 08.Server-integration/04.Mender-Gateway/99.Configuration-file/docs.md
> fix: update the artifacts cache in the Mender Gateway configuration file

- 01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
- 01.Get-started/03.Deploy-a-system-update/docs.md
- 01.Get-started/04.Deploy-a-container-update/docs.md
- 02.Overview/02.Device-Support/docs.md
- 02.Overview/03.Artifact/docs.md
- 03.Client-installation/02.Install-with-Debian-package/docs.md
- 03.Client-installation/03.Identity/docs.md
- 03.Client-installation/04.Inventory/docs.md
- 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/01.Customization/docs.md
- 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
- 05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
- 05.System-updates-Yocto-Project/04.Image-customization/03.State-scripts/docs.md
- 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
- 06.Artifact-creation/01.Create-an-Artifact/docs.md
- 06.Artifact-creation/02.Create-an-Artifact-with-system-snapshot/docs.md
- 06.Artifact-creation/07.Sign-and-verify/docs.md
- 06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
- 07.Server-installation/02.Demo-installation/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/01.Upgrading/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/02.Upgrading-from-OS-to-Enterprise/docs.md
- 07.Server-installation/03.Installation-with-docker-compose/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
- 08.Server-integration/01.Using-the-apis/docs.md
- 08.Server-integration/02.Preauthorizing-devices/docs.md
- 08.Server-integration/03.Mutual-TLS-authentication/docs.md
- 09.Downloads/docs.md
- 200.Server-side-API/chapter.md
- 301.Troubleshoot/01.Yocto-project-build/docs.md
- home/chapter.md
> chore(3.3-release-version): update the component versions

- 09.Downloads/docs.md
> fix(downloads): Bionic and Focal were switched in the downloads tab

- 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> fix: binary name for useradm-enterprise when creating additional users

- 07.Server-installation/04.Production-installation-with-kubernetes/docs.md
> feat: add system requirements to the Kubernetes production installation

- 01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
- 09.Downloads/docs.md
> chore: bump the version of the converted raspios images we provide

- .gitlab-ci.yml
> Cherry hosted update dind

- .gitlab-ci.yml
> ci: bump dind to latest

- 03.Client-installation/02.Install-with-Debian-package/docs.md
- 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
> Fix incorrectly annotated message box.

- .gitlab-ci.yml
- 03.Client-installation/02.Install-with-Debian-package/docs.md
- 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
(cherry picked from commit 3e89a19e9880606a0a1e74009f95ee4d880e7a47)
> Fix incorrectly annotated message boxes.

- 07.Server-installation/04.Production-installation-with-kubernetes/02.MongoDB/docs.md
> Cherry-pick #1765 to 3.3.x

- 05.System-updates-Yocto-Project/05.Customize-Mender/01.Delta-update-support/docs.md
- autoversion.py
```
commit 2b913ddc33170bb16f5b2cb7b98d0483d18d7ad3
Author: Kristian Amlie <kristian.amlie@northern.tech>
Date:   Fri Jul 15 11:40:02 2022
Add kirkstone instructions for mender-binary-delta.
Also update to the latest mender-binary-delta version.
commit 25e1e4966a88ef9dfa634253ac5baa3e4d238152
Author: Kristian Amlie <kristian.amlie@northern.tech>
Date:   Fri Jul 15 11:37:24 2022
Add latest Yocto branches to autoversion.py.
```
> Add kirkstone instructions for mender-binary-delta.

- 02.Overview/11.Security/docs.md
> feat: 2FA is now available in all plans

- 05.System-updates-Yocto-Project/04.Image-customization/02.Read-only-root-filesystem/docs.md
- 05.System-updates-Yocto-Project/06.Build-for-production/docs.md
- 05.System-updates-Yocto-Project/99.Variables/docs.md
- 301.Troubleshoot/01.Yocto-project-build/docs.md
> fix: external links

- 05.System-updates-Yocto-Project/05.Customize-Mender/01.Delta-update-support/docs.md
This (partially) reverts commit 2b913dd.
> hosted: chore: Revert "Add kirkstone instructions for mender-binary-delta."

- 301.Troubleshoot/01.Yocto-project-build/docs.md
> fix: deadlink to the Yocto documentation

- 01.Get-started/01.Preparation/docs.md
Ticket: None
Signed-off-by: Jonathan French [tojonhb@gmail.com](mailto:tojonhb@gmail.com)
> Improve grammar in Preparation > Next Step

- 03.Client-installation/07.Configuration-file/50.Configuration-options/docs.md
Ticket: MEN-5544
Signed-off-by: Kamil Woźniak <kamil.wozniak@digitalnewagency.com>
This is documentation of `UpdateControlMapPollIntervalSeconds` config parameter added here: https://github.com/mendersoftware/mender/pull/989.
> feat: add UpdateControlMapPollIntervalSeconds config description

- 05.System-updates-Yocto-Project/06.Build-for-production/docs.md
- package-lock.json
- package.json
Original work by Anton Kraft, see: https://github.com/mendersoftware/mender-docs/pull/1812
> chore(package.json): Upgrade to latest github-slugger + fix(Build-for-production): Fix link

- 01.Get-started/02.Deploy-an-application-update/docs.md
Change name of field in field description of 'Artifact Mandatory Fields'
to match illustration picture. `s/Artifact name/Release name`
> Change field description of Artifact Mandatory Fields

- 06.Artifact-creation/07.Sign-and-verify/docs.md
chore(pkcs#11): Add PKCS#11 documentation
Ticket: MEN-5760
```
```
Thank you!
> chore(pkcs#11): Add PKCS#11 documentation

- 05.System-updates-Yocto-Project/05.Customize-Mender/01.Delta-update-support/docs.md
- 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
> Switch to new commercial license setup for Yocto.

- 01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
- 01.Get-started/03.Deploy-a-system-update/docs.md
- 06.Artifact-creation/01.Create-an-Artifact/docs.md
- 09.Add-ons/90.Mender-Connect/docs.md
> fix: remove references to `pi` user.

- 05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
- 05.System-updates-Yocto-Project/06.Build-for-production/docs.md
Submit #1273 to master and:
chore: Update commented out snippets for self-signed certificates
Ticket: MEN-4273
> Resubmit mender server certificate

- 301.Troubleshoot/03.Mender-Client/docs.md
> chore: Document workaround for Raspberry Pi 3 dunfel to kirkstone update

- 02.Overview/12.Role.Based.Access.Control/docs.md
chore(RBAC): Document Configure permission
Ticket: MEN-5828
```
```
Thank you!
> chore(RBAC): Document Configure permission

- 301.Troubleshoot/02.Yocto-Project-runtime/docs.md
> fix: broken link to the Yocto docs

- 02.Overview/14.Compatibility/docs.md
- 05.System-updates-Yocto-Project/02.Board-integration/01.Partition-configuration/docs.md
- 05.System-updates-Yocto-Project/02.Board-integration/02.Bootloader-support/01.GRUB/docs.md
- 05.System-updates-Yocto-Project/02.Board-integration/02.Bootloader-support/02.U-Boot/docs.md
- 05.System-updates-Yocto-Project/02.Board-integration/03.Raw-flash/docs.md
- 05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
- 05.System-updates-Yocto-Project/04.Image-customization/01.Features/docs.md
- 05.System-updates-Yocto-Project/04.Image-customization/03.State-scripts/docs.md
- 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
- 05.System-updates-Yocto-Project/06.Build-for-production/docs.md
- 05.System-updates-Yocto-Project/99.Variables/docs.md
- 301.Troubleshoot/01.Yocto-project-build/docs.md
- 301.Troubleshoot/02.Yocto-Project-runtime/docs.md
Most of these are the same as master, only the last one is new.
> 3.4.x kirkstone changes

- 01.Get-started/05.Monitor/docs.md
> fix(typo): Remove typo preventing codeblocks from rendering correctly

- 01.Get-started/05.Monitor/docs.md
Ticket: MEN-5766
(cherry picked from commit 11c3cac6306c6fd933d1bbc1f8ed937096c223ec)
See #1844
> Cherry-pick MEN-5766 to 3.3.x

- 05.System-updates-Yocto-Project/06.Build-for-production/docs.md
Cherry picked from commit 868a4127bdea936a6fc30d021a5dd6041ed696d9
> 3.2.x: fix(Build-for-production): Fix link

- 02.Overview/14.Compatibility/docs.md
Cherry pick of PR: https://github.com/mendersoftware/mender-docs/pull/1867 for me
> [Cherry 3.2.x]: fix(compatibility): Correct version relations for Mender 3.2 and 3.3

- 05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
- 05.System-updates-Yocto-Project/04.Image-customization/03.State-scripts/docs.md
- 05.System-updates-Yocto-Project/05.Customize-Mender/01.Delta-update-support/docs.md
Don't merge right away, but merge as part of [MEN-5864](https://tracker.mender.io/browse/MEN-5864).
> Hosted update for kirkstone

- 302.Release-information/01.Release-schedule/docs.md
Amends commit 461c9e31, see discussion in [PR](https://github.com/mendersoftware/mender-docs/pull/1864#discussion_r979993107).
> chore: Restore table in Current LTS releases

- 01.Get-started/05.Monitor/docs.md
Ticket: MEN-5766
(cherry picked from commit 11c3cac6306c6fd933d1bbc1f8ed937096c223ec)
See #1844
> Cherry-pick MEN-5766 to 3.2.x

- 06.Artifact-creation/05.Create-a-Delta-update-Artifact/docs.md
Signed-off-by: Alan <alan.martinovic@northern.tech>
> fix: Document delta dependency

- 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
Ticket: None
```
```
Thank you!
> fix: typo "prerequesites" -> "prerequisites"

- .checklinks-whitelist
Ticket: None
Signed-off-by: Josef Holzmayr <jester@theyoctojester.info>
> fix: typo in .checklinks-whitelist

- 01.Get-started/07.Server-requirements/docs.md
Signed-off-by: Roberto Giovanardi <roberto.giovanardi@northern.tech>
```
fix: Adedd required firewall URLs
Changelog: Added required firewall URLs
Ticket: None
```
Added required firewall URLs
> Added required firewall URLs

- 01.Get-started/07.Server-requirements/docs.md
```
fix: Server requirements documentation
Changelog: Added Server requirements
Ticket: None
```
Added Server requirements:
* URLs allowlist
* S3 IAM policy
> Server requirements documentation

- 302.Release-information/03.Open-source-licenses/docs.md
> Update licenses for 3.3.1.

- 02.Overview/10.Customize-the-update-process/docs.md
TIcket: None
Signed-off-by: Josef Holzmayr <jester@theyoctojester.info>
```
```
Thank you!
> fix: add Enterprise plan note to synchronized update section

- 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
Signed-off-by: Luis Ramirez Vargas <luis.ramirez@northern.tech>
```
```
Thank you!
> docs: correct mender-convert setup hosted mender

- 09.Downloads/docs.md
```
fix: gpg date refresh
Updated Download doc with the new key lifetime
Changelog: Updated Download doc with the new key lifetime
Ticket: MEN-5937
```
Updated Download doc with the new key lifetime
Thank you!
> gpg date refresh

- .checklinks-whitelist
- 01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
- 02.Overview/10.Customize-the-update-process/docs.md
- 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
- 06.Artifact-creation/02.Create-an-Artifact-with-system-snapshot/docs.md
- 06.Artifact-creation/05.Create-a-Delta-update-Artifact/docs.md
- 09.Downloads/docs.md
- 201.Device-side-API/00.Overview/docs.md
- package-lock.json
- package.json
Updating from commit 126bf647: latest `master` as per today except #1888.
> hosted: update from master

- 02.Overview/16.Requirements/docs.md
Signed-off-by: Roberto Giovanardi <roberto.giovanardi@northern.tech>
```
fix: added general requirements page
Changelog: Added general requirements page
Ticket: ME-7
```
Added general requirements page with AWS S3 policy and with URL allowlist
Thank you!
> chore: added general requirements for 3.4

- 02.Overview/16.Requirements/docs.md
```
fix: copy-pastable solution for Artifact storage access URLs
Ticket: ME-7
```
Set copy-pastable solution for Artifact storage access URLs
> Requirements copy pastable solution

- 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
chore(storage): Add information about all storage types and Azure Blob Storage
Ticket: MEN-5962
```
```
Thank you!
> chore(storage): Add information about all storage types and Azure Blob Storage

- 01.Get-started/03.Deploy-a-system-update/docs.md
- 06.Artifact-creation/10.CI-CD/01.GitHub Actions/docs.md
- 06.Artifact-creation/10.CI-CD/02.GitLab/docs.md
- 06.Artifact-creation/10.CI-CD/03.Azure DevOps/docs.md
- 06.Artifact-creation/10.CI-CD/docs.md
- 09.Downloads/docs.md
feat(CI/CD): Add CI/CD documentation
Ticket: MEN-5893
```
```
Thank you!
> feat(CI/CD): Add CI/CD documentation

- 07.Server-installation/06.Storage-of-the-artifacts/docs.md
> fix: canonical URL for storage-of-the-artifacts

- 09.Downloads/docs.md
> chore: Document mender-client Debian package contents and limitations

- 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/01.Customization/docs.md
- 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
See commit messages for each item improved
> chore: improve mender convert docs

- 02.Overview/15.Taxonomy/docs.md
- 05.System-updates-Yocto-Project/05.Customize-Mender/01.Delta-update-support/docs.md
* chore(Taxonomy): Fix formatting typo
* chore(Delta-update-support): Fix typo in yocto snippet
* chore(Delta-update-support): Manually update version to latest
> chores: Minor typos and update mender-binary-delta version

- 02.Overview/15.Taxonomy/docs.md
- package-lock.json
- package.json
From:
* https://github.com/mendersoftware/mender-docs/pull/1931
> 3.3.x: chore(package.json) + chore(Taxonomy)

- 06.Artifact-creation/10.CI-CD/02.GitLab-CICD/docs.md
Ticket: MEN-5889
Signed-off-by: Alex Miliukov <oleksandr.miliukov@northern.tech>
```
```
Thank you!
> chore(CI/CD-GitLab): jobs templates and examples

- 01.Get-started/06.Mender-Gateway/docs.md
chore(mender-gateway): Add download instructions for on-prem environments
Ticket: MEN-6006
```
```
Thank you!
> chore(mender-gateway): Add download instructions for on-prem environments

- 06.Artifact-creation/10.CI-CD/02.GitLab-CICD/docs.md
Reverts mendersoftware/mender-docs#1949
> MEN-5889: CI/CD templates for GitLab CI

- 07.Server-installation/03.Installation-with-docker-compose/04.Enabling-device-license-count/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/06.Enabling-device-license-count/docs.md
- 07.Server-installation/07.Device-license-count/docs.md
> feat: Device count via deviceauth-enterprise cli.

- 09.Downloads/docs.md
> feat: be more explicit on the APT repo installing the latest versions

- 06.Artifact-creation/10.CI-CD/03.Azure-DevOps/docs.md
Ticket: MEN-5890
Signed-off-by: Alex Miliukov <oleksandr.miliukov@northern.tech>
```
```
Thank you!
> MEN-5890: Azure DevOps CI/CD templates and examples

- 02.Overview/16.Requirements/docs.md
```
fix: added HM EU artifacts URLs requirements
Ticket: None
```
Added HM EU artifacts URLS requirement, tab organized.
> Hm eu artifacts urls requirements

- 02.Overview/16.Requirements/docs.md
```
fix: removed artifacts urls used for custom requests only
Ticket: None
```
Some of the URLs are used just for some clients with customization. No need to 
expose it to the public.
Thank you!
> Removing wrong urls

- .gitlab-ci.yml
- README-hosted-maintenance.markdown
> `hosted` update 2023-01-03

- 02.Overview/01.Introduction/docs.md
- 06.Artifact-creation/03.Combining-system-and-application-updates/docs.md
> feat: document how to combine system and application updates

- 03.Client-installation/07.Configuration-file/50.Configuration-options/docs.md
- 06.Artifact-creation/07.Sign-and-verify/docs.md
See https://github.com/mendersoftware/mender/pull/1108 for details.
Ticket: None
Signed-off-by: Michael Ho <callmemikeh@gmail.com>
> feat: document new ArtifactVerifyKeys option

- 01.Get-started/03.Deploy-a-system-update/docs.md
- 04.System-updates-Debian-family/01.Overview/docs.md
- 06.Artifact-creation/02.Create-an-Artifact-with-system-snapshot/docs.md
> fix: make instructions to modify the device software OS agnostic

- 01.Get-started/06.Mender-Gateway/docs.md
- 08.Server-integration/04.Mender-Gateway/99.Configuration-file/docs.md
> feat: add a paragraph about Device Systems in the Mender Gateway docs

- 06.Artifact-creation/10.CI-CD/02.GitLab-CICD/docs.md
Ticket: None
Signed-off-by: Alex Miliukov <oleksandr.miliukov@northern.tech>
```
```
Thank you!
> docs(gitlab-ci-cd): markdown typo fix

- 06.Artifact-creation/10.CI-CD/02.GitLab-CICD/docs.md
Ticket: None
Signed-off-by: Alex Miliukov <oleksandr.miliukov@northern.tech>
```
```
Thank you!
> GitLab CI: Markdown typo fix

- 03.Client-installation/07.Configuration-file/docs.md
See:
* https://github.com/mendersoftware/mender/pull/999
* https://github.com/mendersoftware/mender/pull/1131 (re-submit)
> docs: Document contributed feature to override Mender dir paths

- .ispell_english
- 04.System-updates-Debian-family/99.Variables/docs.md
Changelog: Add zstd documentation
Ticket: None
Signed-off-by: Michael Ho <callmemikeh@gmail.com>
> feat: add zstd documentation

- 07.Server-installation/01.Overview/docs.md
- 07.Server-installation/02.Demo-installation/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/07.OpenSearch/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/docs.md
Ticket: [MEN-5973](https://tracker.mender.io/browse/MEN-5973)
> update server installation docs

- 08.Server-integration/08.SAML-Federated-Authentication/docs.md
This came from the questions received in support.
Ticket: None
Signed-off-by: Alan <alan.martinovic@northern.tech>
> fix: Small extension of SAML docs

- 01.Get-started/06.Mender-Gateway/docs.md
> MEN-6285: fix: Amend syntax error in example configuration file

- 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
Adds to the documentation an example on creating & deploying an Update Module that safely modifies the mender.conf file with the EU Hosted Mender server URL.
Ticket: CE-36
Signed-off-by: Esteban Agüero Pérez <esteban.aguero@northern.tech>
```
```
Thank you!
> feat: Document how to use a custom Update Module Mender for EU migration

- 06.Artifact-creation/05.Server-side-generation-of-Delta-Artifacts/docs.md
> fix: server side delta generation docs update.

- test_docs.py
Ticket: QA-348
```
```
Thank you!
> QA-348: ci: adjust test to run on relevant integration branch

- 01.Get-started/06.Mender-Gateway/docs.md
- 02.Overview/15.Taxonomy/docs.md
- 08.Server-integration/04.Mender-Gateway/99.Configuration-file/docs.md
- 08.Server-integration/04.Mender-Gateway/docs.md
> feat: rename `Device System` to `System`

- 07.Server-installation/02.Upgrading-from-previous-versions/100.Upgrading-to-3.5/docs.md
feat: upgrading Mender Server: upgrading to 3.5
Ticket: MEN-6219
> feat: upgrading Mender Server: upgrading to 3.5

- 07.Server-installation/02.Upgrading-from-previous-versions/090.Upgrading-from-3.3-to-3.4/docs.md
- 07.Server-installation/02.Upgrading-from-previous-versions/docs.md
feat: upgrading Mender Server: upgrading to 3.4
Ticket: MEN-6219
> feat: upgrading Mender Server: upgrading to 3.4

- 07.Server-installation/02.Upgrading-from-previous-versions/090.Upgrading-from-3.4-to-3.5/docs.md
Ticket: None
- Remove the section in 3.5. which already exists in the general guidelins.
- Use the same chapter format
Old:
New:
I will be cherry pick to the individual branches after this is merged.
> feat: Minor structural improvements

- 08.Server-integration/01.Using-the-apis/docs.md
Adds to the PAT documentation a warning for customers interested in upgrading and are currently using personal access tokens.
Ticket: IBT-330
```
```
Thank you!
> feat: Warning for customers the PAT will be reset at plan upgrades

- 302.Release-information/03.Open-source-licenses/docs.md
(cherry picked from commit 804d599a07edf656809df8ca5af5667c4187310a)
> Update licenses for Mender 3.5.1.

- 301.Troubleshoot/02.Yocto-Project-runtime/docs.md
> update bugtracker link

- autoversion.py
(cherry picked from commit c0073d1c58078cc0ce647ee20b1441206b7e2818)
> autoversion: Don't fetch versions online when offline was requested.

- 06.Artifact-creation/05.Server-side-generation-of-Delta-Artifacts/docs.md
> Change availability of server side delta gen

- 06.Artifact-creation/10.CI-CD/01.GitHub-Actions/docs.md
- 06.Artifact-creation/10.CI-CD/02.GitLab-CICD/docs.md
- 06.Artifact-creation/10.CI-CD/03.Azure-DevOps/docs.md
- 06.Artifact-creation/10.CI-CD/docs.md
> chore: fix typos and grammar

- 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
```
fix: fixed kubectl command
Ticket: None
```
Fixed wrong `kubectl` command by correcting the `--` position.
> fix: fixed kubectl command

- 08.Server-integration/03.Mutual-TLS-authentication/docs.md
> Add comment on how to gain access to mtls proxy evaluation

- 05.Operating-System-updates-Yocto-Project/02.Board-integration/03.Raw-flash/docs.md
> remove Toradex boards from MTD chapter

- 06.Artifact-creation/04.State-scripts/docs.md
→ btw. this is a deadlink
```
```
For me, it was confusing that artifact state scripts are deployed differently than root filesystem state scripts.
So, I clarified the description on how to use of artifact state scripts in contrast to root filesystem state scripts.
> docs: Improve description how to use of artifact state scripts

- 10.Downloads/docs.md
In all other snippets, sudo is included. For modifying sources.list, it is also required.
Ticket: None
```
```
Thank you!
> fix: add missing sudo in client installation

- 05.Operating-System-updates-Yocto-Project/04.Image-customization/02.Read-only-root-filesystem/docs.md
> fix: broken link

- 05.Operating-System-updates-Yocto-Project/06.Build-for-production/docs.md
> fix: broken link to the Yocto documentation

- 05.Operating-System-updates-Yocto-Project/99.Variables/docs.md
Ticket: None
(cherry picked from commit 77a43f2447168f35b244779db40741f1fedf9306)
> fix: broken links

- 06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
So far the absolute basics on Update Modules are not present in the documentation. To reduce user friction, add them.
Ticket: None
```
```
Thank you!
> feat: add Update Module basics

- 05.Operating-System-updates-Yocto-Project/05.Customize-Mender/01.Delta-update-support/docs.md
> fix: replace MENDER_ENTERPRISE_EMAIL with MENDER_ENTERPRISE_USER

- .gitlab-ci.yml
Cherry picks 71f75f7c58cf405df402f9a5c67e05fcb83a36eb
> QA-513: ci: Modernize downstream triggers to stop using trigger tokens

- 302.Release-information/01.Release-schedule/docs.md
Master merge for extending 3.3 support.
Once approved will cherry pick to Hosted and 3.3.
> feat: extend 3.3 support 

- 07.Server-installation/04.Production-installation-with-kubernetes/01.Kubernetes/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
```
fix: forcing user to set a strong mongodb root password
Changelog: forcing user to set a strong mongodb root password
Ticket: None
```
Forcing user to set a strong mongodb root password
> chore: forcing user to set a strong password

- 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
> [Cherry 3.3.x]: chore: forcing user to set a strong password

- 03.Client-installation/07.Configuration-file/50.Configuration-options/docs.md
> docs: states TenantToken should be trated as a secret

- 01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
- 01.Get-started/03.Deploy-an-operating-system-update/docs.md
- 01.Get-started/04.Deploy-a-container-update/docs.md
- 02.Overview/02.Device-Support/docs.md
- 02.Overview/03.Artifact/docs.md
- 03.Client-installation/02.Install-with-Debian-package/docs.md
- 03.Client-installation/03.Identity/docs.md
- 03.Client-installation/04.Inventory/docs.md
- 04.Operating-System-updates-Debian-family/01.Overview/docs.md
- 04.Operating-System-updates-Debian-family/02.Convert-a-Mender-Debian-image/01.Customization/docs.md
- 04.Operating-System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
- 05.Operating-System-updates-Yocto-Project/03.Build-for-demo/docs.md
- 05.Operating-System-updates-Yocto-Project/04.Image-customization/03.State-scripts/docs.md
- 05.Operating-System-updates-Yocto-Project/05.Customize-Mender/docs.md
- 06.Artifact-creation/01.Create-an-Artifact/docs.md
- 06.Artifact-creation/07.Sign-and-verify/docs.md
- 06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
- 07.Server-installation/02.Evaluation-with-docker-compose/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
- 08.Server-integration/01.Using-the-apis/docs.md
- 08.Server-integration/02.Preauthorizing-devices/docs.md
- 08.Server-integration/03.Mutual-TLS-authentication/docs.md
- 10.Downloads/docs.md
- 200.Server-side-API/chapter.md
- 301.Troubleshoot/01.Yocto-project-build/docs.md
- 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
- home/chapter.md
> feat: run autoversion targeting Mender 3.6.0

- 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
```
fix: using the correct k8s label
Changelog: using the correct k8s label
Ticket: None
```
using the correct k8s label
> fix: using the correct k8s label

- 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
```
chore: update helm chart to 5.0.2
Changelog: update helm chart to 5.0.2
Ticket: MC-6924
```
update helm chart to 5.0.2
> Update to 5.0.2 helm chart version

- 01.Get-started/03.Deploy-an-operating-system-update/docs.md
- 01.Get-started/04.Deploy-a-container-update/docs.md
- 02.Overview/02.Device-Support/docs.md
- 02.Overview/03.Artifact/docs.md
- 03.Client-installation/02.Install-with-Debian-package/docs.md
- 03.Client-installation/03.Identity/docs.md
- 03.Client-installation/04.Inventory/docs.md
- 05.Operating-System-updates-Yocto-Project/03.Build-for-demo/docs.md
- 05.Operating-System-updates-Yocto-Project/05.Customize-Mender/docs.md
- 06.Artifact-creation/01.Create-an-Artifact/docs.md
- 06.Artifact-creation/07.Sign-and-verify/docs.md
- 06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
- 07.Server-installation/02.Evaluation-with-docker-compose/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
- 08.Server-integration/01.Using-the-apis/docs.md
- 08.Server-integration/02.Preauthorizing-devices/docs.md
- 08.Server-integration/03.Mutual-TLS-authentication/docs.md
- 10.Downloads/docs.md
- 301.Troubleshoot/01.Yocto-project-build/docs.md
- 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
- 302.Release-information/01.Release-schedule/docs.md
> feat: update versions for Mender 3.6.0

- 302.Release-information/01.Release-schedule/docs.md
> feat: add 3.6 as LTS

- .gitlab-ci.yml
- 06.Artifact-creation/10.CI-CD/01.GitHub-Actions/docs.md
- 06.Artifact-creation/10.CI-CD/02.GitLab-CICD/docs.md
- 06.Artifact-creation/10.CI-CD/03.Azure-DevOps/docs.md
- 06.Artifact-creation/10.CI-CD/docs.md
> feat: update versions after the Mender 3.6.0 release

- 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
> fix: tag for Mender 3.6

- 10.Downloads/docs.md
Ubuntu Bionic standard LTS support is EOL.
> QA-600: chore: Deprecate Ubuntu Bionic debian packages

- 301.Troubleshoot/05.Device-Runtime/docs.md
> fix: broken link for ttssh2

- 10.Downloads/docs.md
Follow-up for commit 0117c6127f4a96457368ae608e3eb51aedb386e8.
Ticket: QA-600
> fix: failure after deprecating Ubuntu Bionic debian packages

- 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
```
chore: updated helm chart version to 5.0.3
Changelog: updated helm chart version to 5.0.3
Ticket: None
```
updated helm chart version to 5.0.3
> chore: updated helm chart version to 5.0.3

- 02.Overview/11.Security/docs.md
Ticket: None
Cherry-picks:
* https://github.com/mendersoftware/mender-docs/pull/2208
* https://github.com/mendersoftware/mender-docs/pull/2209
* https://github.com/mendersoftware/mender-docs/pull/2210
* https://github.com/mendersoftware/mender-docs/pull/2211
> fix: add ECDSA and ED25519 as supported keys for the Mender client

- 302.Release-information/01.Release-schedule/docs.md
Ticket: NOne
(cherry picked from commit 8965d034e779191879c878ab50a6fd374babe057)
> fix: sort the LTS releases from the most recent to the oldest

- 01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
- 04.Operating-System-updates-Debian-family/01.Overview/docs.md
- 04.Operating-System-updates-Debian-family/02.Convert-a-Mender-Debian-image/01.Customization/docs.md
- 04.Operating-System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
- 07.Server-installation/02.Evaluation-with-docker-compose/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
- 08.Server-integration/03.Mutual-TLS-authentication/docs.md
- 10.Downloads/docs.md
> feat: update versions for Mender 3.6.2

- 02.Overview/16.Requirements/docs.md
```
chore: update Firewall requirements
Changelog: New Firewall requirements: Cloudflare
Ticket: MC-6961
```
Adding Cloudflare as a Firewall exception rules.
> Cloudflare firewall requirements

- 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
Changelog: fix: specify region for hosted configuration
Ticket: None
Signed-off-by: Michael Mugnai <michael.mugnai@gmail.com>
(cherry picked from commit 48aa06cbb345f15bf1d39f332cdbe6b3827cfe91)
> fix: specify region for hosted configuration

- 03.Client-installation/08.Integration-checklist/docs.md
Ticket: CE-128
A revamp of the integration checklist.
Got a feedback back in January that it's hard to follow.
Was doing a verification of an integration so used the opportunity to clean it up.
Please share your judgement if it's an improvement :)
> fix: revamp of the integration checklist

- 06.Artifact-creation/05.Server-side-generation-of-Delta-Artifacts/docs.md
> feat: Update server side delta

- 09.Add-ons/50.Remote-Terminal/docs.md
> feat: add docs on how to use the terminal with your shell

- 04.Operating-System-updates-Debian-family/03.Customize-Mender/01.Delta-update-support/docs.md
```
```
Adds information on how to enable delta updates on Debian based images
Thank you!
> Docs: Add delta support for Debian images

- 07.Server-installation/09.Direct-upload/docs.md
The majority of our contributions are fixes, which means your commit should have the form below:
```
```
Thank you!
> CE-256 First iteration over direct upload section

- 07.Server-installation/04.Production-installation-with-kubernetes/docs.md
(cherry picked from commit f7369c7296c7e6de207f373920597242b9b5be2f)
> Memorystore Typo in docs.md

- 06.Artifact-creation/05.Create-a-Delta-update-Artifact/docs.md
- 06.Artifact-creation/05.Server-side-generation-of-Delta-Artifacts/docs.md
Ticket: None
```
```
It warns Mender delta deployments have not been tested over UBIFS
Thank you!
> Fix: Warns Mender delta updates not being tested on UBIFS

- 05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
> fix: broken links to the Yocto documentation

- 06.Artifact-creation/03.Modify-an-Artifact/docs.md
Added behaviour description of signature and checksum  while using `mender-aritfact cp ...` commands.
> Empasised checksum and signature behaviour on artifact modification

- 01.Get-started/01.Preparation/02.Prepare-a-virtual-device/docs.md
> fix: Grammar tweaks in Prepare a Virtual Device chapter.

- 02.Overview/16.Requirements/docs.md
> chore: add more info on the firewall change

- 301.Troubleshoot/05.Device-Runtime/docs.md
> fix: link to ttssh2

- .gitlab-ci.yml
> fix: `latest_versions` test for the `hosted` branch

- 08.Server-integration/03.Mutual-TLS-authentication/docs.md
> fix: misprints in the MTLS env. variables definition

- 11.General/00.Hosted-Mender-regions/docs.md
> Update hosting region description

- 06.Artifact-creation/10.CI-CD/01.GitHub-Actions/docs.md
Ticket: None
```
```
Thank you!
> docs: fix typo in github actions page

- 06.Artifact-creation/01.Create-an-Artifact/09.Kubernetes/docs.md
> docs: k8s application module support

- 01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
- 01.Get-started/03.Deploy-an-operating-system-update/docs.md
- 01.Get-started/04.Deploy-a-container-update/docs.md
- 02.Overview/02.Device-Support/docs.md
- 02.Overview/03.Artifact/docs.md
- 03.Client-installation/02.Install-with-Debian-package/docs.md
- 03.Client-installation/03.Identity/docs.md
- 03.Client-installation/04.Inventory/docs.md
- 04.Operating-System-updates-Debian-family/01.Overview/docs.md
- 04.Operating-System-updates-Debian-family/02.Convert-a-Mender-Debian-image/01.Customization/docs.md
- 04.Operating-System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
- 05.Operating-System-updates-Yocto-Project/03.Build-for-demo/docs.md
- 05.Operating-System-updates-Yocto-Project/05.Customize-Mender/docs.md
- 06.Artifact-creation/01.Create-an-Artifact/docs.md
- 06.Artifact-creation/07.Sign-and-verify/docs.md
- 06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
- 08.Server-integration/01.Using-the-apis/docs.md
- 08.Server-integration/02.Preauthorizing-devices/docs.md
- 10.Downloads/docs.md
- 301.Troubleshoot/01.Yocto-project-build/docs.md
- 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> fix: update versions for Mender 3.7.0

- 01.Get-started/04.Deploy-a-container-update/docs.md
- 02.Overview/02.Device-Support/docs.md
- 03.Client-installation/02.Install-with-Debian-package/docs.md
- 03.Client-installation/03.Identity/docs.md
- 03.Client-installation/04.Inventory/docs.md
- 05.Operating-System-updates-Yocto-Project/03.Build-for-demo/docs.md
- 06.Artifact-creation/01.Create-an-Artifact/docs.md
- 06.Artifact-creation/07.Sign-and-verify/docs.md
- 06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
- 08.Server-integration/02.Preauthorizing-devices/docs.md
- 301.Troubleshoot/01.Yocto-project-build/docs.md
- 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> feat: upgrade Mender client to version 3.5.2

- 06.Artifact-creation/01.Create-an-Artifact/09.Kubernetes/docs.md
- 06.Artifact-creation/01.Create-an-Artifact/10.Docker-Compose/docs.md
(cherry picked from commit 81692b05f3d391636bbc688acc3e58f4c5d48e70)
> feat: use `app-update-module` version `1.0.0`

- 302.Release-information/01.Release-schedule/docs.md
> Update `hosted` from latest `master`

- 01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
- 01.Get-started/03.Deploy-an-operating-system-update/docs.md
- 01.Get-started/04.Deploy-a-container-update/docs.md
- 02.Overview/02.Device-Support/docs.md
- 02.Overview/03.Artifact/docs.md
- 03.Client-installation/02.Install-with-Debian-package/docs.md
- 03.Client-installation/03.Identity/docs.md
- 03.Client-installation/04.Inventory/docs.md
- 03.Client-installation/08.Integration-checklist/docs.md
- 04.Operating-System-updates-Debian-family/01.Overview/docs.md
- 04.Operating-System-updates-Debian-family/02.Convert-a-Mender-Debian-image/01.Customization/docs.md
- 04.Operating-System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
- 05.Operating-System-updates-Yocto-Project/03.Build-for-demo/docs.md
- 06.Artifact-creation/01.Create-an-Artifact/docs.md
- 06.Artifact-creation/07.Sign-and-verify/docs.md
- 06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
- 07.Server-installation/02.Evaluation-with-docker-compose/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
- 08.Server-integration/02.Preauthorizing-devices/docs.md
- 08.Server-integration/03.Mutual-TLS-authentication/docs.md
- 10.Downloads/docs.md
- 301.Troubleshoot/01.Yocto-project-build/docs.md
> feat: update versions for Mender 3.7.2

- 03.Client-installation/02.Install-with-Debian-package/docs.md
- 10.Downloads/docs.md
> chore: update documentation after the introduction of `mender-client4`

- 07.Server-installation/02.Upgrading-from-previous-versions/090.Upgrading-from-3.6-to-3.7/docs.md
Content and URL updated:
server-installation/upgrading-from-previous-versions/upgrading-from-3.6-to-3.7
Ticket: MEN-7002
```
```
Thank you!
> chore: Update upgrade instructions to match going from 3.6 to 3.7

- 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
Ticket: MEN-6976
(cherry picked from commit e8f14ab2907d071651acbebdb6f9aaa0f4347bf4)
> chore: reword the upgrade guide from 3.x to 4.x using Debian packages

- 06.Artifact-creation/04.State-scripts/docs.md
> feat: document execution location for artifact state scripts

- 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> chore: add a troubleshooting section to the Debian packages upgrade page

- 03.Client-installation/07.Configuration-file/50.Configuration-options/docs.md
Ticket: None
(cherry picked from commit b82cbfb5e0aab82d366e819d7b05643aa1da8736)
> fix: link to 3.6 documentation

- 07.Server-installation/02.Upgrading-from-previous-versions/090.Upgrading-from-3.6-to-3.7/docs.md
> Update/instructions 3.6 to 3.7

- 07.Server-installation/02.Upgrading-from-previous-versions/090.Upgrading-from-3.6-to-3.7/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/docs.md
> fix: Update upgrade instructions to use MongoDB 6.0

- 07.Server-installation/02.Upgrading-from-previous-versions/090.Upgrading-from-3.6-to-3.7/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/docs.md
Ticket: MC-7222
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>
(cherry picked from commit 597601a2dae183909f28b1635f453ef4ab5253c3)
> :cherries: fix: Update upgrade instructions to use MongoDB 6.0

- 03.Client-installation/08.Integration-checklist/docs.md
I have decided to check latest available bullseye RPi OS release for compatibility with Mender. When doing so, I used  `Integration checklist` page of a manual as a guide to confirm a successful integration.
However, the default integration of Debian based RPi OS image is via UBoot, however there were no detailed steps within a manual on the way to check the integrations with UBoot bootloader. There was only a brief that mentions a possible difference of integration either via GRUB or UBoot but there were no practical steps showcased for UBoot integration. So, I fixed that. 
PS  I used [this file](https://github.com/mendersoftware/mender-docs/blob/hosted/01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md) as inspiration
> Added UBoot integration checklist steps

- 06.Artifact-creation/02.Create-an-Artifact-with-system-snapshot/docs.md
Submitted-by: Antonio Park <dkalxkwl@gmail.com>
> fix: correct typo in Artifact-creation session

- 10.Downloads/docs.md
Cherry-picking #2349, #2355 and #2354.
> 3.7.x: Debian Bookworm + misc cherry-picks

- 07.Server-installation/02.Evaluation-with-docker-compose/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
- 08.Server-integration/03.Mutual-TLS-authentication/docs.md
Bugfix release
Ticket: None
```
```
Bump Mender Helm to version 3.6.4
> Bump to version 3.6.4

- 07.Server-installation/02.Evaluation-with-docker-compose/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
```
```
Bump mender to 3.7.4
Thank you!
> Bump to version 3.7.4

- 02.Overview/16.Requirements/docs.md
We're now offering cloudflare for Enterprise plans as well, this makes the note unnecessary.
Ticket: None
```
```
We're now offering cloudflare for Enterprise plans as well, this makes the note unnecessary.
> chore: removing unnecessary note

- 08.Server-integration/09.OIDC-Federated-Authentication/docs.md
> docs: OpenID Connect under federated login.

- 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
```
fix: Added documentation for the Ingress included in the Helm Chart
Changelog: Added documentation for the Ingress included in the Helm Chart
Ticket: MC-6912
```
Added documentation for the Ingress included in the Helm Chart
**Note:** this has to be cherry picked to the 3.6 or later releases.
> Helm with Ingress included - master

- 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
```
fix: Added documentation for the Ingress included in the Helm Chart
Changelog: Added documentation for the Ingress included in the Helm Chart
Ticket: MC-6912
```
Added documentation for the Ingress included in the Helm Chart
Cherry picked: https://github.com/mendersoftware/mender-docs/pull/2383/commits/cea16b2791e358edb0574895e00923dfcbe908d9
> 3.7.x Ingress docs

- 302.Release-information/01.Release-schedule/docs.md
Cherry-picking #2388 and #2389.
> 3.7.x: Promote Mender 3.7 to LTS

- 302.Release-information/01.Release-schedule/docs.md
Cherry-picking #2388 and #2389.
> hosted: Promote Mender 3.7 to LTS

- 07.Server-installation/04.Production-installation-with-kubernetes/docs.md
Mender backend supports also arm64 architectures
Ticket: MC-7477
```
```
Mender backend supports also arm64 architectures
> Add arm64 to the supported Mender backend architectures

- 06.Artifact-creation/01.Create-an-Artifact/09.Kubernetes/docs.md
- 08.Server-integration/03.Mutual-TLS-authentication/01.Keys-and-certificates/docs.md
- 08.Server-integration/08.SAML-Federated-Authentication/02.azure-entra-id/docs.md
- 10.Downloads/docs.md
> chore: clean up taxonomy on hosted-specific pages

- 04.Operating-System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
- 04.Operating-System-updates-Debian-family/03.Customize-Mender/docs.md
- 06.Artifact-creation/01.Create-an-Artifact/10.Docker-Compose/docs.md
- 06.Artifact-creation/05.Server-side-generation-of-Delta-Artifacts/docs.md
- 08.Server-integration/08.SAML-Federated-Authentication/03.OKTA/docs.md
- 11.General/00.Hosted-Mender-regions/docs.md
- 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> chore: clean up taxonomy inconsistencies

- 04.Operating-System-updates-Debian-family/03.Customize-Mender/02.Mender-monitor-support/docs.md
- 04.Operating-System-updates-Debian-family/99.Variables/docs.md
Documentation for installing mender-monitor with mender-convert
> MEN-7264: Documentation for mender-convert installation using mender-convert

- 08.Server-integration/04.Mender-Gateway/10.Mutual-TLS-authentication/02.Evaluation-with-docker-compose/docs.md
Ticket: None
```
```
Thank you!
> chore: mender.conf update for the Gateway mTLS ambassador

- 302.Release-information/01.Release-schedule/docs.md
Ticket: None
See: https://gitlab.com/Northern.tech/Mender/mender-docs/-/jobs/7293659477
> chore: sort LTS versions to make autoversioning test happy

- 06.Artifact-creation/02.Create-an-Artifact-with-system-snapshot/docs.md
Title: None
```
```
Thank you!
> fix: Change stderr to stdout as described in mender-snapshot help menu

- 01.Get-started/04.Deploy-a-container-update/docs.md
- 02.Overview/02.Device-Support/docs.md
- 03.Client-installation/02.Install-with-Debian-package/docs.md
- 03.Client-installation/03.Identity/docs.md
- 03.Client-installation/04.Inventory/docs.md
- 03.Client-installation/08.Integration-checklist/docs.md
- 05.Operating-System-updates-Yocto-Project/03.Build-for-demo/docs.md
- 06.Artifact-creation/01.Create-an-Artifact/docs.md
- 06.Artifact-creation/07.Sign-and-verify/docs.md
- 06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
- 08.Server-integration/02.Preauthorizing-devices/docs.md
- 08.Server-integration/03.Mutual-TLS-authentication/01.Keys-and-certificates/docs.md
- 301.Troubleshoot/01.Yocto-project-build/docs.md
> hosted: Update version for Mender client 4.0.4 release

- 10.Downloads/docs.md
> hosted: Cherry-pick repositories updates

- 01.Get-started/02.Deploy-an-application-update/docs.md
Ticket: CE-425
Signed-off-by: Nick Anderson <nick@cmdln.org>
-------
```
```
This change simply adjusts a note to reference the variable that holds the IP instead of the variable that holds the container ID.
> fix: Fixed note on how to access getting started example application on virtual device by IP

- 302.Release-information/01.Release-schedule/docs.md
> 3.7.x: LTS release cherry-picks

- 302.Release-information/01.Release-schedule/docs.md
> 3.6.x: LTS release cherry-picks

- 301.Troubleshoot/01.Yocto-project-build/docs.md
> hosted: chore: Remove obsolete troubleshoot entry

- 301.Troubleshoot/01.Yocto-project-build/docs.md
> 3.7.x: chore: Remove obsolete troubleshoot entry

- 01.Get-started/05.Monitor/docs.md
Ticket: CE-413
```
```
Added a disclaimer when getting started with mender-monitor about the virtual device not being supported (it's not installed on the virtual device and there is no package manager).
> Added disclaimer about virtual device for getting started with Monitor

- 03.Client-installation/01.Overview/docs.md
```
```
Fix for spelling
Thank you!
> fix: Corrected spelling error

- 10.Downloads/docs.md
Set the new expiration date for the Official Mender GPG Key, after extending its lifetime
Ticket: QA-775
```
```
Set the new expiration date for the Official Mender GPG Key, after extending its lifetime
> Set new expiration date

- 08.Server-integration/04.Mender-Gateway/10.Mutual-TLS-authentication/03.Production-installation-with-kubernetes/docs.md
Also added HTTPS_MINIMUM_TLS_VERSION that could be useful to customers looking for advanced security customizations.
Ticket: None
```
```
Added MTLS_ENABLED variable which was missing. Also added HTTPS_MINIMUM_TLS_VERSION that could be useful to customers looking for advanced security customizations.
Ticket: None
> doc: added missing MTLS_ENABLED variable

- 01.Get-started/04.Deploy-a-container-update/docs.md
- autoversion.py
The update module won't be part of the default installation for the next Mender Client release.
> MEN-7672: Update Deploy a container update tutorial

- 06.Artifact-creation/01.Create-an-Artifact/10.Docker-Compose/docs.md
On generating the docker-compose file
Ticket: None
```
```
resolve yaml issue \oOn generating the docker-compose file
> docs: resolve yaml issue

- 01.Get-started/05.Monitor/docs.md
- 06.Artifact-creation/01.Create-an-Artifact/09.Kubernetes/docs.md
> docs: updated command from mender to mender-update

- 01.Get-started/05.Monitor/docs.md
- **docs: updated command from mender to mender-update**
- **docs: added comment to run script as root**
```
```
Thank you!
> "docs: added comment to run script as root"

- 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/docs.md
The SP Tenants feature requires an admin user to delete mongodb databases if needed.
Ticket: None
```
```
The SP Tenants feature requires an admin user to delete mongodb databases if needed.
> docs: notes for sp feature and mongo

- 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
The Mender Server v3.7 supports up to version 5.x of the helm chart only.
```
```
The Mender Server v3.7 supports up to version 5.x of the helm chart only.
> docs: explicit reference helm v5.x

- 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
The heredoc string is duplicated. Removing the unnecessary lines
TIcket: None
```
```
The heredoc string is duplicated. Removing the unnecessary lines
> docs: fix ingress heredoc duplicate

- 04.Operating-System-updates-Debian-family/99.Variables/docs.md
Added description about the `MENDER_SPARSE_IMAGE` flag added in [mender-convert#722](https://github.com/mendersoftware/mender-convert/pull/722)
> docs: add description of MENDER_SPARSE_IMAGE variable

- autoversion.py
> chore: hardcore value for Mender LTS versions in autorevision.py

- 301.Troubleshoot/03.Mender-Client/docs.md
> docs: Add a troubleshoot entry for ` mender: command not found` error

- 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
```
```
The helm chart now includes the optional `DEPLOYMENTS_STORAGE_PROXY_URI` as the value of the .Values.global.url .Values.api_gateway.storage_proxy is enabled.
Ticket: MC-7739
> docs: exclude DEPLOYMENTS_STORAGE_PROXY_URI env var

- 10.Downloads/docs.md
Porting (rewriting) #2529 for 3.7.x
> 3.7.x: Fix `mender-artifact` download links

- 07.Server-installation/04.Production-installation-with-kubernetes/docs.md
Ticket: None
```
```
Thank you!
> docs: fix typo in production installation with kubernetes

- 02.Overview/12.Role.Based.Access.Control/docs.md
- 02.Overview/13.Multi-Tenancy/docs.md
> fix: adjust indentation on headers to ensure pages show up on search

- 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
Ingress keys are duplicated
Ticket: None
```
```
Ingress keys are duplicated
> docs: remove duplicated keys

- 07.Server-installation/02.Evaluation-with-docker-compose/docs.md
- 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
> docs(Server-installation): replace release candidate tags with final release tag

- 08.Server-integration/05.Azure-IoT-Hub/docs.md
- 08.Server-integration/06.AWS-IoT-Core/docs.md
- 08.Server-integration/07.Webhooks/docs.md
- 08.Server-integration/chapter.md
Ticket: CE-547
Signed-off-by: Nick Anderson <nick@cmdln.org>
> docs: Clarified limitation of single integration (Azure|Aws|Webhooks)

- 02.Overview/13.Multi-Tenancy/service-provider.md
- package-lock.json
> align stable with master

- README-styleguide.markdown
> chore: small adjustments to style guide

- 06.Artifact-creation/07.Sign-and-verify/docs.md
> docs: Add support for Azure Key Vault

- 07.Server-installation/04.Production-installation-with-kubernetes/02.Storage/docs.md
Ticket: CE-595
```
```
Provide more details to make the Storage Proxy feature works with Azure Blob Storage
> docs: fix export variables for Azure Blob Storage

- 02.Overview/15.Compatibility-policy/docs.md
Ticket: QA-954
```
```
Thank you!
> docs(Overview/Compatibility-policy): describe deprecation policy

- 01.Get-started/07.Microcontroller-preview/02.Deploy-a-firmware-update/docs.md
- 06.Operating-System-updates-Zephyr/03.Bootloader-support/docs.md
Fix docs issues spotted by Vratia.
> (fix) Fix Zephyr documentation issues spotted on the live site.

- 01.Get-started/07.Microcontroller-preview/01.Prepare-an-esp32-s3-with-Zephyr/docs.md
- 01.Get-started/07.Microcontroller-preview/02.Deploy-a-firmware-update/docs.md
- 01.Get-started/07.Microcontroller-preview/docs.md
- 06.Operating-System-updates-Zephyr/02.Board-integration/docs.md
- 06.Operating-System-updates-Zephyr/04.Customize-Mender-mcu/docs.md
- 06.Operating-System-updates-Zephyr/05.Configuration/docs.md
- 06.Operating-System-updates-Zephyr/chapter.md
> chore: Removed duplicated headings and adjusted subheading levels

- 08.Server-installation/05.Backup-and-restore/docs.md
Added basic guidelines for backing up and restoring a Mender server instance.
Ticket: MC-7375
```
```
Second tentative about basic guidelines for backing up and restoring a Mender server
instance. First run: https://github.com/mendersoftware/mender-docs/pull/2361
> chore: basic backup and restore documentation

- 09.Server-integration/01.Using-the-apis/docs.md
> chore: Fix typo chatper->chapter in Using the APIs

- 10.Add-ons/20.Monitor/40.Configuration/docs.md
Ticket: MEN-7216
Related code PR: https://github.com/mendersoftware/monitor-client/pull/162
> chore: Update DBUS_PATTERN and DBUS_WATCH_EXPRESSION description

- 302.Release-information/01.Supported-releases/docs.md
> chore: Add mender-flash version to client subcomponents

- 09.Server-integration/04.Mender-Gateway/99.Configuration-file/docs.md
> Fix: typo in HTTPS_MINIMUM_TLS_VERSION variable

- 01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
In recent versions of RPi the designated way to configure wifi is to use rpi-imager. This fact needs to be reflected in our documentation.
Ticket: MEN-8547
Changelog: Update RPi wifi headless config howto
> chore: Update RPi wifi headless configuration howto

- 11.Downloads/docs.md
> chore: Reorganize download page for easier navigation

- 01.Get-started/01.Preparation/02.Prepare-a-virtual-device/docs.md
Task: None
Changelog: Change virtual device Get started instructions to be in line with UI
> docs: Change instruction to try a virtual device

- 02.Overview/02.Device-Support/docs.md
> chore: Add Zephyr and Mender MCU client to the Device Support page

- 11.Downloads/docs.md
These two were not being rendered correctly.
> docs: Fix formatting of bash snippets

- 11.Downloads/docs.md
The [previous attempt](https://github.com/mendersoftware/mender-docs/pull/2654) was not effective. This time I have rendered it locally to check ;)
> docs: Actually fix formatting of bash snippets

- 02.Overview/18.Limits/docs.md
> docs: Update the server-side delta limits

- 09.Server-integration/09.OIDC-Federated-Authentication/docs.md
**Description**
After working on the OpenID Connect implementation for a while I found the documentation of this feature to be a bit lacking - especially in terms of all the "gotchas" and how to get the it to work properly. 
I therefore propose these changes to the documentation to hopefully make it a bit easier for whoever comes next. Please do have a look and let me know if this is an improvement or not and/or if there's further changes you'd like to see.
--- 
Changelog: Added more information to the OIDC documentation to make it more clear what's required for a working setup.
Ticket: MEN-569
> docs: Improve OIDC documentation

- run-tests.sh
Recently Download page has been split into 3 separated chapters. This adds those chapters to the tested paths.
> ci: Update test path

- 07.Orchestrate-updates/04.Installation/01.Yocto-Project/docs.md
- 07.Orchestrate-updates/04.Installation/02.Debian-family/docs.md
- 07.Orchestrate-updates/04.Installation/docs.md
Add installation and download instructions for the Orchestrator for Debian and Yocto.
Ticket: MEN-8679
> docs: Add Mender Orchestrator installation instructions
