mendersoftware/mender-docs

04.Devices/02.Integrating-with-U-Boot/docs.md
=> Add section about U-Boot forks.

03.Artifacts/01.Building-Mender-Yocto-image/docs.md
=> Fix incorrect newline in example.

04.Devices/03.Integrating-with-U-Boot/docs.md
=> Clarify that FAT_ENV variables don't necessarily preexist.

04.Devices/04.Configuration-checklist/docs.md
=> MEN-547: Write verification checklist for correct U-Boot integration.

04.Devices/03.Integrating-with-U-Boot/docs.md
https://github.com/mendersoftware/meta-mender/pull/114
=> Documentation for meta-mender/114

04.Devices/03.Integrating-with-U-Boot/docs.md
=> Change u-boot-fw-utils instructions after change in meta-mender.

06.APIs/chapter.md
Reverts mendersoftware/mender-docs#36
=> Revert "Make APIs visible"

06.APIs/02.Device-APIs/03.Artifacts/docs.md, 06.APIs/03.Integration-APIs/04.Artifacts/docs.md
=> hide Artifact docs as they currently dont contain any documentation

06.APIs/chapter.md
=> Make API docs visible again

03.Artifacts/06.Variables/docs.md
Document MENDER_STORAGE_TOTAL_SIZE, MENDER_PARTITIONING_OVERHEAD_MB,
MENDER_PARTITION_ALIGNMENT_MB.
@kacf @eysteins @pasinskim
=> artifacts/variables: document storage & partitioning variables

03.Artifacts/01.Building-Mender-Yocto-image/docs.md
=> Clarify build image types

05.Client-configuration/02.Identity/docs.md
=> client-configuration/identity: update identity tool output format

04.Devices/03.Integrating-with-U-Boot/01.Providing-custom-u-boot-fw-utils/docs.md, 04.Devices/03.Integrating-with-U-Boot/docs.md
=> MEN-593: Make an example of a u-boot-fw-utils port.

04.Devices/03.Integrating-with-U-Boot/01.Providing-custom-u-boot-fw-utils/docs.md
=> Small adjustments after proof reading and checking rendering.

04.Devices/03.Integrating-with-U-Boot/01.Providing-custom-u-boot-fw-utils/docs.md
=> Fix broken links.

03.Artifacts/01.Building-Mender-Yocto-image/docs.md
=> Update docs with mention of default keys being used

03.Artifacts/01.Building-Mender-Yocto-image/docs.md, 03.Artifacts/03.Provisioning-a-new-device/docs.md, 04.Devices/02.Partition-layout/docs.md
=> Follow splitting of meta-mender into several layers.

04.Devices/03.Integrating-with-U-Boot/02.U-Boot-versions-without-BOOTLIMIT-support/docs.md
=> MEN-562: Document how to use custom bootlimit patch.

03.Artifacts/01.Building-Mender-Yocto-image/docs.md, 03.Artifacts/06.Variables/docs.md
* MENDER_ARTIFACT_NAME
* MENDER_DEVICE_TYPE
* MENDER_DEVICE_TYPES_COMPATIBLE
=> MEN-763: Document new artifact and device type related variables.

05.Client-configuration/04.Poll-intervals/docs.md
Signed-off-by: Marcin Pasinski <marcin.pasinski@cfengine.com>
=> Document modifying poll intervals.

01.Getting-started/04.Deploy-to-physical-devices/docs.md
Signed-off-by: Marcin Pasinski <marcin.pasinski@cfengine.com>
=> Update BBB getting started docs.

03.Devices/03.Integrating-with-U-Boot/docs.md, 04.Artifacts/06.Variables/docs.md
=> MEN-480: Update U-Boot env storage location and variables.

01.Getting-started/03.Deploy-to-virtual-devices/docs.md
=> Fix typo in docs.

06.Administration/01.Overview/docs.md, 06.Administration/02.Certificates/docs.md, 06.Administration/03.Tokens/docs.md, 06.Administration/04.Bandwidth/docs.md, 06.Administration/05.Storage/docs.md, 06.Administration/07.Production-Installation/docs.md, 06.Administration/chapter.md
@maciejmrowiec @mendersoftware/rndity @eysteins
=> administration: notes on administration & deployment

04.Artifacts/07.Variables/docs.md
=> Add documentation for variable: MENDER_DEMO_HOST_IP_ADDRESS

04.Artifacts/06.Building-for-production/docs.md
=> Explain how to generate the server.crt client cert from server certs.

06.Administration/02.Production-installation/docs.md, 06.Administration/06.Troubleshooting/docs.md
it's a work in progress but I'd like to get the comments as early as possible
@mendersoftware/rndity @maciejmrowiec @GregorioDiStefano @eysteins
=> administration: production-install

06.Administration/06.Troubleshooting/docs.md
Issues: MEN-922
Signed-off-by: mchalczynski <marcin.chalczynski@rndity.com>
accompanying doc for https://github.com/mendersoftware/integration/pull/147
@maciejmrowiec @mendersoftware/rndity
=> administration/troubleshooting: add password reset instructions

04.Artifacts/02.Build-customizations/docs.md
=> MEN-932: Document how to change server and port using Yocto.

200.APIs/03.Integration-APIs/06.User-administration-and-admission/docs.md
we'll automatically generate these docs just like all other.
goes with https://github.com/mendersoftware/useradm/pull/32
Issues: MEN-976
Signed-off-by: mchalczynski <marcin.chalczynski@rndity.com>
=> apis/integration: make room for useradm docs

01.Getting-started/02.Create-a-test-environment/docs.md, 01.Getting-started/03.Deploy-to-virtual-devices/docs.md, 01.Getting-started/04.Deploy-to-physical-devices/docs.md, 01.Getting-started/05.Standalone-deployments/docs.md, 04.Artifacts/01.Building-Mender-Yocto-image/docs.md, 04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md
Signed-off-by: Marcin Pasinski <marcin.pasinski@mender.io>
=> Add 1.0.x specific changes.

06.Administration/03.Certificates-and-keys/docs.md
=> Certs issues

01.Getting-started/05.Standalone-deployments/docs.md
=> fix mender-standalone download link

200.APIs/01.Overview/docs.md
Signed-off-by: Maciej Mrowiec <mrowiec.maciej@gmail.com>
=> Add versioning section to API overview

06.Administration/02.Production-installation/docs.md
Issues: MEN-946
Signed-off-by: mchalczynski <marcin.chalczynski@rndity.com>
goes with https://github.com/mendersoftware/integration/pull/185
@mendersoftware/rndity @maciejmrowiec
=> production install: notes on Docker's log rotation

201.Troubleshooting/01.Yocto-project-build/docs.md
=> Add troubleshooting entry for running out of FS blocks during build.

01.Getting-started/01.What-is-Mender/docs.md, 01.Getting-started/02.Create-a-test-environment/docs.md, 01.Getting-started/03.Deploy-to-virtual-devices/docs.md, 01.Getting-started/04.Deploy-to-physical-devices/docs.md, 01.Getting-started/05.Standalone-deployments/docs.md, 02.Architecture/01.Overview/docs.md, 02.Architecture/02.Mender-Artifacts/docs.md, 03.Devices/01.System-requirements/docs.md, 03.Devices/02.Partition-layout/docs.md, 03.Devices/03.Integrating-with-U-Boot/01.Providing-custom-u-boot-fw-utils/docs.md, 03.Devices/03.Integrating-with-U-Boot/docs.md, 04.Artifacts/01.Building-Mender-Yocto-image/docs.md, 04.Artifacts/02.Image-configuration/docs.md, 04.Artifacts/03.Provisioning-a-new-device/docs.md, 04.Artifacts/04.Modifying-a-disk-image/docs.md, 04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md, 04.Artifacts/06.Building-for-production/docs.md, 04.Artifacts/07.Variables/docs.md, 05.Client-configuration/01.Overview/docs.md, 05.Client-configuration/03.Inventory/docs.md, 05.Client-configuration/04.Polling-intervals/docs.md, 06.Administration/01.Overview/docs.md, 06.Administration/02.Production-installation/docs.md, 06.Administration/03.Certificates-and-keys/docs.md, 201.Troubleshooting/01.Yocto-project-build/docs.md, 201.Troubleshooting/03.Mender-cli/docs.md, 201.Troubleshooting/04.Mender-Server/docs.md
=> Use lowercase as standard for urls

01.Getting-started/02.Create-a-test-environment/docs.md, 01.Getting-started/03.Deploy-to-virtual-devices/docs.md, 01.Getting-started/04.Deploy-to-physical-devices/docs.md, 01.Getting-started/05.Standalone-deployments/docs.md, 02.Architecture/01.Overview/docs.md, 02.Architecture/02.Mender-Artifacts/docs.md, 03.Devices/01.System-requirements/docs.md, 03.Devices/02.Partition-layout/docs.md, 03.Devices/03.Integrating-with-U-Boot/01.Providing-custom-u-boot-fw-utils/docs.md, 03.Devices/03.Integrating-with-U-Boot/docs.md, 04.Artifacts/01.Building-Mender-Yocto-image/docs.md, 04.Artifacts/02.Image-configuration/docs.md, 04.Artifacts/03.Provisioning-a-new-device/docs.md, 04.Artifacts/04.Modifying-a-disk-image/docs.md, 04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md, 04.Artifacts/06.Building-for-production/docs.md, 04.Artifacts/07.Variables/docs.md, 05.Client-configuration/01.Overview/docs.md, 05.Client-configuration/04.Polling-intervals/docs.md, 06.Administration/01.Overview/docs.md, 06.Administration/02.Production-installation/docs.md, 06.Administration/03.Certificates-and-keys/docs.md, 201.Troubleshooting/01.Yocto-project-build/docs.md, 201.Troubleshooting/03.Mender-cli/docs.md, 201.Troubleshooting/04.Mender-Server/docs.md
(cherry picked from commit 798c6de27769ade665f561342a51622d0df4a210)
=> Use lowercase as standard for urls (#128)

01.Getting-started/02.Create-a-test-environment/docs.md, 03.Devices/01.System-requirements/docs.md, 04.Artifacts/01.Building-Mender-Yocto-image/docs.md, 201.Troubleshooting/01.Yocto-project-build/docs.md, 201.Troubleshooting/03.Mender-Client/docs.md, 201.Troubleshooting/04.Mender-Server/docs.md
=> Use lowercase for internal urls

04.Artifacts/01.Building-Mender-Yocto-image/docs.md, 201.Troubleshooting/01.Yocto-project-build/docs.md, 201.Troubleshooting/03.Mender-Client/docs.md, 201.Troubleshooting/04.Mender-Server/docs.md
(cherry picked from commit c3e866df397c4df20f9d954ebb5ba62942a60f3e)
=> Use lowercase for internal urls (#130)

04.Artifacts/01.Building-Mender-Yocto-image/docs.md
=> Fix markdown and link lowercase

04.Artifacts/06.Building-for-production/docs.md
=> Fix link to lowercase

06.Administration/02.Production-installation/docs.md
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>
=> minio limits passwords to 20 characters

06.Administration/06.Upgrading/docs.md
@mendersoftware/rndity @kacf @maciejmrowiec @pasinskim @GregorioDiStefano 
BTW. no clue if there's anything needed from client side. Feel free to open a separate PR with client related bits.
=> administration/upgrading: upgrade guide

04.Artifacts/07.Variables/docs.md
=> Add documentation for boot loader variables.

202.Release-information/01.Open-source-licenses/docs.md
Should be cherry-picked to 1.0.x as well.
=> Update license overview for 1.0.1.

01.Getting-started/02.Create-a-test-environment/docs.md
=> Remove warning about Docker version check

01.Getting-started/05.Standalone-deployments/docs.md
=> Corrected link for standalone tar.gz

04.Artifacts/07.Variables/docs.md
=> Document MENDER_ARTIFACT_SIGNING_KEY variable.

04.Artifacts/07.Variables/docs.md
=> Add docs for MENDER_ARTIFACT_VERIFY_KEY.

04.Artifacts/07.Variables/docs.md
Signed-off-by: Michael Clelland <michael.clelland@cfengine.com>
=> Fixed link

202.Release-information/02.Open-source-licenses/docs.md
=> Update license overview for 1.1.x.

202.Release-information/01.Release-notes-changelog/docs.md
=> Update changelog for 1.1.x.

200.APIs/03.Management-APIs/02.Device-authentication/docs.md
(cherry picked from commit 50287f982f7babbc589f29e6acf6863f40ab45b2)
=> Add placeholder for device auth API

03.Devices/02.Partition-layout/docs.md
Signed-off-by: Drew Moseley <drew.moseley@mender.io>
=> Add docs for deploying files to the persistent data partition

03.Devices/02.Partition-layout/docs.md
=> Mention UBI support as an experimental feature.

04.Artifacts/99.Variables/docs.md
=> Reorder variable entry alphabetically.

06.Administration/06.Upgrading/docs.md, 06.Administration/07.Backup-and-restore/docs.md
Signed-off-by: Drew Moseley <drew.moseley@mender.io>
Related to https://github.com/mendersoftware/mender-docs/pull/164
=> admistration/{upgrading, backup-and-restore}: Cleanup wording

202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelog for Mender 1.1.0.

01.Getting-started/04.Deploy-to-physical-devices/docs.md, 04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md, 04.Artifacts/06.Signing-and-verification/docs.md
=> MEN-1236: Fix mender-artifact download from new bucket.

chapter.md
=> Removed “beta” from title

01.Getting-started/02.Create-a-test-environment/docs.md
=> Move user create command to single line

202.Release-information/02.Open-source-licenses/docs.md
=> Update copyright to Northern.tech and current year.

04.Artifacts/01.Building-Mender-Yocto-image/docs.md, 04.Artifacts/02.Image-configuration/docs.md
Signed-off-by: Drew Moseley <drew.moseley@mender.io>
=> Update references to local.conf for consistency

01.Getting-started/04.Deploy-to-physical-devices/docs.md
Signed-off-by: Drew Moseley <drew.moseley@mender.io>
=> Fix additional filename references to include version suffix.

04.Artifacts/99.Variables/docs.md
=> MEN-1072: Documented the tenant-token variable usage.

04.Artifacts/99.Variables/docs.md
=> Fix punctuation in MENDER_TENANT_TOKEN docs

04.Artifacts/07.Building-for-production/docs.md, 04.Artifacts/99.Variables/docs.md
Just a few things I thought needed cleaning up while working on a production server environment here.
=> Update server url docs

202.Release-information/02.Open-source-licenses/docs.md
=> Update license information for 1.2.x.

01.Getting-started/02.Create-a-test-environment/docs.md, 01.Getting-started/03.Deploy-to-virtual-devices/docs.md, 01.Getting-started/04.Deploy-to-physical-devices/docs.md, 06.Administration/02.Production-installation/docs.md
=> localhost no longer works as https target due to nginx ALLOWED_HOSTS.

03.Devices/02.Partition-layout/docs.md, 03.Devices/04.Integration-checklist/docs.md, 03.Devices/05.Raw-flash/docs.md
=> devices/raw-flash: documentation for raw flash support

202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelog for 1.2.0b1.

01.Getting-started/02.Create-a-test-environment/docs.md, 01.Getting-started/03.Deploy-to-virtual-devices/docs.md, 01.Getting-started/04.Deploy-to-physical-devices/docs.md, 01.Getting-started/05.Standalone-deployments/docs.md, 02.Architecture/02.Mender-Artifacts/docs.md, 04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md, 04.Artifacts/06.Signing-and-verification/docs.md, 05.Client-configuration/02.Identity/docs.md, 06.Administration/02.Production-installation/docs.md
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>
=> Creating 1.2.x branch, changing related links

02.Architecture/02.Mender-Artifacts/docs.md, 06.Administration/02.Production-installation/docs.md
Issues: MEN-1347
Changelog: title
=> production-install: Update instructions for creating initial user.

chapter.md
=> Rename title to 1.2 beta

chapter.md
=> Update 1.2. chapter text

06.Administration/02.Production-installation/docs.md
=> production-install: Cleanup command output for adding new users.

01.Getting-started/02.Create-a-test-environment/docs.md, 01.Getting-started/03.Deploy-to-virtual-devices/docs.md, 01.Getting-started/04.Deploy-to-physical-devices/docs.md
after https://github.com/mendersoftware/integration/pull/322
=> Use https://localhost to access demo environment, it is allowed

202.Release-information/02.Open-source-licenses/docs.md
=> Update license information for 1.2.0.

202.Release-information/02.Open-source-licenses/docs.md
=> Update license information for 1.1.1.

chapter.md
=> Amend chapter title text

chapter.md
=> Amend chapter title

chapter.md
=> Updated chapter title from beta to stable

chapter.md
=> Remove “beta” from title

01.Getting-started/02.Create-a-test-environment/docs.md, 01.Getting-started/03.Deploy-to-virtual-devices/docs.md, 01.Getting-started/04.Deploy-to-physical-devices/docs.md, 01.Getting-started/05.Standalone-deployments/docs.md, 04.Artifacts/01.Building-Mender-Yocto-image/docs.md, 04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md, 04.Artifacts/06.Signing-and-verification/docs.md
=> Update version references for 1.1.1.

01.Getting-started/02.Create-a-test-environment/docs.md, 01.Getting-started/03.Deploy-to-virtual-devices/docs.md, 01.Getting-started/04.Deploy-to-physical-devices/docs.md, 01.Getting-started/05.Standalone-deployments/docs.md, 04.Artifacts/01.Building-Mender-Yocto-image/docs.md, 04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md, 04.Artifacts/06.Signing-and-verification/docs.md, 06.Administration/06.Upgrading/docs.md
=> Update version references for 1.2.0

04.Artifacts/01.Building-Mender-Yocto-image/docs.md
=> Do not set PREFERRED_VERSION variables by default in latest branch.

04.Artifacts/01.Building-Mender-Yocto-image/docs.md
=> Use wildcard for PREFERRED_VERSION settings

04.Artifacts/07.State-scripts/docs.md
Most notably
* Split out use cases
* Simplified transitions and ordering pieces
* Split out most common state transitions (they were one very very long line)
* Uppercase Artifact and Mender Client
=> improved readability of state script docs

04.Artifacts/07.State-scripts/docs.md
=> adjust states for network connectivity

202.Release-information/01.Release-notes-changelog/docs.md
=> Update changelog 1.1.1.

202.Release-information/01.Release-notes-changelog/docs.md
Output is slightly different due to updated generator tool.
=> Update changelog for 1.2.0.

202.Release-information/01.Release-notes-changelog/docs.md
Signed-off-by: Eystein Måløy Stenberg <eystein@mender.io>
=> 1.2.0 release date

202.Release-information/01.Release-notes-changelog/docs.md
Signed-off-by: Eystein Måløy Stenberg <eystein.maloy.stenberg@cfengine.com>
=> release date 1.1.1

03.Devices/02.Partition-layout/docs.md
=> Removed extra space

03.Devices/chapter.md, 04.Artifacts/chapter.md
=> Correct chapter title numbers

.ispell_english
=> Update spelling to accept northerntech

.ispell_english, 04.Artifacts/07.State-scripts/docs.md, 202.Release-information/01.Release-notes-changelog/docs.md
=> Spell check update

01.Getting-started/02.Create-a-test-environment/docs.md, 06.Administration/02.Production-installation/docs.md
=> Use wrapper scripts to create default user.

03.Devices/03.Integrating-with-U-Boot/docs.md, 03.Devices/04.Integration-checklist/docs.md, 04.Artifacts/02.Image-configuration/01.Features/docs.md, 04.Artifacts/02.Image-configuration/docs.md, 04.Artifacts/99.Variables/docs.md
=> MEN-595: Document new MENDER_FEATURES_ENABLE|DISABLE variables.

202.Release-information/01.Release-notes-changelog/docs.md
=> Update changelog for 1.2.1.

202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelogs for 1.1.2 and 1.1.3.

01.Getting-started/03.Deploy-to-virtual-devices/docs.md, 01.Getting-started/04.Deploy-to-physical-devices/docs.md, 01.Getting-started/05.Standalone-deployments/docs.md, 04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md, 04.Artifacts/06.Signing-and-verification/docs.md
The autoupdate tags will be used later to auto-update the links.
=> Update download links for Mender 1.1.3.

01.Getting-started/03.Deploy-to-virtual-devices/docs.md, 01.Getting-started/04.Deploy-to-physical-devices/docs.md, 01.Getting-started/05.Standalone-deployments/docs.md, 04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md, 04.Artifacts/06.Signing-and-verification/docs.md
The autoupdate tags will be used later to auto-update the links.
=> Update download links for Mender 1.2.1.

01.Getting-started/03.Deploy-to-virtual-devices/docs.md, 01.Getting-started/04.Deploy-to-physical-devices/docs.md, 01.Getting-started/05.Standalone-deployments/docs.md, 04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md, 04.Artifacts/06.Signing-and-verification/docs.md
The autoupdate tags will be used later to auto-update the links.
=> Update download links for Mender master (Development).

01.Getting-started/02.Create-a-test-environment/docs.md, 01.Getting-started/03.Deploy-to-virtual-devices/docs.md, 01.Getting-started/04.Deploy-to-physical-devices/docs.md, 06.Administration/02.Production-installation/docs.md
Also add some tags that we plan to use later for auto-updating.
=> Update version references for Mender 1.1.3.

01.Getting-started/02.Create-a-test-environment/docs.md, 01.Getting-started/03.Deploy-to-virtual-devices/docs.md, 01.Getting-started/04.Deploy-to-physical-devices/docs.md, 06.Administration/02.Production-installation/docs.md
Also add some tags that we plan to use later for auto-updating.
=> Update version references for Mender 1.2.1.

01.Getting-started/02.Create-a-test-environment/docs.md, 01.Getting-started/03.Deploy-to-virtual-devices/docs.md, 01.Getting-started/04.Deploy-to-physical-devices/docs.md, 06.Administration/02.Production-installation/docs.md
Also add some tags that we plan to use later for auto-updating.
=> Update version references for Mender master (Development).

04.Artifacts/08.Building-for-production/docs.md, 06.Administration/03.Certificates-and-keys/docs.md
=> Document that client certificate is only needed for self signed certs.

06.Administration/02.Production-installation/docs.md
Issues: MEN-1514
Signed-off-by: Piotr Przybylak <piotr.przybylak@rndity.com>
=> Document setting (via config) the limit of maximum devices (deviceauth)

.ispell_english, 02.Architecture/01.Overview/docs.md, 02.Architecture/02.Compatibility/docs.md, 05.Client-configuration/04.Configuration-file/docs.md, 06.Administration/02.Production-installation/docs.md, spell-check.sh
@PiotrPrzybylak please specific review https://github.com/mendersoftware/mender-docs/commit/5488182244c44377c3535085a0b123d7c68be5a5 as you submitted the initial change.
=> Spelling updates and rewording

04.Artifacts/01.Building-Mender-Yocto-image/docs.md
=> Clarify the need to add the beaglebone BSP layer.

02.Architecture/02.Compatibility/docs.md
=> Clarify API version versus Artifact format version compatibility

04.Artifacts/99.Variables/docs.md
=> Fixed typo

01.Getting-started/01.Requirements/docs.md, 01.Getting-started/03.Deploy-to-virtual-devices/docs.md
=> Do not use sudo to run docker

.ispell_english, 02.Architecture/04.Standalone-deployments/docs.md
=> Spelling updates

chapter.md
=> Put tags in chapter.md for later autoupdating.

06.Administration/02.Production-installation/docs.md
=> Specify remote name with git log command.

01.Getting-started/02.Create-a-test-environment/docs.md, 06.Administration/02.Production-installation/docs.md
=> 1.2.2 update

06.Administration/02.Production-installation/docs.md
=> Use fully qualified branch for git log command.

04.Artifacts/01.Building-Mender-Yocto-image/docs.md
@drewmoseley @kacf @GregorioDiStefano please review.
I will backport to 1.3.x and 1.2.x once approved.
=> building for Raspberry Pi reference device

03.Devices/01.System-requirements/docs.md, 03.Devices/03.Integrating-with-U-Boot/01.Manual-U-Boot-integration/01.Providing-custom-u-boot-fw-utils/docs.md, 03.Devices/03.Integrating-with-U-Boot/01.Manual-U-Boot-integration/02.U-Boot-versions-without-BOOTLIMIT-support/docs.md, 03.Devices/03.Integrating-with-U-Boot/01.Manual-U-Boot-integration/docs.md, 03.Devices/03.Integrating-with-U-Boot/docs.md, 03.Devices/05.Raw-flash/docs.md, 04.Artifacts/01.Building-Mender-Yocto-image/docs.md, 201.Troubleshooting/01.Yocto-project-build/docs.md
=> MEN-1387: Document automatic U-Boot patching.

01.Getting-started/02.Create-a-test-environment/docs.md, 06.Administration/02.Production-installation/docs.md
=> Update URL for Docker Engine installation

06.Administration/02.Production-installation/docs.md
=> Update link for Docker Volumes tutorial

.ispell_english
=> 1.0.x spelling updates

01.Getting-started/04.Deploy-to-physical-devices/docs.md
=> Added header for "Disk image and Artifacts"

01.Getting-started/05.Download-test-images/docs.md
=> Alter test image download page after recent changes to help+tooltips

06.Administration/02.Production-installation/docs.md, 06.Administration/07.Backup-and-restore/docs.md
goes with: https://github.com/mendersoftware/integration/pull/429
@mendersoftware/rndity @maciejmrowiec
=> migrate from dynomite to redis 

04.Artifacts/07.State-scripts/docs.md
=> Document that removed state scripts recipes need to be cleaned up.

04.Artifacts/07.State-scripts/docs.md
=> Spontanaeous reboot hardening documentation

04.Artifacts/01.Building-Mender-Yocto-image/docs.md
Signed-off-by: Gregorio Di Stefano <greg.distefano+github@gmail.com>
=> bump version in hosted mender from 1.3.0 to 1.3.1

201.Troubleshooting/02.Running-Yocto-Project-image/docs.md
=> Document noisy serial console workarounds

04.Artifacts/07.State-scripts/docs.md
=> MEN-1503: state script logging documentation

01.Getting-started/02.Create-a-test-environment/docs.md
Signed-off-by: Gregorio Di Stefano <greg.distefano+github@gmail.com>
=> add cloudfront cdn link to integration tarball

.ispell_english, 202.Release-information/01.Release-notes-changelog/docs.md
=> 1.4.x Spelling updates

.ispell_english
=> 1.3.x Spelling updates

.ispell_english
=> 1.2.x Spelling updates

.ispell_english, 04.Artifacts/07.State-scripts/docs.md, 202.Release-information/01.Release-notes-changelog/docs.md
=> master Spelling updates

01.Getting-started/02.Create-a-test-environment/docs.md
Signed-off-by: Gregorio Di Stefano <greg.distefano+github@gmail.com>
=> set integration.tar.gz to cloudfront url

03.Devices/03.Integrating-with-U-Boot/01.Manual-U-Boot-integration/02.U-Boot-versions-without-BOOTLIMIT-support/docs.md
=> Correct the URL for the manual UBoot integration patch

01.Getting-started/04.Deploy-to-physical-devices/docs.md, 04.Artifacts/04.Modifying-a-disk-image/docs.md
Signed-off-by: Auke Oosterhoff <auke@orangetux.nl>
=> Fix typo's

01.Getting-started/02.Create-a-test-environment/docs.md
Signed-off-by: Ole Petter <olepor@matnat.uio.no>
=> Replaced wget with git clone in getting-started doc.

04.Artifacts/99.Variables/docs.md
=> Add documentation for MENDER_KERNEL_IMAGETYPE_FORCE

01.Getting-started/04.Deploy-to-physical-devices/docs.md
=> Update artifact names for 1.4.0 release

01.Getting-started/04.Deploy-to-physical-devices/docs.md
=> Specify proper command line parameter for tar

.ispell_english, 01.Getting-started/04.Deploy-to-physical-devices/docs.md, 01.Getting-started/05.Download-test-images/docs.md, 03.Devices/01.System-requirements/docs.md, 04.Artifacts/01.Building-Mender-Yocto-image/docs.md, 201.Troubleshooting/04.Mender-Server/docs.md
=> Add qemux86-64 and make it the default reference.

202.Release-information/02.Open-source-licenses/docs.md
=> Update open source licenses for Mender 1.5.

01.Getting-started/05.Download-test-images/docs.md, 202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelog for Mender 1.5.0b1.

01.Getting-started/02.Create-a-test-environment/docs.md, 01.Getting-started/04.Deploy-to-physical-devices/docs.md, 01.Getting-started/05.Download-test-images/docs.md, 02.Architecture/04.Mender-Artifacts/docs.md, 03.Devices/03.Integrating-with-U-Boot/01.Manual-U-Boot-integration/02.U-Boot-versions-without-BOOTLIMIT-support/docs.md, 04.Artifacts/01.Building-Mender-Yocto-image/docs.md, 04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md, 04.Artifacts/06.Signing-and-verification/docs.md, 04.Artifacts/07.State-scripts/docs.md, 05.Client-configuration/02.Identity/docs.md, 06.Administration/02.Production-installation/docs.md, 202.Release-information/01.Release-notes-changelog/docs.md, 202.Release-information/02.Open-source-licenses/docs.md, chapter.md
=> Update links for Mender 1.5.0b1.

03.Devices/01.System-requirements/docs.md, 03.Devices/02.Partition-layout/docs.md, 03.Devices/03.Integrating-with-U-Boot/02.Integration-checklist/docs.md, 03.Devices/03.Integrating-with-U-Boot/docs.md, 03.Devices/04.Integrating-with-GRUB/docs.md, 03.Devices/Integration-checklist/docs.md, 04.Artifacts/01.Building-Mender-Yocto-image/docs.md, 04.Artifacts/02.Image-configuration/01.Features/docs.md, 04.Artifacts/99.Variables/docs.md
=> MEN-1877: Add documentation for GRUB and x86 support.

03.Devices/03.Integrating-with-U-Boot/02.Integration-checklist/docs.md
=> Update relative link to raw-flash one directory higher

202.Release-information/02.Open-source-licenses/docs.md
=> Update license information for Mender 1.5.0.

202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelog for meta-mender/rocko-v2018.06

chapter.md
=> Update chapter header

05.Client-configuration/04.Configuration-file/docs.md
=> Fix bitbake variable assignment requiring :=

01.Getting-started/04.Deploy-to-physical-devices/docs.md
=> MEN-1805: Setting wifi ssid and password in an image

03.Devices/05.Raw-flash/01.Example-QEMU/docs.md, 03.Devices/05.Raw-flash/docs.md, 04.Artifacts/99.Variables/docs.md, 201.Troubleshooting/01.Yocto-project-build/docs.md
Do not merge yet. I need to document variables first.
=> Documentation for Flash auto-patching

04.Artifacts/99.Variables/docs.md
=> Document MENDER_PRE_SETUP_COMMANDS and MENDER_POST_SETUP_COMMANDS

202.Release-information/01.Release-notes-changelog/docs.md
=> Update changelog for meta-mender rocko-v2018.07.

201.Troubleshooting/01.Yocto-project-build/docs.md
=> Add troubleshooting section for "fw_printenv -l" bug.

07.Administration/02.Production-installation/docs.md, 07.Administration/06.Upgrading/docs.md, 07.Administration/07.Backup-and-restore/docs.md, 201.Troubleshooting/04.Mender-Server/docs.md
Issues: https://tracker.mender.io/browse/MEN-1958
=> Documentation describing migration to single mongoDB instance

202.Release-information/01.Release-notes-changelog/docs.md
=> Add first changelog entry for sumo branch.

04.Artifacts/99.Variables/docs.md
=> variables: update MENDER_DATA_PART_DIR info to match function

.ispell_english, 06.Server-integration/01.Using-the-apis/docs.md
=> Spelling fixes

04.Artifacts/07.State-scripts/docs.md
=> FIX: Reboot hardening turned off for Reboot_Enter

02.Architecture/03.Compatibility/docs.md
=> Update compatibility tables

202.Release-information/02.Open-source-licenses/docs.md
=> Add license info for 1.6.0b1.

01.Getting-started/04.Deploy-to-physical-devices/docs.md, 02.Architecture/03.Compatibility/docs.md, 04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md, 04.Artifacts/06.Signing-and-verification/docs.md, 04.Artifacts/99.Variables/docs.md, 05.Client-configuration/04.Configuration-file/01.Polling-intervals/docs.md, 07.Administration/06.Upgrading/docs.md, 201.Troubleshooting/03.Mender-Client/docs.md
Signed-off-by: Eystein Måløy Stenberg <eystein@mender.io>
=> remove extract of mender artifact, not needed

.ispell_english, 04.Artifacts/07.State-scripts/docs.md, 07.Administration/03.Certificates-and-keys/docs.md
=> Add some clarifying text regarding CA versus self-signed certificates

03.Devices/04.Integrating-with-U-Boot/docs.md
=> Add clarification regarding U-Boot versions and auto-patching

README.markdown, README.md
Also renamed the file from README.markdown to README.md for consistency
=> add README content

01.Getting-started/04.Deploy-to-physical-devices/docs.md, 201.Troubleshooting/03.Mender-Client/docs.md, 201.Troubleshooting/05.Device-Runtime/docs.md
=> Added board bringup troubleshooting.

202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelog for 1.6.0.

202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelog for 1.5.1.

202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelog for meta-mender sumo-v2018.09.

chapter.md
This needs to be reverted later, as part of fixing MEN-2125.
=> MEN-2125: Temporarily fix rendering by removing AUTOVERSION tag.

04.Artifacts/01.Building-Mender-Yocto-image/docs.md
=> Clarify systemd settings per Yocto release.

01.Getting-started/04.Deploy-to-physical-devices/docs.md, 03.Devices/01.System-requirements/01.Yocto/01.Bootloader-support/docs.md, 03.Devices/01.System-requirements/docs.md, 03.Devices/02.Partition-layout/01.Yocto/docs.md, 03.Devices/04.Integrating-with-U-Boot/01.Yocto/01.Manual-U-Boot-integration/01.Providing-custom-u-boot-fw-utils/docs.md, 03.Devices/04.Integrating-with-U-Boot/01.Yocto/02.Integration-checklist/docs.md, 04.Artifacts/01.Building-Mender-image/01.Building-Yocto-image/docs.md, 04.Artifacts/03.Provisioning-a-new-device/docs.md, 04.Artifacts/99.Variables/docs.md, 06.Server-integration/02.Preauthorizing-devices/docs.md, 201.Troubleshooting/01.Yocto-project-build/docs.md
=> Fix broken links after docs restructure

01.Getting-started/04.Deploy-to-physical-devices/docs.md, 03.Devices/02.Partition-layout/01.Yocto/docs.md, 03.Devices/04.Integrating-with-U-Boot/01.Yocto/01.Manual-U-Boot-integration/docs.md, 03.Devices/04.Integrating-with-U-Boot/01.Yocto/docs.md, 04.Artifacts/01.Building-Mender-image/01.Building-Yocto-image/docs.md, 04.Artifacts/99.Variables/docs.md, 201.Troubleshooting/01.Yocto-project-build/docs.md
=> More link fixes after docs pages were moved around

04.Artifacts/06.Signing-and-verification/docs.md
=> Use validate subcommand for signature check.

04.Artifacts/01.Building-Mender-image/01.Building-Yocto-image/docs.md
=> Fix broken link

01.Getting-started/04.Deploy-to-physical-devices/docs.md, 02.Architecture/01.Overview/docs.md, 02.Architecture/03.Compatibility/docs.md, 03.Devices/01.General-system-requirements/docs.md, 03.Devices/02.Yocto-project/02.Bootloader-support/02.U-Boot/docs.md, 03.Devices/02.Yocto-project/03.Raw-flash/docs.md, 04.Artifacts/01.Yocto-project/99.Variables/docs.md, 04.Artifacts/06.Signing-and-verification/docs.md, 05.Client-configuration/02.Cross-compiling/docs.md, 07.Administration/03.Certificates-and-keys/docs.md, 201.Troubleshooting/01.Yocto-project-build/docs.md, 201.Troubleshooting/03.Mender-Client/docs.md
=> Add AUTOVERSION support to cross-compiling docs

01.Getting-started/05.Download-test-images/docs.md, 02.Architecture/05.Standalone-deployments/docs.md, 03.Devices/02.Yocto-project/01.Partition-layout/docs.md, 04.Artifacts/01.Yocto-project/99.Variables/docs.md, 04.Artifacts/06.Signing-and-verification/docs.md, 201.Troubleshooting/01.Yocto-project-build/docs.md
=> Fix more busted links from recent menu heirarchy change

04.Artifacts/06.Signing-and-verification/docs.md
=> Add warning to ensure artifact name matches mender.conf

03.Devices/03.Debian-family/01.Partition-layout/docs.md, 03.Devices/03.Debian-family/02.Bootloader-support/01.GRUB/docs.md, 03.Devices/03.Debian-family/02.Bootloader-support/02.U-Boot/docs.md, 03.Devices/03.Debian-family/02.Bootloader-support/docs.md, 04.Artifacts/02.Debian-family/docs.md
Options and as well as parameters' names have also been renamed.
Issues: MEN-2164
Signed-off-by: Adam Podogrocki <a.podogrocki@gmail.com>
=> Conversion tool renamed to mender-convert

04.Artifacts/02.Debian-family/docs.md
Added detailed information about requirements for mender-convert tool.
Signed-off-by: Dominik Adamski <adamski.dominik@gmail.com>
=> Updated dependency list for mender-convert tool

03.Devices/01.System-requirements/docs.md, 03.Devices/chapter.md, 04.Artifacts/01.Building-Mender-Yocto-image/docs.md
=> Mender hub references for 1.6.x

202.Release-information/02.Open-source-licenses/docs.md
Signed-off-by: Marcin Pasinski <marcin.pasinski@northern.tech>
=> Update open source licenses for 1.7.0b1.

02.Architecture/03.Compatibility/docs.md
Signed-off-by: Marcin Pasinski <marcin.pasinski@northern.tech>
(cherry picked from commit 1467945d081aaff3993f1ffa6e304449e99771d1)
=> Update compatibility tables for Mender 1.7.x.

202.Release-information/01.Release-notes-changelog/docs.md
Signed-off-by: Marcin Pasinski <marcin.pasinski@northern.tech>
(cherry picked from commit 35378c7f9e4f7cdf511d3b4b491c0a9eaa2f1dd7)
=> Add changelog for Mender 1.7.0b1

01.Getting-started/04.Deploy-to-physical-devices/docs.md
=> Fix instructions for wpa-supplicant on Rpi.

01.Getting-started/04.Deploy-to-physical-devices/docs.md
=> Make the artifact modification easier to follow by predefining vars.

04.Artifacts/07.State-scripts/docs.md
=> Add note about download link expire time in state script examples

02.Architecture/02.Device-authentication/docs.md
=> Remove Device admission link

06.Server-integration/02.Preauthorizing-devices/docs.md
=> MEN-2033: Update preauth-docs with the mender-artifact install option.

02.Architecture/02.Device-authentication/docs.md
=> Remove link to admission API

02.Architecture/02.Device-authentication/docs.md
(cherry picked from commit 7f25e807b72b566f1a39e4aedeb8847d6ae9f0aa)
=> Remove lnk to admission API

04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md
=> MEN-2224: Document the mender-artifact's no compression option.

04.Artifacts/01.Yocto-project/03.Building-for-production/docs.md
Signed-off-by: Robert Berger <robert.berger@ReliableEmbeddedSystems.com>
=> maybe different path to remove meta-mender-demo

01.Getting-started/04.Deploy-to-physical-devices/docs.md
Signed-off-by: Ajith P V <ajithpv@outlook.com>
=> Update Mender artifact server IP command

04.Artifacts/01.Yocto-project/03.Building-for-production/docs.md
It makes sense to me to mention it in the our "building for production" section.
=> add polling intervals to "build for production section"

01.Getting-started/04.Deploy-to-physical-devices/docs.md, 04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md, 04.Artifacts/06.Signing-and-verification/docs.md
=> MEN-2336: mender-artifact modify only works if payload is an ext4 image

202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelog for thud-v2019.02.

04.Artifacts/01.Yocto-project/99.Variables/docs.md
- MEN-2333
Signed-off-by: Dell Green <dell.green@ideaworks.co.uk>
=> Updated yocto variables docs to include ARTIFACTIMG_NAME

01.Getting-started/04.Deploy-to-physical-devices/docs.md, README.markdown
=> Update mailing list links to Mender Hub links

04.Artifacts/01.Yocto-project/99.Variables/docs.md
- ISSUE: * #MEN-2361
Signed-off-by: Dell Green <dell.green@ideaworks.co.uk>
=> Added optional mender swap partition variable

03.Devices/02.Yocto-project/02.Bootloader-support/02.U-Boot/02.Integration-checklist/docs.md
=> Clarify and fixup kpartx invocation.

05.Client-configuration/05.Configuration-file/50.Configuration-options/docs.md
=> Add missing docs for InventoryPollIntervalSeconds.

04.Artifacts/01.Yocto-project/99.Variables/docs.md, autoversion.py
=> Add a few future poky branches to autoversion checker.

201.Troubleshooting/02.Running-Yocto-Project-image/docs.md
=> Add Troubleshooting section for the thud partition size optimization.

04.Artifacts/07.State-scripts/docs.md, 05.Client-configuration/05.Configuration-file/50.Configuration-options/docs.md
=> Document the swapping of StateScriptRetry configuration values

.ispell_english, 04.Artifacts/08.Update-Modules/docs.md, 05.Client-configuration/06.Installing/docs.md
=> MEN-2400: Document installation of Mender client from deb

04.Artifacts/08.Update-Modules/docs.md, 05.Client-configuration/06.Installing/docs.md
As the file is not present in master, we cannot use AUTOREVISION atm; we
will fix it after the final merge into master.
=> MEN-2391 update modules spec link

.ispell_english, 02.Architecture/04.Mender-Artifacts/docs.md, 03.Devices/01.General-system-requirements/docs.md, 04.Artifacts/01.Yocto-project/99.Variables/docs.md, 04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md
=> Document LZMA support and dependency

05.Client-configuration/06.Installing/docs.md
=> Update Installing documentation to mention the support for ARMv6

05.Client-configuration/06.Installing/docs.md
=> Update cloudfront download link for the deb package

04.Artifacts/01.Yocto-project/01.Building/docs.md
=> Cleanup Yocto instructions in formal docs to reference Mender Hub.

01.Getting-started/02.Create-a-test-environment/docs.md, 07.Administration/02.Production-installation/docs.md
=> MEN-2408: Remove the sudo call for Docker related commands

04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md
=> Update mender-artifact build instruction to add the version string

04.Artifacts/08.Update-Modules/docs.md
Signed-off-by: Mario Kozjak <kozjakm1@gmail.com>
(cherry picked from commit 2bbb7fc3b515c6ee9f1635d0f56927de1d0ce42f)
=> update artifacts/update-modules doc

04.Artifacts/01.Yocto-project/02.Image-configuration/docs.md
The systemd resolve issue has been resolved upstream and should be safe to
remove the suggested patch.
Also added a link to Yocto documentation as "read-only-rootfs" is a Yocto feature
after all.
=> clean-up configuration of read-only rootfs

02.Architecture/01.Overview/docs.md, 02.Architecture/05.Standalone-deployments/docs.md, 201.Troubleshooting/03.Mender-Client/docs.md
=> Fix mender standalone '-install' argument.

201.Troubleshooting/04.Mender-Server/docs.md
https://tracker.mender.io/browse/MEN-2440
changelog: none
Signed-off-by: Marcin Chalczynski <m.chalczynski@gmail.com>
=> 201.Troubleshooting/04.Mender-Server: HSTS issues workaround

03.Devices/Integration-checklist/docs.md
=> Fix Integration checklist redirect link

04.Artifacts/08.Update-Modules/docs.md
=> Switch update module spec link to master, now that it is merged.

201.Troubleshooting/02.Running-Yocto-Project-image/docs.md, 201.Troubleshooting/03.Mender-Client/docs.md
=> add new client troubleshooting section on poor performance in U-boot

201.Troubleshooting/04.Mender-Server/docs.md
=> Add troubleshooting section about ElasticSearch and memory.

202.Release-information/01.Release-notes-changelog/docs.md
Changelogs for releases sumo-v2019.04 and rocko-v2019.04
@drewmoseley @kacf This is my first meta-mender release, so please pay attention to detail. Also, I haven't pushed the tags yet, do you want to review them?
=> Release changelogs meta mender

04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md, 04.Artifacts/06.Signing-and-verification/docs.md
See also [this PR in mender-artifact](https://github.com/mendersoftware/mender-artifact/pull/194)
=> MEN-2486: Unsupport signed modify

201.Troubleshooting/02.Running-Yocto-Project-image/docs.md
Follow up fixes to changes made in #649.
I have now tested this by running the docs site locally :).
=> Fixes to u boot troubleshooting

README.markdown
=> Added author information to README

01.Getting-started/02.Create-a-test-environment/docs.md, 07.Administration/02.Production-installation/docs.md
=> add a note to user creation in demo and on-prem setup

03.Devices/10.Update-Modules/docs.md
=> Fix links from update modules page

202.Release-information/02.Open-source-licenses/docs.md
=> Update license information for 2.0.0.

202.Release-information/02.Open-source-licenses/docs.md
=> Update licenses for 1.7.1.

202.Release-information/01.Release-notes-changelog/docs.md
=> master: mender-convert 1.1.0 release

05.Client-configuration/05.Configuration-file/50.Configuration-options/docs.md
Document [PR 393](https://github.com/mendersoftware/mender/pull/393) from mender client and minor beautification.
=> Document device type configurable

03.Devices/10.Update-Modules/docs.md
It is always better to explicitly mention the meaning of each option(s) provided with mender artifact command.
Added the meaning of provided options for update module example.
Signed-off-by: Ajith P V <ajithpv@outlook.com>
=> Add Command options' meaning

07.Administration/02.Production-installation/docs.md
(cherry picked from commit 7cdab698ae95287b2502d996753829eb5c37e930)
=> 2.0.x cherry pick on-prem reqs

05.Client-configuration/06.Installing/docs.md
=> fix typographical error

05.Client-configuration/06.Installing/docs.md
(cherry picked from commit 40adb4ba8f49f6396299571cce07b68ee77dc080)
=> 2.0.x cherry-pick: fix typographical error

06.Server-integration/02.Preauthorizing-devices/docs.md
=> break down commands to fetch keygen-client script

01.Getting-started/02.Create-a-test-environment/docs.md, 01.Getting-started/06.Maintain-the-test-environment/docs.md
=> Update docs with regards to script unification and new --client argument.

01.Getting-started/02.Create-a-test-environment/docs.md
Changelog: Added documentation for the automatically created demo user.
=> MEN-2433: Automatically upload the demo artifact to the demo server.

202.Release-information/02.Open-source-licenses/docs.md
=> Update licenses information for Mender 2.0.1 release

04.Artifacts/01.Yocto-project/02.Image-configuration/01.Features/docs.md
=> Fix incorrect information about default mender features.

01.Getting-started/02.Create-a-test-environment/docs.md, 01.Getting-started/04.Deploy-to-physical-devices/docs.md, 01.Getting-started/05.Download-test-images/docs.md, 02.Architecture/04.Mender-Artifacts/docs.md, 03.Devices/10.Update-Modules/docs.md, 04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md, 04.Artifacts/06.Signing-and-verification/docs.md, 05.Client-configuration/02.Cross-compiling/docs.md, 05.Client-configuration/03.Identity/docs.md, 05.Client-configuration/06.Installing/docs.md, 06.Server-integration/02.Preauthorizing-devices/docs.md, 07.Administration/02.Production-installation/docs.md, 202.Release-information/01.Release-notes-changelog/docs.md, 202.Release-information/02.Open-source-licenses/docs.md
* Update licenses information for Mender 2.0.1 release (cherry-pick)
* Update Mender version to 2.0.1 release using autoversion script
* Add changelogs for Mender 2.0.1 release
* Add statistics for Mender 2.0.1 release
=> Update for Mender 2.0.1 release

02.Architecture/05.Standalone-deployments/docs.md
=> Fix outdated state script/standalone mode info box.

201.Troubleshooting/01.Yocto-project-build/docs.md
=> Add troubleshooting suggestion for storage size mismatch

202.Release-information/02.Open-source-licenses/docs.md
=> Update license information for Mender 2.1.0b1.

01.Getting-started/02.Create-a-test-environment/docs.md
See: https://github.com/mendersoftware/integration/pull/663
=> Temporary documentation fix because of bug in 2.1.0b1.

201.Troubleshooting/04.Mender-Server/docs.md
=> Updated virtual device troubleshooting for new onboarding

202.Release-information/01.Release-notes-changelog/docs.md
Commits:
- Add statistics and changelog for meta-mender/sumo-v2019.08
- Add statistics and changelog for meta-mender/sumo-v2019.08
=> Doc sumo and rocko v2019.08 releases to master

202.Release-information/01.Release-notes-changelog/docs.md
Porting #740 to 2.0.x
Commits:
- Add statistics and changelog for meta-mender/sumo-v2019.08
- Add statistics and changelog for meta-mender/sumo-v2019.08
=> Doc sumo rocko 08 2019 2.0.x

202.Release-information/01.Release-notes-changelog/docs.md
Porting #740 to 2.1.x
Commits:
- Add statistics and changelog for meta-mender/sumo-v2019.08
- Add statistics and changelog for meta-mender/sumo-v2019.08
=> Doc sumo rocko 08 2019 2.1.x

04.Artifacts/06.Signing-and-verification/docs.md, 05.Client-configuration/02.Cross-compiling/docs.md, 07.Administration/06.Upgrading/docs.md, 201.Troubleshooting/04.Mender-Server/docs.md
=> Update a few version references that have been stale for a while.

06.Server-integration/chapter.md, 07.Administration/chapter.md, 200.APIs/chapter.md, 201.Troubleshooting/chapter.md, 202.Release-information/chapter.md
=> Chapter numbers fix

202.Release-information/02.Open-source-licenses/docs.md
=> Update license information for 2.1.0.

07.Administration/06.Upgrading/docs.md
=> MEN-2782: Clean up old upgrade instructions

03.Devices/02.Yocto-project/01.Partition-configuration/docs.md, 04.Artifacts/01.Yocto-project/02.Image-configuration/01.Features/docs.md
Follow-up on https://github.com/mendersoftware/meta-mender/pull/822
=> Mender growfs data

04.Artifacts/07.State-scripts/docs.md
(cherry picked from commit 3b49dfec3740618b0d5e1ad0b2cab646e59e4497)
=> Fix broken markdown around link address

07.Administration/02.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md, 07.Administration/02.Production-installation/docs.md
=> Switch back to master from MEN-2648 after prolonged feature work.

07.Administration/02.Production-installation/docs.md
=> Fix broken links

07.Administration/02.Production-installation/docs.md
=> Remove reference to tenantadm API until we actually have it.

02.Architecture/03.Compatibility/docs.md
=> Update compatibility table for Mender 2.2.x.

202.Release-information/01.Release-notes-changelog/docs.md
=> Add statistics and changelog for meta-mender warrior-v2019.10 release

07.Administration/02.Production-installation/docs.md
=> Fix instructions which don't include Docker credentials at this time.

07.Administration/02.Production-installation/docs.md
proper branch configuration for https://github.com/mendersoftware/mender-docs/pull/778
=> add instructions for beta users to enable enterprise in GUI

07.Administration/02.Production-installation/docs.md
Simplified prod install instructions.
A bit unsure if the git log changes will make tests fail..
=> Prod enterprise install simplifications

07.Administration/02.Production-installation/docs.md
=> 2.2.x prod enterprise install simplifications

07.Administration/02.Production-installation/docs.md
=> 2.2.x prod enterprise install simplifications2

04.Artifacts/02.Debian-family/docs.md, 202.Release-information/01.Release-notes-changelog/docs.md
=> Update mender-convert version reference.

01.Getting-started/02.On-premise-installation/docs.md
Signed-off-by: Michael <michael.clelland@mender.io>
(cherry picked from commit e50fd13d4344b233c8d022424c27b6d4ca1f4b10)
=> Fix a broken link

04.Artifacts/02.Debian-family/docs.md
=> Adjust link to correct version

202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelog for meta-mender/warrior-v2019.11.

06.Server-integration/01.Using-the-apis/docs.md, 08.Downloads/docs.md
It will go together with https://github.com/mendersoftware/mender-cli/pull/48 and https://github.com/mendersoftware/mender-qa/pull/324
=> MEN-2895: Add mender-cli to downloads page

07.Administration/02.Production-installation/docs.md
and doing it with different commands, integrate it into the doc.
Ref comments by @kacf in https://github.com/mendersoftware/mender-docs/pull/786
=> For production installation, instead of ignoring test automation

202.Release-information/01.Release-notes-changelog/docs.md, 202.Release-information/02.Open-source-licenses/docs.md
Porting the relevant changes of #820 and #821 into master.
For the Open Source licenses, I am porting the most recent one (2.2.1 release).
=> Releases 2.1.1 and 2.2.1 into master docs

202.Release-information/01.Release-notes-changelog/docs.md
=> Release mender binary delta 1.0.1 into 2.2.x docs

autoversion.py
=> Add latest Yocto branches to autoversion regex.

202.Release-information/01.Release-notes-changelog/docs.md
Cherry-picking #826 into 2.2.x
=> Add statistics and changelog for meta-mender warrior-v2019.12 - 2.2.x docs

03.Devices/03.Debian-family/docs.md, 04.Artifacts/02.Debian-family/02.image-configuration/docs.md
=> Fix: Deadlinks in the development documentation

202.Release-information/01.Release-notes-changelog/docs.md
=> Releases thud/sumo v2019.12 - docs 2.2.x

04.Artifacts/02.Debian-family/03.variables/docs.md
=> Add documentation for new variables in mender-convert.

03.Devices/03.Debian-family/docs.md
See: https://northern-tech.slack.com/archives/C0XM0KX9C/p1576612577017000 for details.
=> Update some minor rendering errors in the docs

.gitlab-ci.yml
=> Add Python3 code formatting CI to the repository

autoversion.py, test_autoversion.py, test_docs.py
=> Formatted Python3 code with Black

07.Administration/02.Production-installation/docs.md
We recently added workflows, so the total count of services must be
updated.
=> Adjust expected number of microservices to fix test_docs

.gitlab-ci.yml, pyproject.toml
This entails adding a pyproject.toml in the root project directory, and using
this for filtering which directories and files to keep formatted.
=> [format] Move to the new python formatting implementation

04.Artifacts/01.Yocto-project/99.Variables/docs.md
=> Resubmission of #849

07.Administration/02.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md, 07.Administration/02.Production-installation/docs.md
* services count for production installation tests updated
* services coutn for enterprise upgrade tests updated
ChangeLog:none
=> MEN-3060 update the services counts in tests

07.Administration/02.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md, 07.Administration/02.Production-installation/docs.md
=> Temporarily work around backend bug in 2.3.0b1.

01.Getting-started/02.On-premise-installation/04.Deploy-a-system-update-demo/docs.md
=> Fix wrong device type in command (our image ships with "raspberrypi3")

202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelogs and statistics for meta-mender/warrior-v2020.02.

202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelog for 2.0.0b1 release of mender-convert.

202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelog for meta-mender/warrior-v2020.02.2

03.Devices/03.Debian-family/docs.md
=> Fix link not rendering correctly from markdown

07.Administration/02.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md, 07.Administration/02.Production-installation/docs.md
=> Increase service count after mender-workflows-worker was added.

01.Getting-started/02.On-premise-installation/04.Deploy-a-system-update-demo/docs.md
(cherry picked from commit b7b488bd3fdc48b49a4da3b5d44269f232f2f6e7)
=> Added a note about what to do when the device has no internet

202.Release-information/01.Release-notes-changelog/docs.md, 202.Release-information/02.Open-source-licenses/docs.md
Cherry picking the relevant commits from #898 into master.
=> Release 2.3.0 and mender-convert 2.0.0 into master

07.Administration/02.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md, 07.Administration/02.Production-installation/docs.md, 201.Troubleshooting/01.Yocto-project-build/docs.md
=> Add troubleshooting guide for when U-Boot has known broken UEFI support.

202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelog and stastistics for meta-mender/warrior-v2020.03.

201.Troubleshooting/03.Mender-Client/docs.md
=> Renamed systemd service name from mender -> mender-client

08.Downloads/docs.md
=> Restore the Raspbian version in Downloads table

chapter.md
Add AUTOVERSION complain tag to Development title in cover so that we don't forget again to update this in future releases.
=> Add AUTOVERSION complain tag to Development title in cover

.ispell_english, 02.Architecture/03.Compatibility/docs.md, 04.Artifacts/10.Yocto-project/01.Building/docs.md, 08.Downloads/docs.md
Resubmitting #917 fixing the AUTOVERSION syntax
=> Updates from feedbac resubmit

.ispell_english, 02.Architecture/03.Compatibility/docs.md, 04.Artifacts/10.Yocto-project/01.Building/docs.md, 08.Downloads/docs.md
=> Updates from feedback - 2.3.x

01.Getting-started/02.On-premise-installation/03.Install-the-mender-client/docs.md
=> Rephrase System updadates section in Getting Started > Install client - 2.3.x

04.Artifacts/10.Yocto-project/99.Variables/docs.md, 201.Troubleshooting/01.Yocto-project-build/docs.md
=> Remove deprecated variable MENDER_GRUB_STORAGE_DEVICE

01.Get-started/01.Connect-your-Raspberry-Pi/docs.md
Went through all the text, and did some polishing, along with some simple restructuring.
=> Rewrote and verified the Getting started with Raspberry Pi secition

01.Getting-started/01.Quickstart-with-raspberry-pi/docs.md
Instead of the Mender Professional plan.
=> update quick start page to referece the Mender Starter plan for testing

202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelogs and statistics for meta-mender/warrior-v2020.04.

202.Release-information/01.Release-notes-changelog/docs.md
(cherry picked from commit 4ad723c45c2148fd75a55d4798be6f98967b5105)
=> [2.3.x] Add changelogs and statistics for meta-mender/warrior-v2020.04.

.gitlab-ci.yml, 07.Administration/02.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md, 07.Administration/02.Production-installation/docs.md
=> Fix and beautify pipeline - 2.3.x

.gitlab-ci.yml, 07.Administration/02.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md, 07.Administration/02.Production-installation/docs.md
=> Fix and beautify pipeline - 2.2.x

200.APIs/01.Open-source/02.Management-APIs/03.Device-inventory-v2/docs.md, 200.APIs/02.Enterprise/02.Management-APIs/03.Device-inventory-v2/docs.md, 200.APIs/02.Enterprise/02.Management-APIs/05.Deployments-v2/docs.md
Add the API documentation for the following services:
- inventory (v2)
- inventory-enterprise (v2)
- deployments-enterprise (v2)
=> Add API documentation folders to the Mender docs

01.Getting-started/01.Quickstart-with-raspberry-pi/docs.md
This was missed when cherry-picking, https://github.com/mendersoftware/mender-docs/commit/b8ca6326d9ce49060ecc2b169d6038c0fcbab589
=> update hosted Mender plan reference in quick start

02.Architecture/03.Compatibility/docs.md
=> Clarify some upgrade/downgrade information.

02.Architecture/03.Compatibility/docs.md
=> Remove foot note from column where it makes no sense (2.0 not supported)

202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelog and statistics for meta-mender/warrior-v2020.05.

02.Overview/05.Certificates-and-keys/docs.md
=> MEN-3185: Transfer Certificates and Keys to the new Overview section

02.Overview/03.Identity/docs.md, 02.Overview/chapter.md
https://tracker.mender.io/browse/MEN-3183
besides the obvious `passive->active voice` thing - I addressed some stuff that sounded clunky to me, hope it's more friendly and to the point now. 
bonus: top level chapter.md file - important for navigation.
@estenberg I got a few comments already from different folks - I'd appreciate if you gave them a final ack/nack as well. you have the final word on this I guess, and then I could fix and close all of it in one go.
=> 02.Overview/03.Identity: restructure

02.Overview/04.Inventory/docs.md
Seems like PR #972 was not up to date with documentation-restructuring
branch and therefore did not run the full CI pipeline.
=> Add missing AUTOREV tags from PR #972

06.Server-installation/02.Demo-installation/docs.md
=> MEN-3221 06.Server-installation/02.Demo-installation rewrite

06.Server-installation/04.Bandwidth/docs.md
=> MEN-3223 06.Server-installation/04.Bandwidth/docs.md rewrite

02.Overview/12.Taxonomy/docs.md
=> MEN-3192 02.Overview/12.Taxonomy/docs.md

01.Getting-started/01.Quickstart-with-raspberry-pi/docs.md, 02.Architecture/05.Deployments/docs.md
Issue: https://tracker.mender.io/browse/MEN-3327
=> Architecture/Deployments: describe the way deployments service is selecting deployment for the device

02.Overview/11.Security/docs.md
=> MEN-3191 02.Overview/11.Security/docs.md

04.Artifacts/10.Yocto-project/02.Image-configuration/01.Features/docs.md
=> yocto: features: add documentation for 'mender-partuuid' feature

06.Server-installation/01.Overview/docs.md
Issue: https://tracker.mender.io/browse/MEN-3220
=> introduce Server-installation/Overview section

202.Release-information/01.Release-notes-changelog/docs.md
(cherry picked from commit c15526637431fcc5f0b3e0e2c925077cca266770)
=> Add changelogs and statistics for meta-mender/warrior-v2020.06.

scripts/passive.sh, scripts/weasel.sh
There is currently no CI along with this.
So the scripts are only intended to be run locally on the files as they are written and merged into the new documentation structure.
=> Add the passive voice and weasel word checker scripts

.gitlab-ci.yml, checklinks, package-lock.json, package.json, scripts/didyoumean
Make the checklinks script more user friendly.
Plus add a utility script for changing links automatically.
=> Checklinks

04.Artifacts/50.State-scripts/docs.md
=> Fix incorrect description of state script order.

202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelog and statistics for meta-mender/zeus-v2020.06.

package-lock.json, package.json
This will fix up errors which came from using the Github-slugger, as they are
not 100% compatible with Grav.
=> Switch the link-checker to use Grav-slug when checking sections

.github/PULL_REQUEST_TEMPLATE.md
=> QA-191: Add a PR contributor template

02.Overview/11.Security/docs.md
Based on the work done in https://github.com/mendersoftware/mender-docs/blob/documentation-restructuring/02.Overview/11.Security/docs.md and #1024
=> add Overview/Security

05.Client-configuration/05.Configuration-file/01.Polling-intervals/docs.md
This one returns with Polling Intervals section to state at `d2b14aac2c4043d37467fc8b9ac7e54d50125720`, and fixes the links.
ChangeLog:none
=> Polling Intervals returns

chapter.md
Submitting independently this commit from #1030 to merge it first. The text has already been reviewed at #1030.
=> [hosted] Set branch version to Hosted

02.Overview/02.Device-Group/docs.md, 02.Overview/04.Deployment/docs.md, 02.Overview/06.Delta-update/docs.md, 02.Overview/10.State-script/docs.md
This fixes a mistake in #1036, I renamed the directories but forgot to update the actual titles in the Markdown files.
=> update titles to match directory names

04.Artifacts/10.Yocto-project/99.Variables/docs.md
=> Document MENDER_EXTRA_PARTS_FSTAB/SIZES_MB.

package-lock.json
=> Update package-lock.json to reflect the new validate-link dep

package-lock.json
=> Update package-lock to the newest checklinks version

README-bash-styleguide.markdown
=> Add a bash style-guide readme

02.Overview/15.Taxonomy/docs.md
Based on work done in https://github.com/mendersoftware/mender-docs/blob/documentation-restructuring/02.Overview/12.Taxonomy/docs.md and #1024
=> add Overview/Taxonomy

02.Overview/15.Taxonomy/docs.md
Original PR #1026 was probably missing a rebase.
=> Fix links from Taxonomy page

.gitlab-ci.yml, 07.Administration/03.Production-installation/docs.md
The script was silently failing as jq was not being installed.
=> [tests] Add jq dependency and verify TENANT_TOKEN var

02.Overview/15.Taxonomy/docs.md
=> Taxonomy: Adding the Mender Client definition

02.Overview/15.Taxonomy/docs.md
=> Mender Client Device mentioned

01.Getting-started/02.On-premise-installation/04.Deploy-a-system-update-demo/docs.md
ChangeLog:none
(cherry picked from commit 35fac8b699c4096c2fe2c810323c279adf30f50c)
=> 01.Getting-started/02.On-premise-installation/04.Deploy-a-system-update-demo wifi fixes

08.Downloads/docs.md
=> Mention limitation of Mac OS X mender-artifact in the downloads seciton

01.Getting-started/02.On-premise-installation/04.Deploy-a-system-update-demo/docs.md
* Correct command to actually enable ssh service
* Correct comment to use same device type as the example
=> Minor fixes 2.4.x

202.Release-information/02.Open-source-licenses/docs.md
=> Update licenses for 2.3.1.

202.Release-information/02.Open-source-licenses/docs.md
=> Update licenses for 2.4.0.

01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md, 01.Get-started/03.Deploy-a-system-update/docs.md
=> Get started cosmetics

02.Architecture/03.Compatibility/docs.md
=> Add zeus to Yocto branch support.

202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelogs and statistics for meta-mender/zeus-v2020.07.

chapter.md
=> Change chapter version to 2.4

02.Overview/15.Taxonomy/docs.md
=> Signing System taxonomy entry

06.Artifact-creation/01.Create-an-Artifact/docs.md, 06.Artifact-creation/03.Standalone-deployment/docs.md, 06.Artifact-creation/04.Sign-and-verify/docs.md, 06.Artifact-creation/05.Create-a-custom-Update-Module/docs.md
=> Changes from previous review that were missed before the merge

202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelogs and statistics for meta-mender/dunfell-v2020.07.

202.Release-information/01.Release-notes-changelog/docs.md
(cherry picked from commit dae3b942f80d13cccf793c41875b1c8f1dbbcc14)
=> 2.3.x: Add changelogs and statistics for meta-mender/dunfell-v2020.07.

202.Release-information/01.Release-notes-changelog/docs.md
(cherry picked from commit dae3b942f80d13cccf793c41875b1c8f1dbbcc14)
=> 2.4.x: Add changelogs and statistics for meta-mender/dunfell-v2020.07.

202.Release-information/01.Release-notes-changelog/docs.md
(cherry picked from commit dae3b942f80d13cccf793c41875b1c8f1dbbcc14)
=> Hosted: Add changelogs and statistics for meta-mender/dunfell-v2020.07. 

03.Client-installation/chapter.md, 06.Artifact-creation/chapter.md
Fix error on both
* https://docs.mender.io/development/artifact-creation
and
* https://docs.mender.io/development/client-installation
ChangeLog:none
=> Missing chapters for Client installation and Artifact creation

02.Overview/14.Compatibility/docs.md, 202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelogs and statistics for meta-mender/warrior-v2020.07.

06.Artifact-creation/02.Create-an-Artifact-with-system-snapshot/docs.md
… into the destination place
ChangeLog:none
=> 06.Artifact-creation/02.Create-an-Artifact-with-system-snapshot moved

08.Downloads/docs.md
Signed-off-by: Eystein Måløy Stenberg <eystein@mender.io>
=> Updated Downloads according to new docs architecture project.

04.System-updates-Debian-family/01.Overview/docs.md, 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/01.Customization/docs.md, 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md, 06.Artifact-creation/03.Modify-an-Artifact/docs.md
=> Fix review comments from @mirzak.

search/search.md
=> Add search page, merge only when new theme goes live (see MEN-2904)

02.Overview/05.Device-integration/docs.md
=> Device Integration Overview

02.Overview/05.Device-integration/docs.md, autoversion.py
=> Update feature ux redesign

200.API/chapter.md
And correct the destination: same server and development subsite.
=> MEN-3825: Add an autoversion "complain" tag to the API redirect chapter

02.Overview/02.Artifact/docs.md, 09.Downloads/docs.md
* [Overview/Artifact] Align wording with master
Likely to be a mistake from conflict resolution.
* [Downloads] Remove duplicated note about Mac OS
Likely to be a mistake from conflict resolution.
=> Hosted minor fixes master

02.Overview/07.Identity/docs.md, 02.Overview/13.Device-authentication/docs.md, 02.Overview/14.Compatibility/docs.md, 03.Client-installation/04.Inventory/docs.md, 08.Server-integration/01.Using-the-apis/docs.md, 08.Server-integration/02.Preauthorizing-devices/docs.md, 200.API/chapter.md
Updating `feature-ux-redesign-hosted` from `feature-ux-redesign` and:
* [hosted] Adjust API redirect for hosted branch
=> Update feature-ux-redesign-hosted and adjust API redirect

01.Get-started/01.Preparation/docs.md, 05.System-updates-Yocto-Project/02.Board-integration/02.Bootloader-support/02.U-Boot/docs.md, 05.System-updates-Yocto-Project/02.Board-integration/02.Bootloader-support/docs.md, 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
As these seem to not render correctly with the new version of Grav
=> Remove "./" prefix for relative links in the directory

06.Artifact-creation/04.State-scripts/docs.md
=> fix link in 06.Artifact-creation/04.State-scripts/docs.md

08.Server-integration/03.Client-certificates/docs.md
=> Add Server-side configuration for mTLS

201.Troubleshoot/03.Mender-Client/docs.md
=> Include extra OpenSSL error messages in the trouble shooting section

08.Server-integration/03.Client-certificates/docs.md
=> One misspell and one missing \

02.Overview/14.Compatibility/docs.md, 202.Release-information/01.Release-notes-changelog/docs.md, 202.Release-information/02.Open-source-licenses/docs.md
Port the relevant commits from #1171 to master.
=> [master] Release 2.5.0

03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
=> MEN-3927 MEN-3955 Document HttpsClient directive in mender.conf

home/chapter.md
=> Fix chapter header for 2.5 homepage

07.Server-installation/01.Overview/docs.md, 07.Server-installation/02.Demo-installation/docs.md, 07.Server-installation/03.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md, 07.Server-installation/03.Production-installation/docs.md, 07.Server-installation/04.Certificates-and-keys/docs.md, 07.Server-installation/05.Bandwidth/docs.md, 07.Server-installation/06.Storage/docs.md, 07.Server-installation/07.Upgrading/docs.md, 07.Server-installation/08.Backup-and-restore/docs.md, 07.Server-installation/chapter.md, 201.Troubleshoot/04.Mender-Server/docs.md
**NOTE:** Do not merge until 2.5 branch is published from mender-docs-site.
=> [hosted] Update "latest stable release" references to 2.5

202.Release-information/01.Release-notes-changelog/docs.md
=> Add changelog and statistics for meta-mender/dunfell-v2020.09.

07.Server-installation/03.Production-installation/docs.md
=> MEN-3928: document mTLS option in production-installation section

03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md, 08.Server-integration/02.Preauthorizing-devices/docs.md, 08.Server-integration/03.Client-certificates/docs.md, 201.Troubleshoot/03.Mender-Client/docs.md
=> 2.5.x merge documentation changes wrt Openssl, HttpsClient, and mTLS.

.gitlab-ci.yml
https://tracker.mender.io/browse/QA-215
Signed-off-by: Oleksandr Miliukov <28045858+0lmi@users.noreply.github.com>
- [*] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.
Thank you!
=> CI for checking latest version in hosted branch

07.Server-installation/06.Storage/docs.md
=> Fix awkward wording.
