mendersoftware/mender-docs

04.Devices/02.Partition-layout/docs.md

- Size of rootfs is configured by standard Yocto variable.
- /uboot is the boot partition. /boot is the partition on the rootfs
where the kernel resides. This is mostly for historical reasons.

Fix a few issues with partition documentation.

---

03.Artifacts/05.Variables/docs.md
04.Devices/02.Partition-layout/docs.md

There's a corresponding PR in mender Yocto layer https://github.com/mendersoftware/meta-mender/pull/154

artifacts/devices: use MENDER_SDIMG_* variable names instead of deprecated SDIMG_*

---

03.Artifacts/01.Building-Mender-Yocto-image/docs.md

This one line made all the difference for me getting a working build.  The documentation talks about the IMAGE_FSTYPES settings, but even after reading the file-system-types docs I didn't get a clear picture of what I needed to change in the config to produced the output desired.

Update build artifacts getting started

---

03.Artifacts/01.Building-Mender-Yocto-image/docs.md

Inline comments in config is invalid and won't build.  Use double-quotes for consistency.

Fix invalid formatting

---

04.Devices/02.Partition-layout/docs.md

Update partition layout with reference to MENDER_STORAGE_TOTAL_SIZE_MB.
Point the reader to Artifacts/Variables for details on the meaning of
respective variables.
@kacf @eysteins @pasinskim

devices/partition-layout: include MENDER_STORAGE_TOTAL_SIZE_MB

---

01.Getting-started/05.Standalone-deployments/docs.md
03.Artifacts/01.Building-Mender-Yocto-image/docs.md
04.Devices/02.Partition-layout/docs.md
07.Troubleshooting/03.Mender-cli/docs.md

The latter doesn't work anymore after we changed to the mender
artifact format.

Update all updates to refer to `.mender` instead of `.ext4`.

---

04.Devices/01.System-requirements/docs.md

Do not merge until https://tracker.mender.io/browse/MEN-852 is done.

MEN-735: Add link to blog post about non-Yocto build systems.

---

01.Getting-started/05.Standalone-deployments/docs.md
03.Devices/02.Partition-layout/docs.md
04.Artifacts/01.Building-Mender-Yocto-image/docs.md
04.Artifacts/03.Provisioning-a-new-device/docs.md
04.Artifacts/06.Variables/docs.md
07.Troubleshooting/03.Mender-cli/docs.md

Temporarily revert a few commits that refer to master code.
The real problem is that we publish docs from the master branch, however revert these commits until we publish stable branch.

Master docs emergency fixes

---

04.Artifacts/01.Building-Mender-Yocto-image/docs.md
04.Artifacts/06.Variables/docs.md

Not only will you trigger a rebuild of a lot of packages by changing
it, but you will influence a lot of packages you didn't intend.

SYSTEMD_AUTO_ENABLE is a package-local variable, don't set it globally.

---

03.Devices/02.Partition-layout/docs.md
04.Artifacts/01.Building-Mender-Yocto-image/docs.md
04.Artifacts/03.Provisioning-a-new-device/docs.md
04.Artifacts/06.Variables/docs.md

This should be merged as soon as we are publishing "stable" on docs.mender.io.
It reverts the emergency fixes at https://github.com/mendersoftware/mender-docs/pull/61

Revert master docs emergency fixes

---

04.Artifacts/06.Variables/docs.md

Clarify documentation of IMAGE_ROOTFS_SIZE variable.

---

06.Administration/05.Storage/docs.md

Deployments service key names were changed to include DEPLOYMENTS_* prefix. Some
keys were completely renamed, ex AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY became
DEPLOYMENTS_AWS_AUTH_KEY, DEPLOYMENTS_AWS_AUTH_SECRET
https://github.com/mendersoftware/deployments/pull/203
https://github.com/mendersoftware/integration/pull/137
@mendersoftware/rndity @maciejmrowiec @eysteins

administraion: storage: update to match env key names change in deployments

---

02.Architecture/01.Overview/docs.md
03.Devices/01.System-requirements/docs.md
04.Artifacts/01.Building-Mender-Yocto-image/docs.md
04.Artifacts/02.Image-configuration/docs.md
04.Artifacts/07.Variables/docs.md
05.Client-configuration/04.Polling-intervals/docs.md

A subtle wording change, but the clue is that the section should cover
any and all client configuration meant to be done during the build,
even if some changes are not really a build system feature.
The only exception for this section is configuration for production
devices, which is still covered in its own section.

MEN-932: Rename section to "Image configuration" to be more generic.

---

01.Getting-started/02.Create-a-test-environment/docs.md
01.Getting-started/03.Deploy-to-virtual-devices/docs.md
01.Getting-started/04.Deploy-to-physical-devices/docs.md

Since this is the default, some sections can be removed, since no
change is required anymore.

MEN-932: Document that we use standard https port now, not 8080.

---

01.Getting-started/02.Create-a-test-environment/docs.md
01.Getting-started/03.Deploy-to-virtual-devices/docs.md
01.Getting-started/04.Deploy-to-physical-devices/docs.md
01.Getting-started/05.Standalone-deployments/docs.md
04.Artifacts/01.Building-Mender-Yocto-image/docs.md
04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md

We are not going to use stable any more and all master branch
artifacts links should point to master.
Signed-off-by: Marcin Pasinski <marcin.pasinski@mender.io>

Remove all stable branch references from master.

---

06.Administration/02.Production-installation/docs.md

URL API versioning scheme was updated at the gateway, but the docs were left
behind using the older scheme.
Fixes: [Mender #1009]
@maciejmrowiec @mendersoftware/rndity @pasinskim

administration: production: update URL for checking if mender backend is up

---

06.Administration/02.Production-installation/docs.md

URL API versioning scheme was updated at the gateway, but the docs were left
behind using the older scheme.
Fixes: [Mender #1009]
@maciejmrowiec @pasinskim @mendersoftware/rndity

administration: production: update URL for checking if mender backend is up [1.x]

---

04.Artifacts/01.Building-Mender-Yocto-image/docs.md

Poky has native Go support now.

Remove oe-meta-go from layer requirements for poky/master.

---

04.Artifacts/06.Signing-and-verification/docs.md

Technically the first key generated is valid, but Go refuses to parse
one that has a parameter section, so get rid of that using the second
line.

MEN-1221: Fix incorrect ECDSA key generation arguments.

---

04.Artifacts/99.Variables/docs.md

TODO: The class should be mentioned where state scripts are
documented.

MEN-1014: Document MENDER_STATE_SCRIPTS_DIR.

---

03.Devices/05.Raw-flash/docs.md

Intended reference is mender-install-ubi.bbclass.
Signed-off-by: Mirza Krak <mirza.krak@gmail.com>

raw-flash: fix typo in reference class related to UBI install variables

---

.travis.yml
redeploy.sh

@drewmoseley @estenberg 
~~With this change, opening a PR will redeploy the staging website, and a merge will update the production server.~~
~~Note, that is you have multiple PRs open, the last PR to run will be visible in the production environment.~~
~~The alternative will be to just update both production AND testing on merge.~~
~~Any thoughts?~~
Since I need a token stored in an env. variable to redeploy the website, re-deployment can only happen on merge (Travis limitation).
My solution is update the staging env. and 5 minutes after, update the production env. 
The worse thing that can happen here is that the markdown is incorrectly formatted. If you notice within 5 minutes, you can cancel the job.

Redeploy to staging production

---

04.Artifacts/07.State-scripts/docs.md
05.Client-configuration/04.Configuration-file/01.Polling-intervals/docs.md
05.Client-configuration/04.Configuration-file/50.Configuration-options/docs.md
05.Client-configuration/04.Configuration-file/docs.md

```
commit c5b3e066824a10b9998e8fbf4393b538a13648b3
Author: Kristian Amlie <kristian.amlie@northern.tech>
Date:   Thu Sep 7 13:58:21 2017
Link state scripts timeout paragraph to configuraion options list.
commit 8e85b267bfc18458f2228e54a0f2ee5864889310
Author: Kristian Amlie <kristian.amlie@northern.tech>
Date:   Thu Sep 7 13:43:33 2017
Document using a custom mender.conf file.
This is preferred over Yocto variables for most non-critical settings,
in order to avoid polluting the build with a lot of global variables
for small details.
```

State scripts timeout

---

spell-check.sh

Evidently some versions don't load it automatically

spell-check: Force ispell to use the local dictionary

---

03.Devices/05.Raw-flash/docs.md

Fixes: [MEN #1515]
Signed-off-by: Maciej Borzecki <maciej.borzecki@rndity.com>
@drewmoseley @eysteins @kacf

devices/raw-flash: add missing ubifsmount in u-boot-integration section

---

201.Troubleshooting/03.Mender-Client/docs.md

@kacf @pasinskim can you please make sure this is (still) accurate?
In particular on my QEMU instance, /var/lib/mender/logs/ does not exist, which was a bit suspicious.

where to find client logs

---

03.Devices/05.Raw-flash/docs.md

This is more consistent with usage in other portions of the docs and removes one
more place to update when versions change

Remove github links to raw flash components.

---

04.Artifacts/01.Building-Mender-Yocto-image/docs.md

This is similar to how it is handled in Mender 1.2.x and newer docs.

Remove invalid yoctoproject.org links.

---

01.Getting-started/04.Deploy-to-physical-devices/docs.md

As the mender-artifact tool can now modify any file in a mender-artifact,
or in a sdimg, the following documentation has been simplified:
1.4: Deploy to physical devices.

MEN-1741: rootfs's no longer need to be mounted.

---

04.Artifacts/99.Variables/docs.md

These are mender-specific; rename them so it's more obvious.

Rename IMAGE_BOOTLOADER* variables to MENDER_IMAGE_BOOTLOADER*.

---

04.Artifacts/99.Variables/docs.md

It states in the Yocto docs that it is expressed in kiB, but if user never clicks the link they will probably assume that it is in MB (happened to me)

variables: make it clear that IMAGE_ROOTFS_SIZE is expressed in kiB

---

04.Artifacts/01.Building-Mender-Yocto-image/docs.md
04.Artifacts/99.Variables/docs.md

To future proof the links updated links to use the /latest/
link which should always point to the latest release of Yocto.
Note that the Yocto Project Quick Start manual does not seem
to support /latest/ link, so instead update to the latest
available which is 2.4.
Signed-off-by: Mirza Krak <mirza.krak@endian.se>

Update links to Yocto docs

---

03.Devices/02.Partition-layout/docs.md
03.Devices/03.Integrating-with-U-Boot/02.Integration-checklist/docs.md

It is now fully automatic, and should not need to be set by anyone
anymore.

Remove description of MENDER_STORAGE_DEVICE_BASE.

---

06.Server-integration/01.Using-the-apis/docs.md
06.Server-integration/02.Preauthorizing-devices/docs.md
201.Troubleshooting/04.Mender-Server/docs.md

It is commonly used together with 'curl' and JSON, but it is also
required to decode certain values in responses, e.g an artifact
URI will contain raw values that need to be decoded by a JSON
parses.
Some more background info can be found in MEN-2082.

mention usage of 'jq' utility to decoded and pretty-print JSON

---

201.Troubleshooting/01.Yocto-project-build/docs.md

As there is now a patch in sumo that targets a specific U-boot version,
which will not apply if an older U-boot fork is used.

Add troubleshooting section for rocko -> sumo update

---

03.Devices/04.Integrating-with-U-Boot/02.Integration-checklist/docs.md

At some point a new 'mender_boot_part_hex' variable was introduced.
This variable needs to be changed along with 'mender_boot_part' from linux
to perform a successful kernel swapping test, otherwise you end up with
a swapped rootfs, but the kernel from the previous rootfs.
It should be noted that if testing from uboot shell then you can
run the 'mender_altbootcmd' which will swap both variables for you.
Signed-off-by: Dell Green <dell.green@ideaworks.co.uk>

Updated device integration list to include mender_boot_part_hex variable

---

201.Troubleshooting/01.Yocto-project-build/docs.md

As there is now a patch in sumo that targets a specific U-boot version,
which will not apply if an older U-boot fork is used.
(cherry picked from commit a2b8aa81ce048c4660293888debf93b34f322c4c)

1.6.x: cherry-pick: Add troubleshooting section for rocko -> sumo update

---

201.Troubleshooting/01.Yocto-project-build/docs.md

As there is now a patch in sumo that targets a specific U-boot version,
which will not apply if an older U-boot fork is used.
(cherry picked from commit a2b8aa81ce048c4660293888debf93b34f322c4c)

1.5.x: cherry-pick: Add troubleshooting section for rocko -> sumo update

---

.ispell_english
03.Devices/04.Integrating-with-U-Boot/02.Integration-checklist/docs.md

Thanks to Dell Green <dell.green@ideaworks.co.uk> for spotting this.

Switch pgrep to pidof, which is Busybox friendly.

---

04.Artifacts/01.Building-Mender-image/01.Building-Yocto-image/docs.md

Parts of this is new in 1.6 (ARM automation), but all should be backported to 1.6.
Is there yet another disk image type for the ARM automation or is that still .sdimg?

No board specific layer

---

01.Getting-started/04.Deploy-to-physical-devices/docs.md
01.Getting-started/05.Download-test-images/docs.md
03.Devices/01.System-requirements/01.Yocto/docs.md
03.Devices/01.System-requirements/docs.md
03.Devices/chapter.md
04.Artifacts/01.Building-Mender-image/01.Building-Yocto-image/docs.md
06.Server-integration/02.Preauthorizing-devices/docs.md

It only applies to the actual Mender integration of the board
and any related low-level sections like the reference boards, output images.
Devices will still be the common term to describe a product,
identity and the over-arching concept.
Signed-off-by: Eystein Måløy Stenberg <eystein@mender.io>

Board integration is a new taxonomy concept.

---

05.Client-configuration/04.Configuration-file/docs.md

The documentation now mentions the existence of the optional
fallback configuration file, along with a brief summary of
how it works. More documentation to come later: See MEN-2177.
Signed-off-by: Don Cross <cosinekitty@gmail.com>

Mention fallback configuration file in documentation.

---

04.Artifacts/01.Yocto-project/01.Building/docs.md

It was still using the old MENDER_PARTITION_ALIGNMENT_KB variable
which was convert to MENDER_PARTITION_ALIGNMENT and the value has
to be in bytes now.

fix Raspberry Pi alignment example

---

04.Artifacts/01.Building-Mender-Yocto-image/docs.md

It was still using the old MENDER_PARTITION_ALIGNMENT_KB variable
which was convert to MENDER_PARTITION_ALIGNMENT and the value has
to be in bytes now.
(cherry picked from commit c95abbf238304c3917f82c7e82d1ba25c48161e4)

1.6.x cherry-pick: fix Raspberry Pi alignment example

---

04.Artifacts/01.Building-Mender-Yocto-image/docs.md

It was still using the old MENDER_PARTITION_ALIGNMENT_KB variable
which was convert to MENDER_PARTITION_ALIGNMENT and the value has
to be in bytes now.
(cherry picked from commit c95abbf238304c3917f82c7e82d1ba25c48161e4)
Conflicts:
04.Artifacts/01.Building-Mender-Yocto-image/docs.md

1.5.x cherry-pick: fix Raspberry Pi alignment example

---

03.Devices/02.Yocto-project/docs.md
03.Devices/chapter.md
04.Artifacts/01.Yocto-project/01.Building/docs.md

Removed reference devices I saw in these areas, this status should probably be moved to Mender Hub.
Though I wonder about the virtual ones - they are not (yet) present in Mender Hub..

reference Mender Hub alongside commercial board integration

---

README-autoversion.markdown
autoversion.py
chapter.md

If the tag is above the header, the page doesn't render correctly.

MEN-2125: Allow trailing AUTOVERSION tags for page headers.

---

README-autoversion.markdown
autoversion.py
chapter.md

If the tag is above the header, the page doesn't render correctly.
(cherry picked from commit efbb37557a3cc862d379a95906c681cb207d7333)

[1.5.x] MEN-2125: Allow trailing AUTOVERSION tags for page headers.

---

README-autoversion.markdown
autoversion.py
chapter.md

If the tag is above the header, the page doesn't render correctly.
(cherry picked from commit efbb37557a3cc862d379a95906c681cb207d7333)

[1.6.x] MEN-2125: Allow trailing AUTOVERSION tags for page headers.

---

04.Artifacts/07.State-scripts/docs.md

(cherry picked from commit 13f0df1e3aabb9551ba2e901f9fccbebe0b6edc1)
(edited expire time from 24 -> 1 hour)

Add note about download link expire time in state script examples

---

201.Troubleshooting/02.Running-Yocto-Project-image/docs.md

https://tracker.mender.io/browse/MEN-1961 is now closed.
This removes the notice from master, but:
* what about 1.7 branch?
* potentially add note in 1.6 branch that this is fixed in thud/sumo...where is it fixed exactly?
@DominikAdamski @kacf please comment

fixed in MEN-1961

---

202.Release-information/01.Release-notes-changelog/docs.md

Add release information for thud-v2019.01.

---

03.Devices/02.Yocto-project/01.Partition-configuration/docs.md
03.Devices/03.Debian-family/01.Partition-configuration/docs.md
04.Artifacts/01.Yocto-project/01.Building/docs.md
04.Artifacts/01.Yocto-project/99.Variables/docs.md
04.Artifacts/03.Provisioning-a-new-device/docs.md

This PR has the following changes:
1) The folder name changed from "Partition layout" to "Partition configuration" for both Yocto and Debian
2) The Title name changed from "Partition layout" to "Partition configuration" for both Yocto and Debian
3) The above changes will provide better readability and more specific to the contents.

 Update to "Partition configuration"

---

04.Artifacts/01.Yocto-project/02.Image-configuration/docs.md
05.Client-configuration/05.Configuration-file/01.Polling-intervals/docs.md

Update documentation so that it is consistent with the code

MEN-2214: Set inventory poll interval default to 8h

---

04.Artifacts/08.Update-Modules/docs.md

We will restore it back to master once Update Modules feature is fully
merged in mender repo

Fix dead link for Update Modules spec by refering to the fork

---

04.Artifacts/02.Debian-family/docs.md

For additional context regarding gcc6 see https://github.com/mendersoftware/mender-convert/pull/78

Remove install of custom toolchain on debian page

---

02.Architecture/03.Compatibility/docs.md

This is primarily motivated by our own need to document this for the
release process, but is useful to have in the docs as well.

Add specific versioning criteria to Compatibility document.

---

05.Client-configuration/06.Installing/docs.md

All the provided configuration files point to Hosted Mender, and the
section "Use demo settings" only updates polling intervals and not
server url, meaning it is still using Hosted Mender.

client: install: remove mention of demo server

---

05.Client-configuration/06.Installing/docs.md

All the provided configuration files point to Hosted Mender, and the
section "Use demo settings" only updates polling intervals and not
server url, meaning it is still using Hosted Mender.
(cherry picked from commit 127db0b14a80bbd7179cf155963db92584297891)

2.0.x cherry-pick: client: install: remove mention of demo server

---

05.Client-configuration/06.Installing/docs.md

I am also thinking if we should remove this section:
- https://docs.mender.io/2.0/client-configuration/cross-compiling
It is now covered in the Mender client [README](https://github.com/mendersoftware/mender/tree/update_modules#installing-from-source)

update mender install instructions

---

04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md
04.Artifacts/06.Signing-and-verification/docs.md

(cherry picked from commit 2adcf88a644a2d48d1c09f9f10265a5b4548adc2)
Conflicts:
04.Artifacts/06.Signing-and-verification/docs.md
Made a small modification to text explaining the 'sign' command

Update documentation to encourage usage of "sign" command instead of "modify"

---

05.Client-configuration/06.Installing/docs.md

From release 2.0 on, the Debian package is named `mender-client` and
must force the users to remove the beta package `mender`

Rename Mender .deb package to mender-client

---

202.Release-information/01.Release-notes-changelog/docs.md

This was simply an oversight when publishing the changelog.

Add statistics for meta-mender/thud-v2019.05.

---

01.Getting-started/04.Deploy-to-physical-devices/docs.md

The filename's prefix is 'beagleboneblack' and includes the Mender
version in it.

Fix typo in beablebone Artifact names

---

07.Administration/02.Production-installation/docs.md

I do not actually know if the values in the requirements are appropriate but recently we have had a number of questions/issues on the forums reporting failure to setup the on-prem server, and most where related to RAM memory which we seem to have increased recently due to update of Elasticsearch.

update requirements for on-prem installation

---

06.Server-integration/02.Preauthorizing-devices/docs.md

This is based on user feedback, and where the user misread this first section and then thinking that one could/should use the server generated certificates in preauthorization.

simplify leading paragraph in preauth page

---

04.Artifacts/07.State-scripts/docs.md

We store a couple of state-script examples (code) in
the Mender client repository.

add link to state-scripts example directory

---

08.Downloads/docs.md

See @eysteins comments in [this already merged PR](https://github.com/mendersoftware/mender-docs/pull/705).

Fixes for Downloads page: newlines break the links

---

05.Client-configuration/06.Installing/docs.md

So that in the odd chance that it was already running, the instructions
will still work.

Amend systemctl instructions for installing Mender

---

03.Devices/10.Update-Modules/docs.md

This is the same pull request as #711 but based on master branch instead of 2.0.X branch.
Added instruction to create directory /var/www prior to installing artifact.
Added description for deploying an update module in standalone mode.

Update update modules instructions

---

03.Devices/10.Update-Modules/docs.md

Port of #712 into 2.0.x
```
Add instructions to update modules to create directory prior to installing artifact.
Added description for deploying an Update Module in Standalone mode.
Signed-off-by: Bryan Matthews <bmatthews@reachtest.com>
(cherry picked from commit 320fba469d1dbd4d5e4f58b33a1e705b718bd4cd)
```

Update Modules instructions update 2.0.x

---

04.Artifacts/02.Debian-family/docs.md

MENDER_DISK_IMAGE should not be in the input/ directory

---

04.Artifacts/02.Debian-family/docs.md
202.Release-information/01.Release-notes-changelog/docs.md

NOTE: tag it not yet pushed. Waiting for [mender-convert PR #113](https://github.com/mendersoftware/mender-convert/pull/113).

Update docs for mender-convert 1.2.0b1 release

---

01.Getting-started/04.Deploy-a-system-update-demo/docs.md
04.Artifacts/04.Modifying-a-disk-image/docs.md
07.Administration/02.Production-installation/docs.md
07.Administration/06.Upgrading/docs.md
07.Administration/07.Backup-and-restore/docs.md
201.Troubleshooting/03.Mender-Client/docs.md

One block uses <br> instead, since it doesn't need to be monospaced,
and relies on being able to turn one piece of text bold, which doesn't
work inside a monospaced code block.
The advantage is clear. It goes from this:
To this:

Make sure terminal quotes are monospaced.

---

04.Artifacts/07.State-scripts/docs.md
05.Client-configuration/05.Configuration-file/50.Configuration-options/docs.md

Most significantly:
Moved the bulk of the description (updated) of the variables listed below to the Mender
client configuration section, mostly to avoid duplication of default settings and to avoid
repeating the information. This is after all an more advanced topic of the Mender client,
and does not need be covered in one single page.
- StateScriptRetryIntervalSeconds
- StateScriptRetryTimeoutSeconds
- StateScriptTimeoutSeconds

state-script documentation cleanup

---

.ispell_english
01.Getting-started/01.Quickstart-with-raspberry-pi/docs.md
05.Client-configuration/06.Installing/docs.md
07.Administration/02.Production-installation/docs.md
08.Downloads/docs.md

This will go together with https://github.com/mendersoftware/mender-dist-packages/pull/16 and https://github.com/mendersoftware/mender/pull/443
```
commit 85a50821236e8699a4005358a496bc9eae6021b2
Author: Lluis Campos <lluis.campos@northern.tech>
Date:   Wed Oct 30 17:00:36 2019 +0100
Document changes in deb package installation
Now a single configuration step is required, which can be done
interactively or unattended; so write the instructions for both cases.
```

MEN-2427: Document mender setup changes on deb package

---

05.Client-configuration/06.Installing/docs.md

The line to update the TenantToken in /etc/mender/mender.conf had
a typo.

fix Mender client install instructions

---

autoversion.py

changelog: none
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>

Fix typo - escaped '%' character.

---

01.Getting-started/02.On-premise-installation/05.Download-test-images/docs.md

Cherry-pick (and conflicts fix) of #808 
For upcoming Mender client 2.1.2 release we will not publish the `release_2` Artifacts, so we need to remove the references in this branch also.

MEN-2825: Remove references to outdated release_2 artifacts - 2.2.x

---

autoversion.py

This is rather a cosmetic change.
The old naming might create confusion now that the client and the whole
integration versioning have diverged.

Rename parameter mender-version to integration-version in autoversion

---

04.Artifacts/02.Debian-family/02.image-configuration/docs.md

Fix broken link to mender-convert config file

---

07.Administration/02.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
07.Administration/02.Production-installation/docs.md

Missing from commit 81f3848 due to PR tests not running enterprise test_docs script.
Follow-up from PR #841. Keep in mind that this change will not be verified until we merge this PR into master.

Adjust expected number of microservices to fix enterprise test_docs

---

05.Client-configuration/05.Configuration-file/50.Configuration-options/docs.md

The inline example were missing quotes, and the following sentence was
oddly formulated.
changelog: none
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>

Correct typo in Servers configuration options section

---

04.Artifacts/01.Yocto-project/99.Variables/docs.md

MEN-2966: Align variable default descriptions with the Debian list.

---

07.Administration/02.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
07.Administration/02.Production-installation/docs.md

On Mac OS X, the -i option of the sed command requires an explicit
backup prefix.
Signed-off-by: Fabio Tranchitella <fabio@tranchitella.eu>

Fix compatibility with Mac OS X sed version

---

07.Administration/02.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
07.Administration/02.Production-installation/docs.md

If the tests running ./run up fail, because the wrong number of
containers are up and running, there is no way to know the container
which failed.
This commit modifies the automation tests to exec, on failure, the
following commands:
docker ps && ./run images && ./run logs
Signed-off-by: Fabio Tranchitella <fabio@tranchitella.eu>

Better error reporting in case of ./run up failures

---

04.Artifacts/10.Yocto-project/99.Variables/docs.md

One space at the end of the line completely screwed up the remainder
of the page.

Fix strange rendering bug because of a single space.

---

autoversion.py

Previously the tool would exit on the first encountered version problem,
creating a slow feedback loop (specially for the ones that rely on CI
for running this check).

[autoversion] Print all encountered problems before exiting with error

---

03.Devices/02.Yocto-project/01.Partition-configuration/docs.md
03.Devices/03.Debian-family/docs.md
04.Artifacts/15.Debian-family/01.building-a-mender-debian-image/docs.md
04.Artifacts/15.Debian-family/02.image-configuration/docs.md
04.Artifacts/22.Snapshots/docs.md

This allows the outline order to change without invalidating the links.

Use unnumbered relative links.

---

01.Getting-started/02.On-premise-installation/04.Deploy-a-system-update-demo/docs.md

This was discovered in accordance with onboarding of the bbb

Fix: mender-artifact cp requires an explicit '-' to read from stdin

---

08.Downloads/docs.md
autoversion.py

To let the release responsible update this independently of mender
client tagging.

[autoversion] Add new parameter mender-convert-client-version

---

08.Downloads/docs.md

It was removed in c77cbd21efa21beccf1695d829da6677a9cf6cba

Restore the Raspbian version in Downloads table

---

01.Getting-started/02.On-premise-installation/03.Install-the-mender-client/docs.md

Add a mention to the Downloads section where to find Mender ready disk
images and remove the BeableBone Black reference for the tutorial (only
RPi 3 atm).

Rephrase System updadates section in Getting Started > Install client

---

01.Getting-started/01.Quickstart-with-raspberry-pi/docs.md
01.Getting-started/02.On-premise-installation/docs.md
03.Devices/10.Update-Modules/docs.md
04.Artifacts/10.Yocto-project/01.Building/docs.md
04.Artifacts/15.Debian-family/01.building-a-mender-debian-image/docs.md
04.Artifacts/15.Debian-family/02.image-configuration/docs.md
04.Artifacts/25.Modifying-a-Mender-Artifact/docs.md
05.Client-configuration/05.Configuration-file/50.Configuration-options/docs.md
05.Client-configuration/06.Installing/docs.md
07.Administration/02.Production-installation/docs.md
07.Administration/chapter.md
201.Troubleshooting/03.Mender-Client/docs.md

As we have now introduced several plans on 'hosted.mender.io' it makes
more sence to just mention the location instead of specific plans on
that server.

replace mentions of 'Mender Professional' with 'hosted Mender'

---

01.Getting-started/01.Quickstart-with-raspberry-pi/docs.md
01.Getting-started/02.On-premise-installation/05.Download-test-images/docs.md
01.Getting-started/02.On-premise-installation/docs.md
03.Devices/10.Update-Modules/docs.md
04.Artifacts/01.Yocto-project/01.Building/docs.md
04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md
05.Client-configuration/05.Configuration-file/50.Configuration-options/docs.md
05.Client-configuration/06.Installing/docs.md
07.Administration/02.Production-installation/docs.md
07.Administration/chapter.md
201.Troubleshooting/03.Mender-Client/docs.md

As we have now introduced several plans on 'hosted.mender.io', lets
use a more generic reference.
(cherry picked from commit 3cc93a8bcebe8d3f8da18e72735d6567eb59c5c9)
Conflicts:
01.Getting-started/01.Quickstart-with-raspberry-pi/docs.md
04.Artifacts/02.Debian-family/docs.md
04.Artifacts/05.Modifying-a-Mender-Artifact/docs.md
04.Artifacts/15.Debian-family/02.image-configuration/docs.md
05.Client-configuration/05.Configuration-file/50.Configuration-options/docs.md
05.Client-configuration/06.Installing/docs.md

2.2.x-cherry-pick: replace mentions of 'Mender Professional' with 'hosted Mender'

---

01.Getting-started/01.Quickstart-with-raspberry-pi/docs.md
01.Getting-started/02.On-premise-installation/docs.md
03.Devices/10.Update-Modules/docs.md
04.Artifacts/10.Yocto-project/01.Building/docs.md
04.Artifacts/15.Debian-family/01.building-a-mender-debian-image/docs.md
04.Artifacts/15.Debian-family/02.image-configuration/docs.md
04.Artifacts/25.Modifying-a-Mender-Artifact/docs.md
05.Client-configuration/05.Configuration-file/50.Configuration-options/docs.md
05.Client-configuration/06.Installing/docs.md
07.Administration/02.Production-installation/docs.md
07.Administration/chapter.md
201.Troubleshooting/03.Mender-Client/docs.md

As we have now introduced several plans on 'hosted.mender.io', lets
use a more generic reference.
(cherry picked from commit 3cc93a8bcebe8d3f8da18e72735d6567eb59c5c9)
Conflicts:
01.Getting-started/01.Quickstart-with-raspberry-pi/docs.md

2.3.x-cherry-pick. replace mentions of 'Mender Professional' with 'hosted Mender'

---

.gitlab-ci.yml
07.Administration/02.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
07.Administration/02.Production-installation/docs.md

- [test_docs] Changes in production docs commands to fix CI build
Ignore the tenantadm --help command (not very important) and remove -it
flags from docker run commands.
These changes fix "the input device is not a TTY" errors seen in the CI
pipeline.
- [pipeline] Move test job to test stage
Minor nitpick, but let's explicitly state that this repo does not
"build" anything.

Fix and beautify pipeline

---

04.Artifacts/10.Yocto-project/01.Building/docs.md

Since we use DEFAULT_PREFERENCE settings to ensure that updates which break
backward compatibility, a full explicit version is needed instead of
relying on wildcards.

Specify full package versions using PREFERRED_VERSION_pn.

---

07.Administration/02.Production-installation/docs.md

The configuration has been removed as it becomes ineffective in
multi-tenant setups, and has no value in single-tenant setups.
Instead, the enterprise device limit per/plan is made configurable and
is documented in the production template in mendersoftware/integration.

Remove section describing device limit configuration

---

03.Devices/03.Debian-family/docs.md

This came up from a user report and I thought it made sense to clarify.
We don't have a good way to handle artifact state scripts yet but when we do we should add a description of that here.
Thoughts?

Clarification of config files with mender-convert

---

03.Devices/02.Yocto-project/02.Bootloader-support/02.U-Boot/01.Manual-U-Boot-integration/docs.md
201.Troubleshooting/01.Yocto-project-build/docs.md

The FAT_ENV variables are a thing of the past, they have not been used
for several years.

Document new config requirements for zeus / U-Boot v2020.01+.

---

07.Administration/06.Upgrading/docs.md

From 2.4.x on, the backend services will use tags like mender-1.2.3,
where 1.2.3 is the integration version (not the git version of the
component).

MEN-4366: Update Docker image tags for the new versionig

---

201.Troubleshooting/04.Mender-Server/docs.md

Use docker exec instead of the docker-compose command in order to avoid the error:
ERROR: Service 'mender-deployments' depends on service 'storage-proxy' which is undefined.
Thank you @koptermax

Switch from docker-compose to docker for deviceauth maintenance

---

02.Overview/05.Certificates-and-keys/docs.md
04.System-updates/01.Debian-family/01.Overview/docs.md
04.System-updates/02.Yocto-Project/01.Overview/docs.md

This migrates both sections, as they are pretty much the same. 
That means:
* MEN-3205
* MEN-3211
both

Migrate System-Updates/{Yocto,Debian}/Overview sections

---

02.Overview/10.Compatibility/docs.md

Help wanted: I could not resolve all internal references with the new documentation structure and commented them out with a FIXME tag.

Move compatibility section to new documentation structure

---

01.Getting-started/01.Quickstart-with-raspberry-pi/docs.md

The on-prem Quickstart is telling you to start by SSH'ing to the
device, but you need to start by flashing it, as for Hosted Mender.

Adjust Quickstart steps for on-prem installation.

---

04.Artifacts/10.Yocto-project/01.Building/docs.md

See: https://github.com/remarkjs/remark-validate-links/issues/54 for why this
was not caught by the internal link checker.
This was a curious bug, and a result of a bug in my link migration script it
seems. bash '${VAR##.*#}' anyone? Seems it messed up the suffix placement :)
I also did a regex search for similar cases, and found none other than this one.

Fix dead internal link

---

02.Overview/12.Taxonomy/docs.md

The thinking behind it:
1. user authorizes a device
2. device is identified by an authentication set
3. there is no such thing as "authorization set"
ChangeLog:none

Authorization set renamed to Authentication set (alignment with API docs)

---

01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
01.Get-started/01.Preparation/02.Prepare-a-virtual-device/docs.md
01.Get-started/01.Preparation/docs.md
01.Get-started/02.Deploy-an-application-update/docs.md
01.Get-started/03.Deploy-a-system-update/docs.md
01.Get-started/04.Deploy-a-container-update/docs.md
03.Devices/02.Yocto-project/02.Bootloader-support/02.U-Boot/01.Manual-U-Boot-integration/01.Providing-custom-u-boot-fw-utils/docs.md
04.Artifacts/10.Yocto-project/01.Building/docs.md
04.Artifacts/10.Yocto-project/03.Building-for-production/docs.md
07.Administration/03.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
07.Administration/03.Production-installation/docs.md
07.Administration/07.Upgrading/docs.md
201.Troubleshooting/01.Yocto-project-build/docs.md
201.Troubleshooting/04.Mender-Server/docs.md

We decided to align on "tutorial" as we are currently mixing guide/tutorial to describe the same thing.

replace occurrences of 'guide' with 'tutorial'

---

04.Artifacts/10.Yocto-project/03.Building-for-production/docs.md
05.Client-configuration/07.Standalone-deployments/docs.md

standalone-deployment does not fit longer in "Overview" section. Standalone deployment should be covered in the Overview -> Introduction (briefly) and the details on how it works are moved to Client configuration (for now).

Move standalone deployments

---

01.Get-started/01.Preparation/docs.md

As it looks right now, the new "Get Started" will not be deployed to an environment where "Mender Starter" is relevant. So update to match the upcoming free evaluation.

replace "Mender Starter" reference with the upcoming free evaluation

---

05.Client-configuration/04.Inventory/docs.md

This script only exists on master branch and the versioning
of the link breaks e.g on the "hosted" branch because all
Mender client links are converted to a stable release.
We could maintain this specific link manually, but there is
not enough value here to justify it.
This was found in a deadlinkchecker report: https://www.deadlinkchecker.com/reports/docs-mender-io-20200630052922.html

remove link to mender-inventory-geo script

---

01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
08.Downloads/docs.md

For raspios 2020-05-27 we have only released it with Mender client
version 2.3.0b1. For on-boarding it is irrelevant as the user will
install the deb package (with latest stable version).
Links updated with:
```
./autoversion.py --update --mender-convert-client-version 2.3.0b1
```

[hosted] Update links for Raspberry Pi images

---

CONTRIBUTING.markdown
README-styleguide.markdown
README.markdown

This adds the style-guide from:
https://docs.google.com/document/d/1LbrWKkVXf9s5Lq2Sa74WDb8Okh7h27Ptbf3a16fz57Y/edit
to the Mender-docs repo in markdown.

MEN-3677: Add the style-guide to the Mender-docs repo

---

07.Administration/02.Demo-installation/docs.md

It is not specified anywhere else that you should use client. Rely on
the onboarding to tell you this instead.

Remove inconsistent reference to `--client` argument.

---

02.Overview/02.Device-Group/docs.md

- Added links to Overview/Taxonomy for relevant parts
- Slight re-wording of a couple of sentences
- Adjusted headings to be singular
- Removed "Groups of devices in Mender" heading (superfluous)
- Render note at the end as a "note"

minor fixes to Overview/Device group

---

02.Overview/02.Device-Group/docs.md

The link does not work, as the default version of
docs.mender.io is now the 'Hosted' branch, which has
a slightly different API structure.
Replaced link with an internal reference instead.

Overview/Device Group: Remove link to API section

---

201.Troubleshooting/03.Mender-Client/docs.md

MEN-3756: Document why `_INCONSISTENT` is appended to software name.

---

07.Administration/03.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
07.Administration/03.Production-installation/docs.md

* [tests] Add tests for all TENANT_ID/TENANT_TOKEN variables
All these variables are actually empty at the moment. We'll fix it, but
these tests will catch future regressions.
* [tests] Production installation: add -T flag to docker-compose exec
Fixes "the input device is not a TTY" error in CI tests.

[tests] Fix "the input device is not a TTY" error in CI tests

---

04.Artifacts/15.Debian-family/03.variables/docs.md

New variables added with MEN-3725 allowing part-uuid partition block device references
- MENDER_ENABLE_PARTUUID
- MENDER_BOOT_PART
- MENDER_ROOTFS_PART_A
- MENDER_ROOTFS_PART_B
- MENDER_DATA_PART
Changelog: partition-uuid block device usage variables added
Signed-off-by: Dell Green <dell.green@ideaworks.co.uk>
Thank you!

Variables added with MEN-3725 allowing part-uuid partition block device references

---

01.Get-started/03.Deploy-a-system-update/docs.md
04.Artifacts/22.Snapshots/docs.md

MEN-3832 Mention explicitly how to use multiple ssh arguments in snapshots
ChangeLog:none

MEN-3832 Mention explicitly how to use multiple ssh arguments in snapshots

---

03.Client-installation/04.Inventory/docs.md

In the context of this page, it is irrelevant if we point to OS or
Enterprise (and it will help on the hosted branch). Also fix the anchor
in the link that was broken.

Change API link to Enterprise and fix anchor

---

autoversion.py

This directory contain the checked-in API specs on old branches, which
might contain version strings that we want to ignore.
Add also "node_modules" to the ignore list, so that we can run the
script locally together with the checklinks tool installed.

[autoversion.py] Exclude 200.API dir from version checks

---

04.System-updates-Debian-family/99.Variables/docs.md
05.System-updates-Yocto-Project/99.Variables/docs.md

Use HTML `&lt;` and `&gt;` to represent < and >, otherwise the angled
brackets are interpreted as invalid HTML tags.

MEN-3814: Format variable values correctly

---

05.System-updates-Yocto-Project/02.Board-integration/02.Bootloader-support/02.U-Boot/docs.md

Fix incorrect reference to `mender-uboot` default.

---

08.Server-integration/03.Client-certificates/docs.md

fix: Wrong name for the server key and certificate generation

---

07.Server-installation/01.Overview/docs.md
07.Server-installation/02.Demo-installation/docs.md
07.Server-installation/03.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
07.Server-installation/03.Production-installation/docs.md
07.Server-installation/04.Certificates-and-keys/docs.md
07.Server-installation/05.Bandwidth/docs.md
07.Server-installation/06.Storage/docs.md
07.Server-installation/07.Upgrading/docs.md
07.Server-installation/08.Backup-and-restore/docs.md
07.Server-installation/chapter.md
201.Troubleshoot/04.Mender-Server/docs.md

These have now changed from 2.4 (old docs structure) to 2.5 (new).

[hosted] Update links for 2.5 on overridden pages

---

201.Troubleshoot/03.Mender-Client/docs.md

The `-debug` flag is not supported any more.

Correct the tip on how to add verbosity to the client

---

07.Server-installation/02.Demo-installation/docs.md

Did not work on Ubuntu. New ones confirmed to work.

Adjust dependencies for Demo installation.

---

04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/02.State-scripts/docs.md

Signed-off-by: KevinR <k.rohn@outlook.de>
The example file didn't work because of a syntax error. So I removed the backslash after the last parameter option, to avoid "unexpected end of life".
Thank you!

removed backslash from last parameter to avoid "syntax error: unexpected end of file"

---

202.Release-information/01.Release-notes-changelog/docs.md

Releasing meta-mender versions:
* rocko-v2020.10
* sumo-v2020.10
* thud-v2020.10
* warrior-v2020.10
* zeus-v2020.10

Changelog and statistics for meta-mender maintenance releases

---

202.Release-information/01.Release-notes-changelog/docs.md

(cherry picked from commit ea91bdc118d6924b8db0f230c5409ae0c06c83b1)

2.4.x: Add changelogs and statistics for meta-mender/dunfell-v2020.10.

---

202.Release-information/01.Release-notes-changelog/docs.md

(cherry picked from commit ea91bdc118d6924b8db0f230c5409ae0c06c83b1)

2.5.x: Add changelogs and statistics for meta-mender/dunfell-v2020.10.

---

autoversion.py

To be used on client only releases.

[autoversion.py] New option --mender-client-version

---

03.Devices/10.Update-Modules/docs.md
04.Artifacts/10.Yocto-project/01.Building/docs.md
04.Artifacts/40.Signing-and-verification/docs.md
05.Client-configuration/02.Cross-compiling/docs.md
05.Client-configuration/03.Identity/docs.md
05.Client-configuration/06.Installing/docs.md
06.Server-integration/02.Preauthorizing-devices/docs.md
08.Downloads/docs.md
201.Troubleshooting/01.Yocto-project-build/docs.md
202.Release-information/01.Release-notes-changelog/docs.md
autoversion.py

Cherry pick `mender-client-version` option to `autoversion`, and bump `Mender-client` version to `2.3.1`

Mender-client 2.3.1 release docs

---

01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
01.Get-started/04.Deploy-a-container-update/docs.md
03.Client-installation/02.Install-with-Debian-package/docs.md
03.Client-installation/03.Identity/docs.md
03.Client-installation/04.Inventory/docs.md
04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/01.Customization/docs.md
04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
06.Artifact-creation/01.Create-an-Artifact/docs.md
06.Artifact-creation/07.Sign-and-verify/docs.md
06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
08.Server-integration/02.Preauthorizing-devices/docs.md
09.Downloads/docs.md
201.Troubleshoot/01.Yocto-project-build/docs.md
202.Release-information/01.Release-notes-changelog/docs.md
autoversion.py

This cherry-picks the `autoversion.py --mender-client-version` option, and bumps the `mender-client-version` to `2.4.1`

Release Mender-client 2.4.1

---

05.System-updates-Yocto-Project/05.Customize-Mender/docs.md

Simply document the PACKAGECONFIG option to remove the `mender-inventory-geo` script from updates.

Inventory geo script configuration option documentation 

---

02.Overview/13.Device-authentication/docs.md
07.Server-installation/03.Production-installation/docs.md
08.Server-integration/03.Mutual-TLS-authentication/docs.md

Aligns with website taxonomy and is more accurate.

Rename Client certificates section to Mutual TLS authentication.

---

09.Downloads/docs.md

Adds two more installation paths:
- Using the convenience script (https://get.mender.io)
- Setting up our APT repository and installing from there.
(requires mendersoftware/mender-docs-site#297 to render properly)

MEN-4136: Update download package with options to use apt repository

---

202.Release-information/01.Release-notes-changelog/docs.md

Cherry-picking #1267 and missing `dunfell-v2020.12`.

[hosted] Release notes for meta-mender dunfell-v2020.12, zeus-v2020.12 and warrior-v2020.12 

---

202.Release-information/01.Release-notes-changelog/docs.md

Cherry-picking #1267 and the previous batch of maintenance releases, which I missed to cherry-pick to 2.4.x.

[2.4.x] Release notes for meta-mender zeus-v2020.12, warrior-v2020.12 and older

---

05.System-updates-Yocto-Project/06.Build-for-production/docs.md

The functionality to ship a self-signed certificate with the image is
now moved to its own recipe mender-server-certificate. Update
documentation accordingly.

MEN-4273: Adapt self-signed server instructions to new recipe

---

08.Server-integration/03.Mutual-TLS-authentication/docs.md
autoversion.py
test_autoversion.py

This is the tag that we build/test during releases and the one that we
should document for users to pull.

[hosted] Update mtls-ambassador tag to mender-2.5.0

---

autoversion.py
test_autoversion.py

As the ones used for the Docker tags of backend services.

[autoversion] Accept mender-X.Y.Z like versions

---

autoversion.py

So that the backend services get mender-X.Y.Z tags instead of X.Y.Z.

[autoversion] Fetch docker versions from release_tool

---

202.Release-information/01.Release-notes-changelog/docs.md
202.Release-information/02.Open-source-licenses/docs.md

disabled shortcode detection on long release information sites

---

202.Release-information/01.Release-notes-changelog/docs.md
202.Release-information/02.Open-source-licenses/docs.md

[1.0.x] disabled shortcode detection on long release information sites

---

202.Release-information/01.Release-notes-changelog/docs.md
202.Release-information/02.Open-source-licenses/docs.md

[1.1.x] disabled shortcode detection on long release information sites

---

202.Release-information/01.Release-notes-changelog/docs.md
202.Release-information/02.Open-source-licenses/docs.md

[1.2.x] disabled shortcode detection on long release information sites

---

202.Release-information/01.Release-notes-changelog/docs.md
202.Release-information/02.Open-source-licenses/docs.md

[1.3.x] disabled shortcode detection on long release information sites

---

202.Release-information/01.Release-notes-changelog/docs.md
202.Release-information/02.Open-source-licenses/docs.md

[1.4.x] disabled shortcode detection on long release information sites

---

202.Release-information/01.Release-notes-changelog/docs.md
202.Release-information/02.Open-source-licenses/docs.md

[1.5.x] disabled shortcode detection on long release information sites

---

202.Release-information/01.Release-notes-changelog/docs.md
202.Release-information/02.Open-source-licenses/docs.md

[1.6.x] disabled shortcode detection on long release information sites

---

202.Release-information/01.Release-notes-changelog/docs.md
202.Release-information/02.Open-source-licenses/docs.md

[1.7.x] disabled shortcode detection on long release information sites

---

202.Release-information/01.Release-notes-changelog/docs.md
202.Release-information/02.Open-source-licenses/docs.md

[2.0.x] disabled shortcode detection on long release information sites

---

202.Release-information/01.Release-notes-changelog/docs.md
202.Release-information/02.Open-source-licenses/docs.md

[2.1.x] disabled shortcode detection on long release information sites

---

202.Release-information/01.Release-notes-changelog/docs.md
202.Release-information/02.Open-source-licenses/docs.md

[2.2.x] disabled shortcode detection on long release information sites

---

202.Release-information/01.Release-notes-changelog/docs.md
202.Release-information/02.Open-source-licenses/docs.md

[2.3.x] disabled shortcode detection on long release information sites

---

202.Release-information/01.Release-notes-changelog/docs.md
202.Release-information/02.Open-source-licenses/docs.md

[2.4.x] disabled shortcode detection on long release information sites

---

202.Release-information/01.Release-notes-changelog/docs.md
202.Release-information/02.Open-source-licenses/docs.md

[2.5.x] disabled shortcode detection on long release information sites

---

202.Release-information/01.Release-notes-changelog/docs.md
202.Release-information/02.Open-source-licenses/docs.md

[hosted] disabled shortcode detection on long release information sites

---

01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
01.Get-started/03.Deploy-a-system-update/docs.md
01.Get-started/04.Deploy-a-container-update/docs.md
02.Overview/02.Device-Support/docs.md
02.Overview/03.Artifact/docs.md
03.Client-installation/02.Install-with-Debian-package/docs.md
03.Client-installation/03.Identity/docs.md
03.Client-installation/04.Inventory/docs.md
04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/01.Customization/docs.md
04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
05.System-updates-Yocto-Project/04.Image-customization/03.State-scripts/docs.md
05.System-updates-Yocto-Project/05.Customize-Mender/01.Delta-update-support/docs.md
06.Artifact-creation/01.Create-an-Artifact/docs.md
06.Artifact-creation/07.Sign-and-verify/docs.md
06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
07.Server-installation/02.Demo-installation/docs.md
07.Server-installation/03.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
07.Server-installation/03.Production-installation/docs.md
07.Server-installation/07.Upgrading/docs.md
08.Server-integration/01.Using-the-apis/docs.md
08.Server-integration/02.Preauthorizing-devices/docs.md
08.Server-integration/03.Mutual-TLS-authentication/docs.md
09.Downloads/docs.md
200.API/chapter.md
201.Troubleshoot/01.Yocto-project-build/docs.md
201.Troubleshoot/04.Mender-Server/docs.md
home/chapter.md

Updated with:
```
./autoversion.py --update \
--integration-version 2.6.0-build1 \
--meta-mender-version dunfell \
--poky-version dunfell \
--mender-convert-version 2.3.x \
--mender-convert-client-version 2.5.0-build1 \
--mender-binary-delta-version 1.2.0 \
--integration-dir ...
```

[2.6.x] Update versions for Mender 2.6 build candidate 1

---

01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
01.Get-started/03.Deploy-a-system-update/docs.md
01.Get-started/04.Deploy-a-container-update/docs.md
02.Overview/02.Device-Support/docs.md
02.Overview/03.Artifact/docs.md
03.Client-installation/02.Install-with-Debian-package/docs.md
03.Client-installation/03.Identity/docs.md
03.Client-installation/04.Inventory/docs.md
05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
06.Artifact-creation/01.Create-an-Artifact/docs.md
06.Artifact-creation/07.Sign-and-verify/docs.md
06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
07.Server-installation/02.Demo-installation/docs.md
07.Server-installation/03.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
07.Server-installation/03.Production-installation/docs.md
07.Server-installation/07.Upgrading/docs.md
08.Server-integration/01.Using-the-apis/docs.md
08.Server-integration/02.Preauthorizing-devices/docs.md
08.Server-integration/03.Mutual-TLS-authentication/docs.md
09.Add-ons/01.Remote-Terminal/20.Installation/docs.md
09.Downloads/docs.md
201.Troubleshoot/01.Yocto-project-build/docs.md
201.Troubleshoot/04.Mender-Server/docs.md

Updated with:
```
./autoversion.py --update 
--integration-version 2.6.0-build2 
--meta-mender-version dunfell 
--poky-version dunfell 
--mender-convert-version 2.3.x 
--mender-convert-client-version 2.5.0-build2 
--mender-binary-delta-version 1.2.0 
--integration-dir ...
```

2.6.x: Update for Mender 2.6 build2 + Update RaspiOS version + cherry-pick

---

07.Server-installation/03.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
07.Server-installation/03.Production-installation/docs.md

We have added three containers: deviceconnect, nats and auditlogs.
The previous update was not enough, but as this test only runs for
master it passed unnoticed the PR.

tests: Update (again) the expected containers for Enterprise setup

---

01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
01.Get-started/03.Deploy-a-system-update/docs.md
01.Get-started/04.Deploy-a-container-update/docs.md
02.Overview/02.Device-Support/docs.md
02.Overview/03.Artifact/docs.md
02.Overview/14.Compatibility/docs.md
03.Client-installation/02.Install-with-Debian-package/docs.md
03.Client-installation/03.Identity/docs.md
03.Client-installation/04.Inventory/docs.md
04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/01.Customization/docs.md
04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
06.Artifact-creation/01.Create-an-Artifact/docs.md
06.Artifact-creation/07.Sign-and-verify/docs.md
06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
07.Server-installation/02.Demo-installation/docs.md
07.Server-installation/03.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
07.Server-installation/03.Production-installation/docs.md
07.Server-installation/07.Upgrading/docs.md
08.Server-integration/01.Using-the-apis/docs.md
08.Server-integration/02.Preauthorizing-devices/docs.md
08.Server-integration/03.Mutual-TLS-authentication/docs.md
09.Downloads/docs.md
201.Troubleshoot/01.Yocto-project-build/docs.md
201.Troubleshoot/04.Mender-Server/docs.md
202.Release-information/01.Release-notes-changelog/docs.md
202.Release-information/02.Open-source-licenses/docs.md

* Update OS licenses for Mender 2.6.0
* Update versions for Mender 2.6.0
* Update versions for mender-convert 2.3.0
* Update Compatibility docs for Mender 2.6.x
* Add statistics and changelogs for Mender 2.6.0
* Add statistics and changelogs for mender-convert 2.3.0

2.6.x: release Mender 2.6.0 + mender-convert 2.3.0

---

.gitlab-ci.yml

So that we can update the site if tests are failing, when necessary.

[pipeline] Add option to skip tests

---

08.Server-integration/02.Preauthorizing-devices/docs.md

The original sed command used gnu extension so did not work on MacOS.
This command using awk is simpler and works on MacOS and Linux.
Signed-off-by: Drew Moseley <drew@moseleynet.net>
Thank you!

Use awk rather than GNU sed for formatting.

---

05.System-updates-Yocto-Project/05.Customize-Mender/docs.md

Fixed target directory of `mender-connect.conf` for yocto builds.
Replaces #1347 as this commit is signed off.

fix mender-connect.conf target path

---

07.Server-installation/03.Production-installation/docs.md

This is a follow up of the discussion here:
https://hub.mender.io/t/docker-compose-wrong-minimal-version-in-production-install-tutorial/3271

Bump the production-installation Docker-compose version to 1.9

---

03.Client-installation/07.Integration-checklist/docs.md

root@raspberrypi4:# mount /dev/mmcblk2 /mnt
mount: /mnt: special device /dev/mmcblk2 does not exist.
root@raspberrypi4:# mount /dev/mmcblk0p2 /mnt
[ 498.514342] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[ 498.522653] ext4 filesystem being mounted at /mnt supports timestamps until 2038 (0x7fffffff)
Signed-off-by: Luis Ramirez <lerv22@gmail.com>
There was an error while following the tutorial. My fix allows me to continue
Thank you!

Step 8 should use mmcblk0p2 instead of mmcblk2

---

05.System-updates-Yocto-Project/04.Image-customization/01.Features/docs.md

Mender feature to install the client is `mender-client-install` and not
`mender-install`. Added also two missing features to the list.

[Yocto] Mender features: fix typo in install and add missing features

---

04.System-updates-Debian-family/99.Variables/docs.md

Porting relevant fix from #1376

2.6.x: [Debian family/Variables] Correct style of Mender Connect variables

---

07.Server-installation/01.Overview/docs.md
07.Server-installation/02.Demo-installation/docs.md
07.Server-installation/03.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
07.Server-installation/03.Production-installation/docs.md
07.Server-installation/07.Upgrading/docs.md
07.Server-installation/08.Backup-and-restore/docs.md
201.Troubleshoot/04.Mender-Server/docs.md

This is the first part of the https://tracker.mender.io/browse/MEN-4400
The task was originally about updating the docs after migration from nginx to traefik, but it occurred that our server installation docs were outdated in general, so I decided to try to make them up to date.
Related integration changes:
https://github.com/mendersoftware/integration/pull/1316
https://github.com/mendersoftware/integration/pull/1309
The next PR will include upgrade steps and info about optional storage proxy (the one from here - https://github.com/mendersoftware/integration/tree/master/storage-proxy).

update docs to reflect actual state of the mender server

---

01.Get-started/03.Deploy-a-system-update/docs.md
01.Get-started/04.Deploy-a-container-update/docs.md
02.Overview/02.Device-Support/docs.md
02.Overview/03.Artifact/docs.md
02.Overview/14.Compatibility/docs.md
03.Client-installation/02.Install-with-Debian-package/docs.md
03.Client-installation/03.Identity/docs.md
03.Client-installation/04.Inventory/docs.md
05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
05.System-updates-Yocto-Project/05.Customize-Mender/01.Delta-update-support/docs.md
06.Artifact-creation/01.Create-an-Artifact/docs.md
06.Artifact-creation/07.Sign-and-verify/docs.md
06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
07.Server-installation/02.Demo-installation/docs.md
07.Server-installation/03.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
07.Server-installation/03.Production-installation/docs.md
07.Server-installation/07.Upgrading/docs.md
08.Server-integration/01.Using-the-apis/docs.md
08.Server-integration/02.Preauthorizing-devices/docs.md
08.Server-integration/03.Mutual-TLS-authentication/docs.md
09.Downloads/docs.md
201.Troubleshoot/01.Yocto-project-build/docs.md
202.Release-information/01.Release-notes-changelog/docs.md

* Update versions for Mender 2.7.0
Using:
```
./autoversion.py --update --integration-version 2.7.0 --mender-binary-delta 1.2.1 --poky-version dunfell --meta-mender-version dunfell
```
* Update compatibility table for Mender 2.7.0
* Add changelog and statistics for Mender 2.7.0

Update versions for Mender 2.7.0

---

04.System-updates-Debian-family/99.Variables/docs.md
09.Downloads/docs.md

MEN-4256: Mender-convert no longer installs the client by default

---

01.Get-started/04.Deploy-a-container-update/docs.md

Just a small example I wanted to add after doing Hosted onboarding testing.

Add an example to illustrate that deployed containers are also started.

---

201.Device-side-API/00.Overview/docs.md
201.Device-side-API/chapter.md

Remove github metadata, not needed in mender-docs

---

09.Downloads/docs.md

This moves the documentation to use a custom 'mender.list' source script, as
opposed to directly adding the source to '/etc/apt/sources.list' globally, which
was done previously, and is consider poor form.
Also, add a simple command for helping the user purge any existing mender
configuration from the global source list, if the user has previously done a
mender install with the old documentation.

MEN-4715: Move to using /etc/apt/source.list.d/mender.list

---

09.Downloads/docs.md

This moves the documentation to use a custom 'mender.list' source script, as
opposed to directly adding the source to '/etc/apt/sources.list' globally, which
was done previously, and is consider poor form.
Also, add a simple command for helping the user purge any existing mender
configuration from the global source list, if the user has previously done a
mender install with the old documentation.
(cherry picked from commit 1603dee5d43857ffe96fa1482d0ee48f0c2ea0e4)
Thank you!

[cherry 2.6.x] MEN-4715: Move to using /etc/apt/source.list.d/mender.list

---

05.System-updates-Yocto-Project/05.Customize-Mender/docs.md

Fixed:
* Missing ${D} in the mkdir/install destinations
* Missing ":" in the FILESEXTRAPATHS_prepend
Builds on top of fix submitted by antoniodm at:
https://github.com/mendersoftware/mender-docs/pull/1450

Yocto Customize Mender: fixes in yocto snippets

---

03.Client-installation/06.Use-the-device-side-api/docs.md

You're not meant to update the map before this time, you're meant to
update after it has elapsed (this is why it is half the expiry time).

Slight adjustment to the return value of Update Control Maps API.

---

01.Get-started/03.Deploy-a-system-update/docs.md
01.Get-started/04.Deploy-a-container-update/docs.md
02.Overview/02.Device-Support/docs.md
02.Overview/03.Artifact/docs.md
03.Client-installation/02.Install-with-Debian-package/docs.md
03.Client-installation/03.Identity/docs.md
03.Client-installation/04.Inventory/docs.md
05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
06.Artifact-creation/01.Create-an-Artifact/docs.md
06.Artifact-creation/07.Sign-and-verify/docs.md
06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
07.Server-installation/02.Demo-installation/docs.md
07.Server-installation/03.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md
07.Server-installation/03.Production-installation/docs.md
07.Server-installation/07.Upgrading/docs.md
08.Server-integration/02.Preauthorizing-devices/docs.md
08.Server-integration/03.Mutual-TLS-authentication/docs.md
09.Downloads/docs.md
301.Troubleshoot/01.Yocto-project-build/docs.md

Updated with:
```
./autoversion.py --update
--integration-dir ...
--integration-version 3.0.0-build3
--mender-convert-version 2.5.x
--mender-convert-client-version 3.0.0-build3
--meta-mender-version poky
--poky-version poky
--mender-binary-delta-version 1.2.1

Update versions for release candidate Mender 3.0.0-build3

---

03.Client-installation/06.Use-the-device-side-api/docs.md

The second step, `apt-get install`, eats all the input, preventing the
two last steps from running. Split them so the user gets one Copy
button for each.

Split snippet to avoid apt eating the input.

---

.gitlab-ci.yml
01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
09.Downloads/docs.md
README-hosted-maintenance.markdown
autoversion.py

Mender-convert images do not contain the client anymore, so this
information is obsolete.

Remove mender-convert-client auto-versioning.

---

05.System-updates-Yocto-Project/99.Variables/docs.md

The build will get an error without them.

Add missing fstab fields.

---

09.Downloads/docs.md

The Mender GUI already uses bash, the upcoming package mender-monitor
will require bash, and in any case we know Raspberry Pi OS (main target
of this script) comes with bash.

Use bash on get.mender.io script

---

05.System-updates-Yocto-Project/05.Customize-Mender/01.Delta-update-support/docs.md

Now the content is separated on /content/hosted and /content/on-prem in the URL's.
Thank you!

Update the mender-binary-delta download links to the new URL scheme

---

05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
09.Downloads/docs.md

The actual repository is monitor-client

Fix AUTOVERSION key for mender-monitor

---

01.Get-started/03.Deploy-a-system-update/docs.md
06.Artifact-creation/02.Create-an-Artifact-with-system-snapshot/docs.md

MEN-4983: Add note that `apt upgrade` is not safe when snapshotting.

---

07.Server-installation/02.Demo-installation/docs.md

spelling: double that

---

09.Add-ons/20.Monitor/docs.md

The `./XX.Something` syntax is not rendered properly in grav.

Fix relative link in Add-ons/Monitor section

---

06.Artifact-creation/05.Create-a-Delta-update-Artifact/docs.md

Signed-off-by: Kris van Rens <krisvanrens@gmail.com>
Fix simple typo.
Otherwise; great documentation and likewise project!

Fix typo in artifacts documentation

---

05.System-updates-Yocto-Project/04.Image-customization/docs.md

The Yocto Project documentation switched from docbook/xml to sphinx, therefore some of the
output locations/filenames have changed as well. The YP website is forwarding the old links
to the new location, so this link works, but update it to avoid forwarding.
Signed-off-by: Trevor Woerner <twoerner@gmail.com>
Thank you!

update yocto docs url

---

05.System-updates-Yocto-Project/06.Build-for-production/docs.md

There is no `mender` app, what needs to be bbappend'ed is `mender-client`.
Signed-off-by: Trevor Woerner <twoerner@gmail.com>
Thank you!

append mender-client not mender

---

04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
05.System-updates-Yocto-Project/03.Build-for-demo/docs.md
06.Artifact-creation/01.Create-an-Artifact/docs.md
README-autoversion.markdown
README.markdown
autoversion.py

With our latest release_tool we cannot anymore use the "trick" of
querying docker versions to pure git components (like mender-artifact,
mender, etc) and expect it to fallback to git version and work.
By default the tool will now use the git versions, unless an special
string is used for in the AUTOVERSION expression to trigger the switch
to docker version. See updated README.

MEN-5391: autoversion: Add logic to query either git or docker version

---

08.Server-integration/03.Mutual-TLS-authentication/docs.md

fails the test, hence it's not deploying.

wrong version of mtls-ambassador in staging

---

09.Downloads/docs.md

Following packages names updates from MEN-5410.
(cherry picked from commit 8f0345f7d1992b24bf09e2bc393a011dd92c099c)
Setting client version to 3.2.1 while resolving merge conflict.

3.2.x: Downloads: mender-client: Update URLs for direct downloads

---

09.Downloads/docs.md

And tweak a bit the wording to both make the expressions unique for
the tool but also make it more human friendly (same as the other
tables).

Downloads: Fix autoversion expressions for Mender client packages

---

09.Downloads/docs.md

We need the '%2B' character, which is a '+' sign, to remain as is,
otherwise the download doesn't work. But Grav auto-translates them,
so use HTML links to avoid that.

Downloads: Use HTML links to prevent Grav from mangling the URL.

---

09.Downloads/docs.md

Merging master in to bring https://github.com/mendersoftware/mender-docs/pull/1658

hosted: Downloads: Use HTML links to prevent Grav from mangling the URL.

---

09.Downloads/docs.md

wget renames the files correctly. This way also the download commands
are consist with the OS packages.

Switch from curl to wget for commercial packages download

---

09.Add-ons/10.Configure/01.Device-integration/docs.md

As you can see from logs created inside the same file on the device this is the value of sys.argv.
14:41:02,820 root INFO ['/usr/lib/mender-configure/apply-device-config.d/example_script.py', '/var/lib/mender-configure/device-config.json'
Also run into troubles with the arguments of subprocess.run so I prefered to let all the command inside a list.

Small fix python example for mender configure

---

05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
06.Artifact-creation/06.Standalone-deployment/docs.md
06.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
301.Troubleshoot/03.Mender-Client/docs.md

the `-command` syntax is no longer prefered.

docs: move example commands to the new command syntax

---

.gitlab-ci.yml
03.Client-installation/02.Install-with-Debian-package/docs.md
07.Server-installation/03.Installation-with-docker-compose/02.Upgrading-from-OS-to-Enterprise/docs.md
07.Server-installation/03.Installation-with-docker-compose/docs.md
08.Server-integration/03.Mutual-TLS-authentication/docs.md
09.Downloads/docs.md
run-tests.sh

* Install with Debian: Use native arch and split download and setup
* Install with Debian: Use new demo flags on mender setup commands
* Downloads: Consistently use sudo in all privileged commands
* Downloads: fix download links for mender-gateway examples package
* Downloads: fix download links for mender-gateway Debian buster armhf
* Downloads: use wget for mender-gateway examples package
* Downloads: Split closed source downloads instructions
* QA-378: Add AUTOMATION tests for Downloads and mender-client deb install

QA-378: Add AUTOMATION tests for Downloads and mender-client deb install

---

06.Artifact-creation/06.Standalone-deployment/docs.md

It looks like this dashes are deprecated now
Thank you!

Remove dash from commands

---

.github/PULL_REQUEST_TEMPLATE.md

QA-365: Add the conventional commit spec to the PR template

---

01.Get-started/06.Mender-Gateway/docs.md

docker command was failing because a missing character
Ticket: None
Signed-off-by: Luis Ramirez Vargas <luis.ramirez@northern.tech>
```
```
I fixed a typo in a command
Thank you!

fix: add missing backslash in command

---

08.Server-integration/01.Using-the-apis/docs.md

in the future. Remove the explicit listing.

mender-cli no longer supports just two use cases and will be extended

---

07.Server-installation/04.Production-installation-with-kubernetes/03.NATS/docs.md

Signed-off-by: Roberto Giovanardi <rob.giovanardi@gmail.com>
```
fix: add storageclass note for k3s
NATS helm chart uses "default" `storageClassName` that doesn't work with k3s. Solved by changing `storageClassName` to `local-path` into the doc. Also added an advice for replacing local-path with the appropriate storage class name.
Changelog: Add storageClassName note for K3S
Ticket: None
```
NATS helm chart uses "default" `storageClassName` that doesn't work with k3s.   
Fixed by changing `storageClassName` to `local-path` into the doc. Also added an …

fix: add storageclass note for k3s

---

07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md

Ticket: MEN-5638
(cherry picked from commit 2299b4b1c1dce7ac61090558a3cd0a032e178f07)

fix: binary name for useradm-enterprise when creating additional users

---

301.Troubleshoot/01.Yocto-project-build/docs.md

fix: Update the link to the denx wiki on UBoot's boot count limit

---

01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
09.Downloads/docs.md

Previously there was a typo for version 3.3.0, but this is the Mender release
version, not the converted image version.

chore(3.3.0): update the convert images to convert version 3.0.0

---

08.Server-integration/03.Mutual-TLS-authentication/docs.md

For now we have to do this component manually.

Fix mtls-ambassador autoversion failure by ignoring it.

---

01.Get-started/03.Deploy-a-system-update/docs.md

Removed '.' after '!'. `s/!./!`

Fixed typo in 'Getting started' tutorial

---

02.Overview/01.Introduction/docs.md

I had to look up the definition of the DFU. By adding the definition to
the first use of the abbreviation, other IoT newbies like my self won't
have to do this.

Add definition of DFU to the first use of the abbreviation

---

01.Get-started/03.Deploy-a-system-update/docs.md
04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/01.Customization/docs.md
04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
06.Artifact-creation/02.Create-an-Artifact-with-system-snapshot/docs.md
autoversion.py

Note that I'm cherry-picking in the opposite order in this case, since 3.3.x was the branch which suffered problems. However, I will also cherry-pick the tool fixes to master.

Several autoversion fixes

---

09.Downloads/docs.md

After adding Ubuntu Jammy, we have three more packages (one per each architecture).

test: Update expected packages count in Downloads page

---

.gitlab-ci.yml

Since Mender 3.3 all the repos are part of the release tool: the extra flags are not recognized anymore and we can also clean-up the SSH cloning of private repo.

ci: Update job  test:latest_versions

---

09.Downloads/docs.md

Ticket: [MEN-5927](https://tracker.mender.io/browse/MEN-5927)

chore: Stop using deprecated apt-key in repo install instructions

---

201.Device-side-API/00.Overview/docs.md

Add examples and explanations to the device-side API overview. This encompasses a short explanation of methods versus signals.
Ticket: None
Signed-off-by: Josef Holzmayr <jester@theyoctojester.info>

fix: add examples for client api invocations

---

06.Artifact-creation/02.Create-an-Artifact-with-system-snapshot/docs.md

fix: typo in command that dumps golden image from target
Signed-off-by: Luis Ramirez <luis.ramirez@northern.tech>
```
```
Thank you!

Fix typo in golden image generation

---

03.Client-installation/02.Install-with-Debian-package/docs.md
09.Downloads/docs.md

The removal led to a lot of changes. With doing it this way we keep the resources for installing the client in the downloads section, which makes sure we don't drift away from the steps required in different parts of the docs.
Ticket: MEN-5907

fix: Remove the reference to Debian buster

---

302.Release-information/01.Release-schedule/docs.md

Shed some light on the LTS vs. non-TLS release versioning and schedule. Please note that this commit does not introduce any difference in the versioning and schedule, it simply reflects the current practices.
Ticket: None
(cherry picked from commit 4bfb5fe95366a45c19712bf8c7bbac16dff59877)

feat: update release schedule information

---

05.System-updates-Yocto-Project/04.Image-customization/01.Features/docs.md

All available entries for MENDER_FEATURES need to be documented. In order to communicate the fitness for production clearly, some have been marked as "internal" or "experimental".
Ticket: None
Signed-off-by: Josef Holzmayr <jester@theyoctojester.info>
```
```
Thank you!

fix: document missing MENDER_FEATURES in Yocto

---

06.Artifact-creation/10.CI-CD/01.GitHub-Actions/docs.md
06.Artifact-creation/10.CI-CD/docs.md

For the other CIs pages (GitLab and Azure DevOps) it is correctly set, but we missed it on GitHub Actions and the parent page.

chore: Consistently use autoversion for mender-ci-workflows references

---

autoversion.py

As we moved out this repository out of the release_tool, we need an explicit argument to update the version here.
This is a temporary solution to be redesign during the upcoming release process split workforce.

feat(autoversion): Add argument --mender-ci-workflows-version

---

.gitlab-ci.yml

As this component is out of the release_tool, the ci test has no way to know which is the latest version (for now).
Amends commit 72079d479137940b6afcecf35c2f8271585dc335 and it will be reworked together with the original commit once we have a design for where to store the latest version of independent components.

ci: Hard-code mender-ci-workflows-version to 1.0.0

---

301.Troubleshoot/10.Hosted-Mender-migration/docs.md

Fixing misleading comment that migrating to the EU HM instance is enterprise only feature.

Add info that the migration to EU is not enterprise only.

---

08.Server-integration/03.Mutual-TLS-authentication/docs.md

fix: mTLS ambassador runs as non-root

---

07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md

```
fix: tenantadm command separated from kubectl command
Added double dash `--` to separate `kubectl` command from the exec `tenantadm` command
Changelog: fix tenantadm command
Ticket: None
```
Added double dash `--` to separate `kubectl` command from the exec `tenantadm` command

fix: tenantadm command separated from kubectl command

---

07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md

Cherry pick of PR: https://github.com/mendersoftware/mender-docs/pull/2058

[Cherry 3.5.x] :fix: tenantadm command separated from kubectl command

---

.gitlab-ci.yml
07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md

Cherry pick of PR: https://github.com/mendersoftware/mender-docs/pull/2058
Also cherry-pick of 704b738b7 that changed gitlab runner tag

[Cherry 3.4.x] :fix: tenantadm command separated from kubectl command

---

07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md

Cherry pick of PR: https://github.com/mendersoftware/mender-docs/pull/2058

[Cherry 3.3.x] :fix: tenantadm command separated from kubectl command

---

07.Server-installation/04.Production-installation-with-kubernetes/02.MongoDB/docs.md

```
fix: tuning internal MongoDB probes
Bitnami deployed MongoDB chart won't get ready in some conditions (e.g. slow storage).
The Pod never get ready because of timeout.
Fixed by increasing the default timeout in the helm chart
Changelog: modified the default probe timeoutSeconds in bitnami MongoDB Helm Chart
Ticket: None
```
Bitnami deployed MongoDB chart won't get ready in some conditions (e.g. slow storage).
The Pod never get ready because of timeout.
Fixed by increasing the default timeout in the helm chart

Internal MongoDB not ready

---

04.Operating-System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md

In order to use the containerized version of mender-convert, the containers must be built. This is documented in the README, but missing here.
Ticket: None
```
```
Thank you!

fix: add missing docker build for mender-convert

---

07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md

```
fix: implicitly use the latest Helm Chart version
Mender Helm Chart is an independent project with its own versioning.  
To select the right Mender version a new variable was added:
```
export MENDER_VERSION_TAG="mender-3.4"
```
Besides, the `helm upgrade` command will not specify a `--version`, so I'll take the last published chart.
Changelog: implicitly use the latest Helm Chart version
Ticket: MC-6798
```
fix: implicitly use the latest Helm Chart version
Mender Helm Chart is an independent project with its own versioning.  
To select the right …

3.4.x chore: implicitly using latest version with master

---

07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md

```
fix: implicitly use the latest Helm Chart version
Mender Helm Chart is an independent project with its own versioning.  
To select the right Mender version a new variable was added:
```
export MENDER_VERSION_TAG="mender-3.3"
```
Besides, the `helm upgrade` command will not specify a `--version`, so I'll take the last published chart.
Changelog: implicitly use the latest Helm Chart version
Ticket: MC-6798
```
fix: implicitly use the latest Helm Chart version
Mender Helm Chart is an independent project with its own versioning.  
To select the right …

3.3.x chore: implicitly using latest version with master

---

07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md

Ticket: MC-6809
```
fix: set working AWS_URI example
Ticket: MC-6809
```
The `AWS_URI` specified in the doc doesn't work with S3. I tested the right URL and updated the example.

fix: set working AWS_URI example

---

07.Server-installation/06.Storage-of-the-artifacts/docs.md

With the setting as it was you get the most criptic error:
```
main: failed to setup storage client: s3: failed to check bucket preconditions: operation error S3: HeadBucket, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, canceled, context deadline exceeded
```
Due to AWS SDK in deployments going into uncharted code segments.
Ticket: None

chore: critical fix for server installation.

---

06.Artifact-creation/07.Sign-and-verify/docs.md

The second command in the private key generation had no effect. We put the two together for simplification and consistency with how ECDSA keys are generated below.

chore: Simplify commands to generate RSA key pair

---

.github/PULL_REQUEST_TEMPLATE.md

```
```
This PR fixes a dead link in github PR template regarding commitlint grammar.

fix: correct commitlint grammar URL in GitHub PR template

---

05.Operating-System-updates-Yocto-Project/05.Customize-Mender/01.Delta-update-support/docs.md
05.Operating-System-updates-Yocto-Project/05.Customize-Mender/docs.md
10.Downloads/docs.md

Enterprise user names are not emails. Rename the bash variable to avoid confusion to Enterprise customers downloading software with their Enterprise credentials.
Ticket: None
(cherry picked from commit 1c2cfc630e2eb00b88910667f1fc9943630ab2a2)

fix: replace MENDER_ENTERPRISE_EMAIL with MENDER_ENTERPRISE_USER

---

01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md

In Mac OS, the default provider for `openssl` command is LibreSSL (instead of OpenSSL), which does not support the `-6` option to specify SHA512 hash algorithm.
Remove the option and let the command use the default algorithm, which will actually be different for OpenSSL and LibreSSL.

chore: Remove unsupported option for openssl command in Mac OS

---

04.System-updates-Debian-family/99.Variables/docs.md

During implementation at my end, i've discovered some discrepancies between some variables referenced in the docs and what mender-convert actually looks for.
PS: there may be other discrepancies but the ones submitted are the only ones i have looked into, for now.

Replace index with number to match what the code is actually looking for

---

09.Add-ons/90.Mender-Connect/docs.md

During implementation at my end, i've discovered some discrepancies between some variables referenced in the docs and what mender-connect actually looks for.
PS: this is not an exhaustive check, just the items i've personally encountered
LE: I have now realised that I have done the PR from and into hosted tag despite our implementation now being done on 3.4. I am assuming hosted has similar code, so i suspect this is appropriate for both tags. If you need me to re-do this on 3.4 let me know

Changes to Limits properties

---

302.Release-information/01.Release-schedule/docs.md

The 3.3 docs had the old docs format.
As it's the current LTS, the new release schedule docs applies.

feat: extend 3.3 support and Release schedule docs

---

301.Troubleshoot/03.Mender-Client/docs.md

This adds a user reported mitigation for a Raspbian+package update correlated boot problem as described here:
https://hub.mender.io/t/hang-at-boot-waiting-for-root-device-mender-kernel-root/5693/12
Ticket: None
```
```
Thank you!

fix: add boot problem on Raspbian to troubleshoot section

---

01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
301.Troubleshoot/03.Mender-Client/docs.md

The Raspberry Pi Imager offers options to pre-customize the image right during flashing to the SD card. This injects a firstrun.sh script, along with a kernel command line that causes an infinite boot loop.
This needs to be documented in the onboarding section as well as the troubleshoot section.
Ticket: None
```
```
Thank you!

fix: document Raspberry Pi Imager bug

---

02.Overview/05.Deployment/docs.md

Ticket: None
Recently had a case where I pointed the customer to the deployment docs and they couldn't reason their way to the answers. This is an attempt to simplify the docs and make the ordering in complex cases more clear.

Expand and revamp the deployments docs

---

07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md

Ticket: MC-6911
```
fix: pinned the helm chart version for the older mender versions
Starting from the 3.6 release, the helm chart contains new breaking changes.
To avoid disrupting old 3.3 and 3.4 setups, we added the latest supported helm chart version
in the setup documentation.
Changelog: Pinned the helm chart version for the older mender versions
Ticket: MC-6911
```
Starting from the 3.6 release, the helm chart contains new breaking changes.
To avoid disrupting old 3.3 and 3.4 setups, we added the latest supported helm chart version
in the setup …

chore: pinned helm chart version for the 3.4 mender versions

---

07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md

Ticket: MC-6911
```
fix: pinned the helm chart version for the older mender versions
Starting from the 3.6 release, the helm chart contains new breaking changes.
To avoid disrupting old 3.3 and 3.4 setups, we added the latest supported helm chart version
in the setup documentation.
Changelog: Pinned the helm chart version for the older mender versions
Ticket: MC-6911
```
Starting from the 3.6 release, the helm chart contains new breaking changes.
To avoid disrupting old 3.3 and 3.4 setups, we added the latest supported helm chart version
in the setup …

chore: pinned helm chart version for the 3.3 mender versions

---

10.Downloads/docs.md

- rebalanced tab shortcodes after 0117c6127f4a96457368ae608e3eb51aedb386e8
Ticket: None

fix: fixed an issue that prevented access to the download page due to an inbalance of tab closures

---

04.Operating-System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md

This comes with the pull request https://github.com/mendersoftware/mender-convert/pull/594
If there is any other place in the docs where `mender-convert/scripts/bootstrap-rootfs-overlay-hosted-server.sh` is used, please let me know!

fix: specify region for hosted configuration

---

09.Add-ons/50.Remote-Terminal/docs.md

Hosted merge, follows https://github.com/mendersoftware/mender-docs/pull/2238.
I have no idea why there is an extra `81d6afb55` but it's an empty merge commit so isn't of practical importance.

Mender cli for terminal

---

06.Artifact-creation/04.State-scripts/docs.md

During implementation I was quite confused that even though usual state script flow and error state script flow is different, there seemingly is no handling of error states. However, after looking through examples I have realised that `_Leave` state scripts are not run on error and instead `_Error` scripts are run. I just wanted to put more emphasise on this specific idea as it is quite crucial in handling and distinguishing usual flow from the error flow.

fix: Emphasised _Error states are run instead of _Leave states

---

06.Artifact-creation/04.State-scripts/docs.md

Signed-off-by: Dmitrij Santarovic <ds@ferarudynamics.co.uk>
(cherry picked from commit afef4faacffe599bd1b90e54b8ad920d67d0fd48)

Emphasised _Error states are run instead of _Leave states

---

301.Troubleshoot/10.Hosted-Mender-migration/docs.md

Suggesting an unsafe update module in the docs is unsafe, even with the note.
We promise brick free devices, so suggesting risky steps in the docs doesn't align with that message.
Ticket: None

chore: remove the unsafe update module and make migration ent only

---

07.Server-installation/02.Upgrading-from-previous-versions/090.Upgrading-from-3.3-to-3.6/docs.md

Not everyone has a clear separation between the helm chart version and the product update.
When doing an update from 3.3.->3.6 you can stumble on the helm chart version increase and perceive it as a problem in 'server upgrade problem'
This expansion hopes to clarify this.
Ticket: None

chore: mention the helm breaking change

---

08.Server-integration/01.Using-the-apis/docs.md

Ticket: None
Adds a section to server integration docs that describes how to use session tokens for CLI and API uses cases.
This is helpful to know for users of SSO.

Docs: Adds session token usage for CLI and API

---

07.Server-installation/02.Upgrading-from-previous-versions/090.Upgrading-from-3.3-to-3.6/docs.md

fix: canonical URL for the 3.6-only page about upgrading from 3.3

---

04.Operating-System-updates-Debian-family/01.Overview/docs.md

(cherry picked from commit 3a0612bd6025d565d54bebea594a0c226a370073)

Fix incorrect reference to mender-convert version and grub.d support.

---

301.Troubleshoot/03.Mender-Client/docs.md

Cherry picked from commit 04b8cac8f1fd4062ec9af1d3d1e42bc662dc0b8b

3.7.x: doc: Fix markdown syntax for link

---

06.Artifact-creation/02.Create-an-Artifact-with-system-snapshot/docs.md

(cherry picked from commit 5fe775b60e9097e44afb85d064799ecc308d3acd)

Clarify that an uncompressed image must be given to mender-artifact.

---

05.Operating-System-updates-Yocto-Project/99.Variables/docs.md

Document the `MENDER_EXTRA_PARTS_MOUNT_LOCATIONS` variable. Reorder the `MENDER_EXTRA_PARTS_*` sections to be consistent with the description in `MENDER_EXTRA_PARTS`. Make some simple grammatical and punctuation changes.
Changelog: Add MENDER_EXTRA_PARTS_MOUNT_LOCATIONS documentation
Ticket: None

feat: Add MENDER_EXTRA_PARTS_MOUNT_LOCATIONS documentation

---

01.Get-started/03.Deploy-an-operating-system-update/docs.md

Fix: corrected typo in docs.md, "exsts" was spelled "eists"

Fix: corrected typo in docs.md

---

03.Client-installation/08.Integration-checklist/docs.md

Add a space after a slash in grep command to fix mountpoints filtering in _Confirm OS switch using bootloader variables_ section.
Ticket: None
Other instances of the same command already have a space after the slash.
The following console dump show the difference between the two commands.
```console
root@testmender:~# mount | grep 'on /'
/dev/mmcblk0p4 on / type ext4 (rw,noatime)
devtmpfs on /dev type devtmpfs (rw,relatime,size=986560k,nr_inodes=246640,mode=755)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=666)
tmpfs on /run …
```

fix: add missing space to mount with grep command

---

10.Downloads/docs.md

This is a close source component and it is not available in the public APT repositories.

chore: Remove misleading note about `mender-monitor` in repos

---

01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md

The snippet now will find either `boot` or `bootfs` mount point.

CE-390: Amend `boot` partition detection for latest Raspberry Pi OS image

---

302.Release-information/01.Release-schedule/docs.md

An oversight in the previous commit

chore: Update end of support date for Mender 3.7

---

10.Downloads/docs.md

Missing from 84600922dd9fe13abd92a8795f4042219a28e3ce.
This test only runs on protected branches (master) so the mistake went unnoticed in the PR.

test: Update expected number of packages after adding new distro

---

302.Release-information/01.Release-schedule/docs.md

We support the two latest (at any given time), and this already seems out-dated.
Ticket: Men-7484

fix: Redacted mention of specific Yocto LTS releases

---

06.Artifact-creation/01.Create-an-Artifact/10.Docker-Compose/docs.md

Bump app-update-module reference from 1.0.0 to 1.1.0.
Ticket: MEN-7477
```
```
Bump app-update-module reference from 1.0.0 to 1.1.0

chore: bump app-update-module to 1.1.0

---

08.Server-integration/07.Webhooks/docs.md

docs(webhook): Inventory webhook description.

---

04.Operating-System-updates-Debian-family/99.Variables/docs.md

The MENDER_BOOT_PART_MOUNT_LOCATION variable is being introduced in mender-convert, document it accordingly.
Ticket: None
```
```
Thank you!

chore: document MENDER_BOOT_PART_MOUNT_LOCATION

---

09.Add-ons/05.Orchestrator/50.Interface-protocol/docs.md

```
commit 672287a330de35e10ce7f26b239cdc36096ae233
Author: Kristian Amlie <kristian.amlie@northern.tech>
Date:   Tue Oct 29 14:49:42 2024
Add Update Module specification.
This commit only exists to make reading the next commit easier, where
we make the necessary changes to the specification to cover the update
interfaces instead.
Ticket: MEN-6996
commit 9e34ed21d917ff3703a16de0aee63c9c91318330
Author: Kristian Amlie <kristian.amlie@northern.tech>
Date:   Mon Oct 28 07:50:28 2024
Adapt the update module protocol docs into update interfaces.
Ticket: MEN-6996
```

Add Update Interface protocol specification

---

301.Troubleshoot/03.Mender-Client/docs.md

Makes the snippet to troubleshoot deltas work on devices with busybox dd.
Proof it gives the same results as the previous command:

feat: delta troubleshoot snippet works with busybox dd

---

05.Operating-System-updates-Yocto-Project/04.Image-customization/01.Features/docs.md

The "mender-prepopulate-inactive-partition" feature has been added as MENDER_FEATURE to meta-mender, respectively Yocto. This adds the corresponding entry to the image customization features list.
```
```
Thank you!

chore: add "mender-prepopulate-inactive-partition" feature

---

01.Get-started/03.Deploy-an-operating-system-update/docs.md
01.Get-started/04.Deploy-a-container-update/docs.md
10.Downloads/docs.md

OpenSSL 1.1 has been replaced in latest Ubuntu and Debian releases and, most importantly, Ubuntu does not provide an openssl1.1 compatibility package, which runs our pre-compiled binary unusable there.
Instead of having two binaries, one per each OpenSSL version, we link now directly into the deb packages as the preferred method to install the tool on Linux.
On Mac the support has not changed, but we add the architecture to make it explicit where the binary is expected to work.
As a side effect of using deb packages, we cannot offer anymore a reliable link to the pre-release version, so we remove these from the table. The master versions are still accessible via APT experimental repositories for the advance users.

MEN-7767: Replace libssl1.1 `mender-artifact` with deb packages

---

01.Get-started/03.Deploy-an-operating-system-update/docs.md
01.Get-started/04.Deploy-a-container-update/docs.md
10.Downloads/docs.md

OpenSSL 1.1 has been replaced in latest Ubuntu and Debian releases and, most importantly, Ubuntu does not provide an openssl1.1 compatibility package, which runs our pre-compiled binary unusable there.
Instead of having two binaries, one per each OpenSSL version, we link now directly into the deb packages as the preferred method to install the tool on Linux.
On Mac the support has not changed, but we add the architecture to make it explicit where the binary is expected to work.
As a side effect of using deb packages, we cannot offer anymore a reliable link to the pre-release version, so we remove these from the table. The master versions are still accessible via APT experimental repositories for the advance users.
Ticket: MEN-7767 …

docs: Replace libssl1.1 `mender-artifact` with deb packages

---

10.Downloads/docs.md

The links per distro were pointing to the wrong reference. Sorted also now the same way that the table to facilitate maintenance.
Amends commit b8cfdcd.

docs: Fix `mender-artifact` download links

---

301.Troubleshoot/03.Mender-Client/docs.md

It's not uncommon for this to be an issue for users. Providing a bit more
specific guidance on how to ensure correct time prior to mender services
starting could help some users avoid running into issues where because of large
polling intervals for production rejections related to time sync can cause long
delays in establishing communication with the server.
Ticket: CE-564
Signed-off-by: Nick Anderson <nick@cmdln.org>

CE-564: docs: Added note about how to achieve time sync before mender services start

---

01.Get-started/03.Deploy-an-operating-system-update/docs.md

Future versions of the virtual device won't support anymore this tutorial. Make it RPi only.

MEN-7633: Update Deploy an OS update to require real hardware

---

07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md

Ticket: None
```
```
This way you're forced to wait for the complete install before continue the setup

docs: add wait flag to helm upgrade

---

.checklinks-whitelist

The new tooling to generate the licenses for the Mender Server produce markdown links to non-existing destinations.
Although it would be nice to fix the root cause, let's ignore the pages from the link checker to simplify our flow.

chore: Add licence pages to checklinks whitelist

---

01.Get-started/05.Monitor/docs.md

The rest of the commands in this tutorial either have `sudo` or an explicit mention to be run as root.

chore: Add missing `sudo` in sytemctl command

---

06.Artifact-creation/05.Create-a-Delta-update-Artifact/docs.md

Replacing it with an info tip about the version implementing it.
It was implemented one year ago.

MEN-6774: Remove limitation of delta not working on UBIFS

---

01.Get-started/01.Preparation/docs.md

```
fix: Adding support index to prepartaion document
To make is quicker for the user to get to the index of community supported devices
Changelog: Add support index to 01.Get-started/01.Preparation/docs.md
Ticket: ME-490
```

Add support index

---

07.Server-installation/05.Backup-and-restore/docs.md

```
```
Added basic guidelines for backing up and restoring a Mender server instance.

Basic backup and restore documentation

---

06.Operating-System-updates-Zephyr/04.Customize-Mender-mcu/docs.md

The important detail is that `CONFIG_MENDER_SERVER_HOST_ON_PREM` needs to be explicitly set.

MEN-8351: Improve and correct instructions for Mender MCU with on-premise

---

01.Get-started/03.Deploy-an-operating-system-update/docs.md
11.Downloads/docs.md

`brew` is not available in the environment testing the commands.
Ticket: MEN-8333

fix: Prevent automation from running `brew install`

---

302.Release-information/01.Supported-releases/docs.md

Follow-up on closed https://github.com/mendersoftware/mender-docs/pull/2598 (had problems with CI not recognizing my sign-off)
Attempts to fix the indentation for call-outs in https://docs.mender.io/release-information/supported-releases#mender-client-subcomponents
I am assuming MkDocs is used to generate the documentation and that requires multi-line call-outs to be indented https://squidfunk.github.io/mkdocs-material/reference/admonitions/#usage so they are rendered as one piece.
Tested by locally running  `mender-docs-site`

fix: indent call outs in device API version section

---

302.Release-information/01.Supported-releases/docs.md

4.0 is EOL as it was port of the Mender 3.7 bundle

chore: remove 4.0 from Supported-releases (EOL)

---

12.General/01.Build-from-source/docs.md

Build from source page aims to the project repositories we are hosting on GitHub. Instead of using plain text for the repo addresses I changed them to direct hyperlinks.
Ticket: None

chore: Update build from source page

---

01.Get-started/02.Deploy-an-application-update/docs.md

Ticket: None
Changelog: Update qemu device type in Get started guide to be in line with actual device type reported by virtual device

chore: Update qemu device type in get started guide

---

01.Get-started/03.Deploy-an-operating-system-update/docs.md

`Deploy an Operating system update` chapter was pointing to the deprecated method of `mender-artifact` installation. Now it will point to the common `Download` page with repo setup description.

chore: Update pointer to mender-artifact installation

---

02.Overview/02.Device-Support/docs.md
03.Client-installation/02.Install-with-Debian-package/docs.md
03.Client-installation/03.Identity/docs.md
03.Client-installation/04.Inventory/docs.md
03.Client-installation/08.Integration-checklist/docs.md
05.Operating-System-updates-Yocto-Project/03.Build-for-demo/docs.md
07.Artifact-creation/01.Create-an-Artifact/docs.md
07.Artifact-creation/07.Sign-and-verify/docs.md
07.Artifact-creation/08.Create-a-custom-Update-Module/docs.md
09.Server-integration/02.Preauthorizing-devices/docs.md
301.Troubleshoot/01.Yocto-project-build/docs.md

Update `mender` to 5.0.2
Update `mender-connect` to 2.3.1
Update `monitor-client` to 1.4.1
Updated with 
```
./autoversion.py --update --component mender --version 5.0.2
./autoversion.py --update --component mender-connect --version 2.3.1
./autoversion.py --update --component monitor-client --version 1.4.1
```

chore: Update versions for Mender Client LTS 5.0

---

11.Downloads/docs.md

Some headers are duplicated (APT repo setup) which causes some links to point into incorrect section. More precise linking targets are required.
Ticket: None

chore: Update section links in download page

---

02.Overview/18.Limits/docs.md

Mainly for ensuring those are clear for hosted Mender users.

Add update check and inventory poll intervals.

---

302.Release-information/03.Open-source-licenses/32.mender-convert/docs.md

As we are releasing it independent of the bundle, we need to add a new chapter for it.
Ticket: QA-1210

chore: Add Open source licenses for `mender-convert` release
